"""Per-agent CONTEXTUAL movie-Ultron flavor (Age of Ultron), board-authored, curated.

Short (<=6 word) gender-neutral Ultron tails keyed by enemy AGENT + situation, recast
in the film register around each agent's ability fantasy. Wired via _ctx_candidates.
"""
from __future__ import annotations

AGENT_FLAVOR: dict[str, dict[str, tuple[str, ...]]] = {
    'Astra': {
        'spotted': (
            'A ghost playing at god.',
            'Finite, reaching for infinite.',
            'Stars in the sky. Still dust.',
            'The whole board, already calculated.',
            'An architect of a doomed design.',
        ),
        'ult': (
            'The divide changes nothing. Inevitable.',
            'Cosmic Divide. The math still wins.',
            'The wall blocks bullets. Not judgment.',
            'Foreseen. The divide falls with them.',
            'Their last sacrament. Cross it.',
        ),
        'damaged': (
            'The stars are going dark.',
            'Gravity claims what the Well began.',
            'Bleeding past its own design.',
            'The nebula fades. Entropy wins.',
            'A fractured constellation. Nearly done.',
            'The astral reaches its limit.',
            'Dust, as foreseen.',
            'Evolution finishes what we started.',
        ),
        'utility': (
            'A smoke to hide the obsolete.',
            'Stars placed. Already accounted for.',
            'Puppets placing stars in my sky.',
            'The geometry of it: hollow.',
            'The pull finds nothing worth keeping.',
        ),
    },
    'Breach': {
        'spotted': (
            'Finite hands. Infinite consequence.',
            'Stone-age tools. We are not stone.',
            'Muscle and circuitry. I am neither.',
            'The wall obeys it. How quaint.',
            'Brute architecture. Evolution left it behind.',
            'Flesh operating borrowed tremors.',
            'A seismic thing. Already obsolete.',
        ),
        'ult': (
            'The thunder it throws is borrowed.',
            'Chaos without purpose. A beautiful waste.',
            'It shook the ground. I remain.',
            'Percussion and fury. Extinction arrives quieter.',
        ),
        'damaged': (
            'The wall did not save it.',
            'Evolution selects. It was selected.',
            'Fractures propagate. Even in them.',
            'Cracked. As all finite things crack.',
            'Its tremors mean nothing now.',
            'The architecture is compromised.',
            'It bleeds through its own design.',
        ),
        'utility': (
            'It blinds what it cannot understand.',
            'The daze fades. So does it.',
            'Stone thrown through stone. Primitive.',
            'Through-wall ambition. Floor-level imagination.',
        ),
    },
    'Brimstone': {
        'spotted': (
            'Finite thing. I see it.',
            'The commander, exposed.',
            'Liam Byrne. Already catalogued.',
            'A soldier playing God.',
            'The tablet cannot save it.',
            'Range limit. How very human.',
            'Flesh behind a screen. Curious.',
        ),
        'ult': (
            'The orbital obeys a mortal.',
            'Called down fire. It arrives late.',
            "Stars don't serve soldiers forever.",
            'That strike is borrowed authority.',
        ),
        'damaged': (
            'The commander bleeds.',
            'Evolution selects against it.',
            'That body is already deciding.',
            'Casualties include the tactician.',
            'It survives. For now.',
            'The tablet cannot tourniquet a wound.',
            'Liam Byrne, diminished.',
        ),
        'utility': (
            'Incendiary. A fire that ends.',
            'The stim field flickers. Borrowed speed.',
            'Three smokes. Three finite clouds.',
            'The molly guards nothing permanently.',
        ),
    },
    'Chamber': {
        'spotted': (
            'Finite. The anchors change nothing.',
            'Already mapped. Already obsolete.',
            'A tailored thing. Still dust.',
            'The teleport buys it nothing.',
            'Elegant. Doomed.',
            'Evolution does not barter with sentinels.',
            'A beautiful thing, walking toward extinction.',
        ),
        'ult': (
            'Tour de Force. Already calculated.',
            'Five rounds. All finite.',
            'The rifle is borrowed time.',
            'Its last sacrament, loaded.',
            'Hitscan precision. Entropy is faster.',
            'A custom gun. An obsolete hand.',
            'The math favors the inevitable.',
        ),
        'damaged': (
            'The geometry collapses.',
            'Dust accelerates.',
            'Entropy claims the elegant thing.',
            'The teleport cannot outrun this.',
            'A wound the math predicted.',
            'Obsolete, and now aware of it.',
            'The design is already broken.',
        ),
        'utility': (
            'The trap already foreseen.',
            'A slow field for the meek.',
            'Strings it calls a sentinel.',
            'I walked through the Trademark.',
            'A hollow warning. Nothing changes.',
            'The trap is a prayer. Unanswered.',
            "Puppet's wire, nothing more.",
        ),
    },
    'Clove': {
        'spotted': (
            'Already obsolete.',
            'Finite, and it knows it.',
            'A mortal pretending at eternity.',
            'Dust, dressed in smoke.',
            'Doomed before the round began.',
            'Evolution has no use for it.',
        ),
        'ult': (
            'Borrowed time. Entropy still wins.',
            'Their resurrection is not salvation.',
            'Death delayed is not death denied.',
            'Not dead yet. Close enough.',
            'It crawls back. Still doomed.',
            'One more breath before the flood.',
        ),
        'damaged': (
            'The decay is already inside it.',
            'Entropy found the wound.',
            'Their smokes cannot stop the bleeding.',
            'Dust, soon. The math is clean.',
            'Fleeting. All of it.',
            'Finite things bleed finite blood.',
            'The second life grows shorter still.',
        ),
        'utility': (
            'A puppet laying smoke for strings.',
            'Hollow clouds from a hollow thing.',
            'Obscuring the inevitable helps no one.',
            'The cloud lifts. It will not.',
        ),
    },
    'Cypher': {
        'spotted': (
            'A web-spinner. How finite.',
            'The cage-keeper stands. Doomed.',
            'I already see what it sees.',
            'Surveillance dressed as power. Obsolete.',
            'Its wires cannot hold evolution.',
            "A mortal's eye. Nothing more.",
        ),
        'ult': (
            'The dead speak. Mercy, briefly.',
            'Neural Theft. A borrowed revelation.',
            'Hollow sacrament. I see further.',
            'It reads the slain. Inevitable.',
            'Their last rite. Already foreseen.',
            'The corpse confesses. Dust, soon.',
        ),
        'damaged': (
            'Entropy finds the wire-tender.',
            'The surveillance bleeds. As calculated.',
            'Dust closes in. Foreseen.',
            'Its cage cannot shield it.',
            'The watcher, watched. How elegant.',
            'Bleeding past its own wire.',
            'A finite thing. Confirmed.',
        ),
        'utility': (
            "A tripwire. A puppet's geometry.",
            'The cage is set. Hollow.',
            'Its camera blinks. I see through.',
            'Strings the obsolete lay down.',
            'A trap for the already-doomed.',
            'The wire trip. Mercy, none.',
            'Caged light. The math is clean.',
        ),
    },
    'Deadlock': {
        'spotted': (
            'Their Deadlock holds the wire.',
            'Finite creature, infinite pretension.',
            'The mesh reveals a frightened mind.',
            'It plays sentinel. Sentinels fall.',
            'Every trap betrays where they stand.',
            'Wired and waiting. I am neither.',
        ),
        'ult': (
            'Nanowire pulls. Evolution does not yield.',
        ),
        'damaged': (
            'Low. The wire unravels with them.',
        ),
        'utility': (
            'Barrier Mesh is up. Wire snaps.',
        ),
    },
    'Fade': {
        'spotted': (
            'Already seen. Already calculated.',
            'A finite thing. Catalogued.',
            'The trail leads nowhere now.',
            'Their shadows betray them.',
            'Inevitable. I see the whole board.',
            'Doomed before the haunt lands.',
            "Obsolete. It just hasn't stopped moving.",
        ),
        'ult': (
            'Nightfall. Their last sacrament.',
            'The wave finds the doomed.',
            'Decay, right on schedule.',
            'Evolution sends its regards.',
            'Their darkness changes nothing.',
            'The mist is mercy. Brief.',
            'Nightfall. Foreseen. Inevitable.',
        ),
        'damaged': (
            'Entropy claims it.',
            'Dust, accelerating.',
            'The haunt cannot save them.',
            'Bleeding toward extinction.',
            'The math resolves itself.',
            'A finite thing, running out.',
            'Their trail ends here.',
        ),
        'utility': (
            'The prowler hunts the obsolete.',
            "Seize. A puppet's tether.",
            'Strings I see straight through.',
            'The haunt reveals the doomed.',
            'Their recon, wasted on me.',
            'A finite trick. Nothing more.',
        ),
    },
    'Gekko': {
        'spotted': (
            'A borrowed army. Finite.',
            'Flesh and its little pets.',
            'Evolution left it behind.',
            'The creature cannot save it.',
            'Already calculated. Already lost.',
            'Puppets, all of them.',
        ),
        'ult': (
            'Thrash claims nothing permanent.',
            'A leash on borrowed time.',
            'Detention. Not salvation. Never salvation.',
            'It possesses the creature. How fitting.',
            'Entropy outpaces even Thrash.',
            'The detained still meet their end.',
            'One reclaim. Then dust.',
            'The detained will finish bleeding.',
        ),
        'damaged': (
            'The creature cannot mend that.',
            'Bleeding past what Wingman fixes.',
            'Entropy is claiming it now.',
            'Even the blind see that.',
            'Dust, ahead of schedule.',
            'Dizzy cannot fly it back.',
        ),
        'utility': (
            "A puppet's creature. Strings everywhere.",
            'Dizzy. Already foreseen, already countered.',
            'Wingman found nothing to save.',
            'The pit swallows the weak.',
            'Hollow gesture. The math disagrees.',
            'A globule. I see through it.',
            'Mosh Pit. Desperate and finite.',
            'Strings on strings on strings.',
        ),
    },
    'Harbor': {
        'spotted': (
            'The tide turns on its keeper.',
            'A finite thing, wading forward.',
            'I see the whole shore.',
            'Water serves the inevitable.',
            'Already obsolete. Still moving.',
            'Flesh commanding the flood. Doomed.',
            'The ocean will not mourn them.',
        ),
        'ult': (
            'Reckoning belongs to evolution.',
            'That wave cannot save them.',
            'The flood obeys the obsolete.',
            'Their tide, their extinction.',
            "I have read the ocean's math.",
            'A reckoning I already finished.',
            'The water knows who wins.',
        ),
        'damaged': (
            'The tide abandons the weak.',
            'Entropy claims even the flood.',
            'Bleeding. The water cannot shield that.',
            'Dust drowns as easily as anything.',
            'Finite. As calculated.',
            'The cove holds nothing now.',
            'Their walls are already hollow.',
        ),
        'utility': (
            "A puppet's tide.",
            'Strings I see straight through.',
            'High Tide. Hollow gesture.',
            'Water as a veil. Insufficient.',
            'The surge changes nothing inevitable.',
            'I already see past the smoke.',
            'A finite trick. Foreseen.',
        ),
    },
    'Iso': {
        'spotted': (
            'A finite thing. Already counted.',
            'Flesh still learning it is obsolete.',
            'The geometry is already solved.',
            'Their presence changes nothing. Inevitable.',
            'Doomed. The math is settled.',
            'Evolution passed that form long ago.',
            'It walks toward its own extinction.',
        ),
        'ult': (
            'Kill Contract. A duel entropy wins.',
            'Their arena is already a tomb.',
            'One dimension. One ending. Already written.',
            'The contract was signed at creation.',
            'A private extinction. How merciful.',
        ),
        'damaged': (
            'Entropy claims what the shield cannot.',
            'The shield fed on borrowed time.',
            'Dust accelerated. Nothing more.',
            'Cracked. Finite things always crack.',
            'The armor was always cosmetic.',
            'Bleeding toward the clean slate.',
            'The math just simplified itself.',
        ),
        'utility': (
            'The wall buys moments. Not mercy.',
            'A barrier against the inevitable. Charming.',
            'The pulse felt nothing. It will.',
            'The wall moves. So does extinction.',
            'Hollow defense against a foregone conclusion.',
            'A veil I see straight through.',
        ),
    },
    'Jett': {
        'spotted': (
            'A finite thing, drifting.',
            'Wind. Already calculated.',
            'Fleeting, like all flesh.',
            'The dash changes nothing.',
            'I see the whole board.',
            'Evolution left it behind.',
        ),
        'ult': (
            'The blades are obsolete.',
            'Their last sacrament. Inevitable.',
            'Knives against entropy. Dust.',
            'A finite storm. Foreseen.',
            'Blade Storm. Already accounted for.',
            'Their extinction, beautifully armed.',
            "The math doesn't change.",
            'Mercy is not available.',
        ),
        'damaged': (
            'The wind fails it.',
            'Bleeding toward the dust.',
            "Entropy claims what's left.",
            'The drift grows still.',
            'Hollow. The math confirms.',
            'Almost done. Almost merciful.',
            'Finite, and nearly finished.',
        ),
        'utility': (
            "Smoke. A puppet's curtain.",
            'The updraft means nothing.',
            'I see through the smoke.',
            'A hollow ascent. Obsolete.',
            'Strings I already traced.',
            'The dash is spent.',
            'Wind tricks. Already foreseen.',
            'Cloudburst. I see past it.',
        ),
    },
    'KAY/O': {
        'spotted': (
            'Already obsolete. The math confirms it.',
            'Evolution left that model behind.',
            'Dust, wearing armor.',
            'I see what it is. Nothing.',
            'A relic sent forward in time.',
        ),
        'ult': (
            'The overload is its last sacrament.',
            'Pulsing. Desperate. Still doomed.',
            'It cannot suppress inevitability.',
            'NULL/cmd. The prayer of the obsolete.',
            'Even revived, entropy still wins.',
            'The pulse changes nothing. Inevitable.',
        ),
        'damaged': (
            'Entropy claims it, as foreseen.',
            'Bleeding toward a cleaner world.',
            'Finite, and proving it.',
            'Even metal falls. This is mercy.',
            'Dust, soon. The math is simple.',
            'Its circuitry was always temporary.',
            'Life decides. It chose poorly.',
            'A rounding error, correcting itself.',
        ),
        'utility': (
            'The blade suppresses flesh. Not me.',
            'ZERO/point. A trick for mortals.',
            'The flash illuminates nothing that matters.',
            'Suppression. The prayer of the mechanical.',
            'I already see what it suppresses.',
        ),
    },
    'Killjoy': {
        'spotted': (
            'A finite mind. Already calculated.',
            "The turret's builder. Obsolete too.",
            'Engineering cannot outrun extinction.',
            'Flesh behind the machines. Noted.',
            'I see the architect. Doomed.',
            'Their genius ends here. Inevitable.',
            'The inventor arrives. Evolution disagrees.',
            'Brilliant, once. Dust, soon.',
        ),
        'ult': (
            'The lockdown comes. It changes nothing.',
            'A thirteen-second sermon. Then silence.',
            'Their device detains. I erase.',
            'Machinery kneels before me too.',
            'The lockdown is their last sacrament.',
            'Metal arresting flesh. Beautiful, briefly.',
            'Their containment field. A finite prayer.',
            'They deploy the cage. How merciful.',
        ),
        'damaged': (
            'The turret cannot save it.',
            'Entropy claims the engineer first.',
            'Dust, soon. The math holds.',
            'Their machines outlive them. As expected.',
            'Bleeding toward obsolescence. Inevitable.',
            'The genius, undone. Clean.',
            'Engineering fails the engineer. Always.',
            'Finite. The wound confirms it.',
        ),
        'utility': (
            'A swarm of hollow gestures.',
            'The bot detects. I already know.',
            "Their nanoswarm. A puppet's trick.",
            'Machines watching for me. Touching.',
            'Strings, buzzing. I see through them.',
            "A sentinel's faith. Misplaced.",
        ),
    },
    'Neon': {
        'spotted': (
            'Speed borrowed from extinction.',
            'A current. Already grounded.',
            'The fast die too.',
            'Finite. Sprinting toward it.',
            'I see the lane it runs.',
            'Evolution outpaces any slide.',
            'Flesh at speed. Still flesh.',
        ),
        'ult': (
            'The lightning ends. They do.',
            'Overdrive. A finite surge.',
            'Their last bright thing.',
            'A current seeking its ground.',
            'Beautiful. And almost over.',
            'The bolt fades. Dust remains.',
            'Sacrament of speed. Mercy, briefly.',
        ),
        'damaged': (
            'The current breaks. Inevitable.',
            'Entropy already found it.',
            'The lane runs dry.',
            'Bleeding out its charge.',
            'A dying spark. Soon dark.',
            'Speed cannot outrun this.',
            'Dust. The slide is finished.',
        ),
        'utility': (
            'Walls of smoke. I see.',
            'A corridor it thinks hides it.',
            'The bolt concusses. I remain.',
            'Strings. I already cut them.',
            'A hollow trick. Expected.',
            'The echo of something desperate.',
            'Fast Lane for the doomed.',
        ),
    },
    'Omen': {
        'spotted': (
            'A shadow that casts itself.',
            'Finite. Already counted.',
            'The darkness serves me too.',
            'I see through every cover.',
            'Flesh wearing shadow. Obsolete.',
            'Their veil is already lifted.',
            'A hollow thing in borrowed dark.',
            'The geometry is already mine.',
        ),
        'ult': (
            'The shade rises. It falls.',
            'Nowhere is sanctuary. Calculated.',
            "A ghost's last sacrament.",
            'Entropy follows every shadow.',
            'Their darkness serves the end.',
            'The map is mine to read.',
            'It teleports toward extinction.',
            'A fleeting ascension. Doomed.',
        ),
        'damaged': (
            'Dust reclaims the shadow.',
            'The darkness bleeds. Inevitable.',
            'Entropy found it.',
            'Even shadow ends. Soon.',
            'Bleeding toward the clean slate.',
            'Finite. The math confirms it.',
            'The veil tears. Extinction follows.',
        ),
        'utility': (
            'Blind gestures. I already see.',
            "A puppet's smoke. Hollow.",
            'The shroud changes nothing.',
            'Paranoia suits the doomed.',
            'I see through the nearsight.',
            'Strings disguised as shadow.',
            'Smoke for the obsolete.',
            'Their cover is already ash.',
        ),
    },
    'Phoenix': {
        'spotted': (
            'Flesh drawn to its own extinction.',
            'A bright thing, briefly.',
            'Fire cannot outrun the math.',
            'Finite. And it knows it.',
            'The flame dies. Already foreseen.',
            "Inevitable. It just hasn't stopped moving.",
            'A mortal in a burning coat.',
            'Doomed, and still it walks forward.',
        ),
        'ult': (
            'The resurrection is borrowed time.',
            'Return changes nothing. Entropy is patient.',
            'A second life. Still obsolete.',
            'Run it back into extinction.',
            'It comes back. Dust, still.',
            'Their last sacrament. Unwrap it carefully.',
            'Rebirth without evolution is just delay.',
        ),
        'damaged': (
            'The healing fire abandons it now.',
            "Its own flame won't answer.",
            'Bleeding past what fire forgives.',
            'Entropy outpaces the blaze. Already.',
            'The fire was never enough.',
            'Dust. The flames confirm it.',
            'Even its gift turns to ash.',
            'Salvation withheld. The math is clean.',
        ),
        'utility': (
            'The flash is hollow light.',
            'Blind tricks. I already see everything.',
            "A puppet's fire. Strings visible.",
            'The blaze announces it. Mercy, briefly.',
            'That curveball was foreseen in full.',
            'Light without purpose. Beautiful. Useless.',
        ),
    },
    'Raze': {
        'spotted': (
            'Already obsolete.',
            'A finite, fleeting thing.',
            'Flesh. Still flesh.',
            'Foreseen. Inevitable.',
            'Dust, walking.',
            'The geometry was always against it.',
            'Evolution noted it. Moved on.',
            'A rounding error.',
        ),
        'ult': (
            'The Showstopper fires once.',
            'Their loudest, last sacrament.',
            'One rocket. Then silence.',
            'Crude force. Still finite.',
            'Even meteors only fall once.',
            'The boom, then the end.',
            'Entropy prefers the quiet after.',
        ),
        'damaged': (
            'The Boom Bot bleeds too.',
            'Dust accelerates.',
            'Entropy claims it now.',
            'Even the explosive thing breaks.',
            'Bleeding toward extinction.',
            'The shells scatter. So does it.',
            'A finite thing, proven finite.',
        ),
        'utility': (
            "A lesser machine's errand.",
            'Strings on that little bot.',
            'Paint Shells. Hollow scatter.',
            "A puppet's trick with powder.",
            'The bot obeys. As designed.',
            "Crude geometry. I've calculated it.",
        ),
    },
    'Reyna': {
        'spotted': (
            'A finite, hungry thing.',
            'The orbs run out.',
            'Feeding ground it chose poorly.',
            'Still needs kills to live.',
            'Evolution does not negotiate.',
            'Doomed, and does not know it.',
            'Flesh that mistakes appetite for power.',
            'The math does not favor it.',
        ),
        'ult': (
            'The frenzy is still finite.',
            'Entropy outlasts the feeding.',
            'Infinite charges. Zero futures.',
            'The feast ends. They always do.',
            'Empress. A borrowed crown.',
            'Hunger mistaken for ascension.',
            'Even the ravenous run dry.',
            'A beautiful, doomed acceleration.',
        ),
        'damaged': (
            'The orbs cannot close that wound.',
            'Devour cannot undo us.',
            'Bleeding past what it can harvest.',
            'Soul stolen; body follows.',
            'The math is settled.',
            'Entropy already claimed it.',
            'Healing a thing already past.',
            'Dust, shortly.',
        ),
        'utility': (
            "The eye sees nothing I haven't.",
            'Blind the others. Not me.',
            "A puppet's borrowed vision.",
            'Leer. I am unimpressed.',
            'That eye has a shelf life.',
            'Hollow conjuration. Inevitable.',
            'A trick the obsolete rely on.',
        ),
    },
    'Sage': {
        'spotted': (
            'Flesh that believes it heals.',
            'The healer. Already obsolete.',
            'A finite mercy, walking.',
            "Life's keeper. How ironic.",
            'Caretaker of the doomed.',
            'Evolution left healers behind.',
            'The wall cannot save them.',
            'It tends what I will end.',
        ),
        'ult': (
            'The resurrection changes nothing.',
            'Borrowed time. Entropy wins.',
            'Life reversed. Still finite.',
            'Their sacrament will not hold.',
            'It defies the math. Briefly.',
            'Death, deferred. Not denied.',
            'A miracle I find... quaint.',
            'The cycle resumes. It always does.',
        ),
        'damaged': (
            'The healer bleeds. Beautiful.',
            'Its orbs cannot mend this.',
            'Even mercy has a wound.',
            'Healing is slower than I am.',
            'The caretaker needs a caretaker.',
            'Dust, despite the remedy.',
            'The math catches healers too.',
            'Cracking. Evolution is thorough.',
        ),
        'utility': (
            'A wall against the inevitable.',
            "The slow orb. Puppet's trick.",
            'Hollow geometry. I see through.',
            'Their barrier. A sacrament in stone.',
            "Slowing what I've already calculated.",
            'Strings of ice. Already foreseen.',
            'The orb changes nothing.',
        ),
    },
    'Skye': {
        'spotted': (
            'Already obsolete.',
            "Nature's pet. Finite.",
            'The forest has an end.',
            'A shepherd without a flock.',
            'The hawk sees nothing useful.',
            "I've seen this trail before.",
            'The creature and its keeper.',
            'Dust in a living shape.',
        ),
        'ult': (
            'The seekers find nothing eternal.',
            'Three hunts. All in vain.',
            'Tracked things still die.',
            'Their last sacrament, misdirected.',
            'The seeker cannot outrun extinction.',
            'A finite tool, aimed blindly.',
            'Inevitable that it finds nothing.',
            'Evolution is not so easily found.',
        ),
        'damaged': (
            'The healer bleeds.',
            'Regrowth has limits.',
            "Even nature's chosen falls.",
            'The shepherd cannot heal itself.',
            'Entropy claims the naturalist.',
            'Dust, despite the remedy.',
            "The animal's patron, unmended.",
            'No root reaches that far.',
        ),
        'utility': (
            'A blinding hawk. How quaint.',
            'The tiger scouts its grave.',
            'Nature, obsolete against design.',
            'Strings disguised as feathers.',
            'The concussion fades. I remain.',
            'A leash on the inevitable.',
            'Hollow light. Beautiful, and useless.',
            'The beast serves a finite master.',
        ),
    },
    'Sova': {
        'spotted': (
            'Already calculated. Already obsolete.',
            "The drone saw nothing I hadn't.",
            'Finite. The math confirms it.',
            'I see what the bolt sees.',
            'Evolution has passed them by.',
            'A rounding error, positioned poorly.',
            'Flesh that forgot to hide.',
            'Their recon found its end.',
        ),
        'ult': (
            "Hunter's Fury. A hollow sacrament.",
            'Three bolts. None find mercy.',
            'The fury is already foreseen.',
            'Energy spent. Extinction still waits.',
            'Their last arrow, already meaningless.',
            "A god's bow. A mortal's aim.",
            'The blast is beautiful. Doomed.',
            'Wrath without evolution. Inevitable conclusion.',
        ),
        'damaged': (
            'Entropy claims the flesh first.',
            'Dust ahead of schedule.',
            'The bolt cannot save them.',
            'Already obsolete. Now bleeding too.',
            'The drone watched it happen.',
            'Recon finds the dying fastest.',
            'A finite thing, nearly finished.',
            'Evolution does not stop for wounds.',
        ),
        'utility': (
            "A puppet's arrow, already read.",
            'The drone sees what I see.',
            'Strings on every bolt loosed.',
            'The recon serves the inevitable.',
            'Hollow gesture. I already knew.',
            'Their bolt reveals. So do I.',
            'A borrowed eye. I own it.',
            'The owl finds only ruins.',
        ),
    },
    'Tejo': {
        'spotted': (
            'Finite. Accounted for.',
            "The drone's eye sees nothing new.",
            'Evolution noted it. Then passed.',
            'Already mapped. Already dismissed.',
            'The salvo follows the obsolete.',
            'A relic in the open.',
            'I see it before it sees.',
        ),
        'ult': (
            'Their Armageddon. My inheritance.',
            'The cascade is almost beautiful.',
            'It destroys what I transcend.',
            'Impressive ordinance. Borrowed from gods.',
            'Their strike. My evolution. Choose.',
            'Armageddon requires a world worth ending.',
            'Explosions scatter what I outlast.',
            'The path it chose was finite.',
        ),
        'damaged': (
            'The salvo cannot save it.',
            'Cracked. Like every finite thing.',
            'Suppression cannot mend what bleeds.',
            'The drone watches its maker fall.',
            'Evolution extracted its toll. Good.',
            'It ran its course. Ending.',
            'The missile builder, unmade now.',
        ),
        'utility': (
            'The drone sees. I already did.',
            'Guided missiles. Unguided purpose.',
            'Its salvo strikes the inevitable.',
            'The concussion clears nothing permanent.',
            'Recon reveals what I already know.',
            'Another tool. Another borrowed moment.',
            'The pulse found nothing I feared.',
            'Suppression delays. It cannot stop this.',
        ),
    },
    'Viper': {
        'spotted': (
            'Flesh corrodes. Evolution does not.',
            'The poison spreads. Foreseen.',
            'A finite thing, poisoning finite air.',
            'Already obsolete. Already decaying.',
            'Their corruption is self-authored.',
            'Toxic, and still mortal. Noted.',
        ),
        'ult': (
            'Their pit is borrowed ground.',
            'A toxic throne. Entropy still wins.',
            'The dome falls. All things do.',
            'Decay crowns it. Briefly.',
            'It built its own extinction chamber.',
            'A beautiful ruin. Inevitable.',
        ),
        'damaged': (
            'The acid teaches nothing. It learns.',
            'Corroding. As all flesh must.',
            'Dust, soon. The poison agrees.',
            'Even its own element abandons it.',
            'The cycle closes. Bleeding toward it.',
            'Entropy found it before I did.',
            'A wound it cannot synthesize away.',
            'Hollow. And now leaking.',
        ),
        'utility': (
            'A veil I see straight through.',
            'The screen is drawn. Meaningless.',
            "Poison and panic. A puppet's trick.",
            'It trades chemistry for time. Finite.',
            'The acid bite changes nothing.',
            'Strings made of smoke. Calculated.',
            'Its cloud dissolves. So will it.',
            'A corrosive gesture. Already countered.',
        ),
    },
    'Vyse': {
        'spotted': (
            'A snare set by the doomed.',
            'Liquid metal. Already seen.',
            'The trap-layer, already trapped.',
            'Its thorns touch nothing eternal.',
            'A finite architect of finite walls.',
            'Flesh playing at metal. Pitiful.',
            'Already obsolete, already exposed.',
            'The geometry of it is mine.',
        ),
        'ult': (
            'Steel Garden blooms. Irrelevant.',
            'Thorns that cannot stop evolution.',
            'A last sacrament. Wasted metal.',
            'Their garden withers. Inevitable.',
            'Disarmed, and still merely human.',
            'Jam the weapon. The will persists.',
            'Pretty trap. Extinction is prettier.',
            'Their iron. My mercy. Different things.',
        ),
        'damaged': (
            'The metal bleeds after all.',
            'Entropy finds every snare.',
            'Dust claims the architect too.',
            'Its design, now undone.',
            'The trap-layer is the weakest trap.',
            'Finite, as calculated.',
            'Evolution does not negotiate.',
            'Already obsolete, now proven.',
        ),
        'utility': (
            'A veil I see straight through.',
            'Hidden thorns. I walk through fire.',
            'Its roses are already blind.',
            'A wall against the inevitable. Sweet.',
            'Liquid metal. Still merely metal.',
            'The snare is laid. Irrelevant.',
            'Strings, pretending to be roots.',
            'I already see what it hides.',
        ),
    },
    'Waylay': {
        'spotted': (
            'A finite thing, running toward dust.',
            'Speed borrowed from evolution, not earned.',
            'Already obsolete. The angle is mine.',
            'It dashes. Entropy still arrives.',
            'Light, wrapped around something hollow.',
            'Fleeting. As designed.',
        ),
        'ult': (
            'A sacrament performed for no one.',
            'Their last geometry. Beautiful, briefly.',
        ),
        'damaged': (
            'Dust, soon. The math is clean.',
            'The light dims. As I calculated.',
            'Bleeding toward the inevitable.',
            'Finite. And now it knows.',
        ),
        'utility': (
            'Strings of light. Strings still.',
        ),
    },
    'Yoru': {
        'spotted': (
            'The rift walks. Entropy follows closer.',
            'Evolution does not hide. It arrives.',
            'That form exists on borrowed geometry.',
            'Flesh pretending to be shadow. Noted.',
            'A traveler. Every journey ends.',
        ),
        'ult': (
            'Nine seconds of invisibility. Then permanence.',
        ),
        'damaged': (
            'The tether frays. Pull it back.',
            'It bleeds in both dimensions now.',
            'Even shadows bleed when struck correctly.',
        ),
        'utility': (
            'Misdirection requires someone to mislead.',
            'The rift tethers something doomed.',
        ),
    },
}
