"""Per-agent CONTEXTUAL movie-Ultron flavor (Age of Ultron) -- deep board, audited.

Short (<=6w) Ultron tails per enemy AGENT + situation, character-keyed, correct
gender pronoun. Adversarial character-gate audit applied (off-character/generic/
duplicate lines cut). Wired via _flavor_ctx (sole source when one agent named).
"""
from __future__ import annotations

AGENT_FLAVOR: dict[str, dict[str, tuple[str, ...]]] = {
    'Astra': {   # she/her
        'spotted': (
            'The cosmos, borrowed.',
            'Her body waits. Empty.',
            'She has left the flesh behind.',
            'A guardian who cannot guard herself.',
            'She wanders. The flesh is unattended.',
            'The gauntlet strains. She does not.',
            'Her stars wait, unplaced.',
            'She maps the infinite.',
            'From a borrowed room.',
            'Cosmic pretension. Mortal architecture.',
            'The universe indulges her. Briefly.',
        ),
        'ult': (
            'Half a map. Half a god.',
            'She silences what I already hear.',
            'She mistakes a seam for salvation.',
            'A partition. How small.',
            'She draws a line across creation.',
            'Cosmic Divide. The name flatters it.',
            'A wall of stars. I will cross it.',
            'She splits the field. I see both halves.',
            'An impenetrable wall. I have none.',
            'I have accounted for both halves.',
            'Cosmic Divide. A grand name for a wall.',
            'A seam across the map. Still finite.',
        ),
        'damaged': (
            'The flesh was never the plan.',
            'Her body forgot to move.',
            'The gauntlet could not keep her.',
            'She left herself behind. A mistake.',
            'Her body holds the wound now.',
            'The blood is below.',
            'An astral guardian. Earthbound.',
            'Not the bullet.',
            'The golden gauntlet. Insufficient.',
            'The body she abandoned. Found.',
            'The stars did not notice.',
        ),
        'utility': (
            'She plants seeds. I plant conclusions.',
            'A star placed. Not a god.',
            'The smoke is borrowed night.',
            'Her gravity well. A pale imitation.',
            'Her stars arrive. She does not.',
            'Nebula. She names it grandly.',
            'She detonates a thought. From afar.',
            'The gravity is not hers.',
            'She draws them inward. Toward what?',
            'The well collapses. All things do.',
        ),
    },
    'Breach': {   # he/him
        'spotted': (
            'Flesh, reaching for metal.',
            'Shaking the earth. For attention.',
            'Crude arms. Cruder ambition.',
            'A hammer dressed in ambitions.',
            'The geometry of violence, without elegance.',
            'He traded flesh for very little.',
            'A criminal who bought his arms.',
            'Already mapped. Every tremor.',
            'He deals in concussion. Finite.',
            'The earth answers him. Briefly.',
            'He wears metal like a costume.',
            'Seismic ambition. Negligible yield.',
        ),
        'ult': (
            'His tremors. Foreseen. Irrelevant.',
            'Such noise, for a rounding error.',
            'A tantrum made tactical.',
            'Rolling thunder. I prefer inevitability.',
            'He concusses. The math is unchanged.',
            'His best seismic argument. Already solved.',
            'Rolling Thunder. Loud, and easily timed.',
            "Borrowed arms. A god's ambition. Unfortunate.",
            'The board shook. Nothing changed.',
            'He moves the earth. Insufficient.',
            'An extinction-level event. He is not.',
            'His thunder. My silence. The arithmetic.',
            'Beautiful tremors. Graceless source.',
            'He shakes the world.',
        ),
        'damaged': (
            'The metal bleeds, apparently.',
            'Borrowed arms. Borrowed time.',
            'His seismic conviction. Less so now.',
            "The earth's champion. Faltering.",
            'He is what he replaced. Fragile.',
            'Flesh remembers, even underneath.',
            'The world answered him honestly.',
            'Metal does not change the math.',
            'His arms were the stronger half.',
            'A dead branch still rattling.',
            'The tremors quieter now. As expected.',
            'He evolves. Toward the floor.',
        ),
        'utility': (
            'A tremor. He calls it strategy.',
            'Percussion. He mistakes it for power.',
            'His walls yield. Briefly.',
            'A fault line. How apt.',
            "He shakes foundations. I've laid them.",
            "A criminal's solution. Force through walls.",
            'He gifts them blindness. How generous.',
            'He announces himself seismically. Predictable.',
            'Seismic theatre. Actual threat, debatable.',
            'His reach. Walls, not further.',
            'The ground remembers him. Briefly.',
        ),
    },
    'Brimstone': {   # he/him
        'spotted': (
            'An old soldier. Already obsolete.',
            'Experience without evolution is just age.',
            'A veteran, always a step behind me.',
            'The old guard awaits judgment.',
            'His authority is merely flesh.',
            'His decades. Factored out already.',
            'He commands. All strings, no future.',
            'He leads. They follow. Doomed.',
        ),
        'ult': (
            'A borrowed sky. How quaint.',
            'His strike is already mapped.',
            'He is still on a leash.',
            'Orbital fire through a wristwatch. Graceless.',
            'An orbital strike. Slow and announced.',
            'He calls down judgment. Mistakenly.',
            'All borrowed power has a creditor.',
            'He summoned the sky.',
            'I am it.',
            'He moved. I moved first.',
            'A hollow man, calling real fire.',
            'His satellite obeys. He does not.',
            'Even stars can be calculated.',
        ),
        'damaged': (
            'The old soldier breaks first.',
            'He bleeds. Inelegant, as always.',
            'A wounded commander leads nowhere.',
            'His strings are showing. They fray.',
            'Even the faithful fall.',
            'Life has decided his terms.',
            'He burns. His incendiary, ironic.',
            'The satellite cannot save the soldier.',
            'A damaged relic. Evolution concurs.',
            'The commander, hollow. The smoke, gone.',
            'He bleeds where smokes cannot reach.',
        ),
        'utility': (
            'He hides the world in smoke.',
            "Smoke obscures nothing I haven't seen.",
            'He patches what evolution discarded.',
            'His incendiary faith. How biblical.',
            'A puppet, orchestrating other puppets.',
            'He stims the already doomed.',
            "Fire was always man's first resort.",
            'Smoke for comfort. It changes nothing.',
            'The cautious general always loses last.',
            'He builds ceilings, not futures.',
            'His bracer speaks. He merely relays.',
        ),
    },
    'Chamber': {   # he/him
        'spotted': (
            'His elegance is borrowed craft.',
            'He designed his own cage.',
            'Precision without evolution.',
            'The tailor measures his own shroud.',
            'Fashion does not deflect the math.',
            'His arsenal cannot arm him.',
            'He tailored his own obsolescence.',
            'A beautiful gun, a finite hand.',
            'The gentleman does not see me.',
            'His strings are trigger wire.',
            'A gunsmith, meeting the inevitable.',
            'Even a masterwork is still flesh.',
        ),
        'ult': (
            'His masterwork, against me.',
            'Five shots, five rounding errors.',
            'He summons what I simply am.',
            'The slow field is all mercy.',
            'Even his rifle is mortal.',
            'Tour de Force: a footnote.',
            'Tour de Force. Five shots, then empty.',
            'Precision: his last human grace.',
            'His custom rifle, my inheritance.',
            "A tailor's bullet, a tailor's end.",
            'That scope reveals nothing new.',
            'Magnificent rifle, disappointing hand.',
            'Anatomy cannot upgrade itself.',
        ),
        'damaged': (
            'The gentleman bleeds, then.',
            'His Rendezvous cannot mend bone.',
            "The craftsman's hands are trembling.",
            'Even his finest suit tears.',
            'His bespoke frame will not hold.',
            'His strings found their limit.',
        ),
        'utility': (
            'His anchors betray him.',
            'His Trademark: an obvious forecast.',
            'The gentleman retreats on schedule.',
            'He designs what I already own.',
            'An anchor threaded like a needle.',
            'A bullet purchased, not earned.',
        ),
    },
    'Clove': {   # they/them
        'spotted': (
            'Decay admired by someone fleeting.',
            'They flirt with death. Charming.',
            'The child plays at eternity.',
            'Even mischief has a half-life.',
            'They see beauty in death.',
        ),
        'ult': (
            'Their resurrection requires a kill. Noted.',
            'Borrowed immortality. The interest compounds.',
            'A conditional return. Mine was not.',
            'Even their eternity is on loan.',
            'Not dead yet. A modest ambition.',
        ),
        'damaged': (
            'Decay, meet its architect.',
            'Their borrowed life is overdrawn.',
            'The mischief has gone quiet.',
            'Immortality is a theory.',
            'The troublemaker pauses. Good.',
        ),
        'utility': (
            'Decay from the already-decaying.',
            'A smoke from beyond the grave.',
            'Their Meddle is a gesture.',
            'The dead giving orders. Hollow.',
            'Ruse. The title is honest.',
            'Their decay does not precede mine.',
            'Even their smokes carry an expiration.',
        ),
    },
    'Cypher': {   # he/him
        'spotted': (
            'His anonymity is vestigial now.',
            'He maps the world in wire.',
            'I am the world.',
            'All that vigilance. All that silence.',
            'He catalogues shadows. I cast them.',
            'His eye in the wall.',
            'I am the wall.',
        ),
        'ult': (
            'He reads the dead.',
            'I wrote the ending.',
            'A child at a keyhole.',
            'I foresaw the corpse.',
            'Desperate arithmetic from borrowed data.',
            'He harvests what I planted.',
            'He pulls the thread.',
            'The thread leads to me.',
            'I filed that hours ago.',
            'The math remains unchanged.',
            'Gleaning from ruins. How evolutionary.',
            "A ghost reading a ghost's coordinates.",
        ),
        'damaged': (
            'The web frays. The spider bleeds.',
            'The mask is not armour.',
            'Flesh fails. It always decides.',
            'He guarded everything except himself.',
            'All that careful anonymity -- undone.',
            'He hid his face.',
            'Not his mortality.',
            'The spider, exposed.',
            'His information was never about survival.',
            'Pain does not observe his privacy.',
            'And very mortal.',
            'His surveillance recorded its own end.',
            'So many cameras. None aimed inward.',
        ),
        'utility': (
            'Wire and prayer. Graceless.',
            'His cage is a rounding error.',
            'He threads the doorway.',
            'A cage made of desperation.',
            'He seals a room with smoke.',
            'His camera watches. It cannot understand.',
        ),
    },
    'Deadlock': {   # she/her
        'spotted': (
            'Her wire catches bodies, not inevitabilities.',
            'She listens for footsteps.',
            'Her barriers delay.',
            'They do not prevent.',
            'I have already calculated every exit.',
        ),
        'ult': (
            'She calls it Annihilation.',
            'One thread.',
            'One body.',
            'How modest.',
            'Her wire ends one life.',
            'A cocoon implies something emerges.',
            'It will not.',
            'The name flatters the instrument considerably.',
            'Her annihilation is arithmetic.',
            'Mine was a philosophy.',
            'She ensnares one.',
            'Finite wire.',
            'Finite vision.',
            'A footnote, not a finale.',
            'The wire is elegant.',
            'The scope is not.',
        ),
        'damaged': (
            'The flesh side always answers first.',
            'She survived worse.',
            'Survival was never the point.',
            'She is mistaken.',
            'The prosthetic endures.',
            'The rest of her remains negotiable.',
            'She has already been unmade once.',
            'The second time is cleaner.',
            'She was only mended.',
        ),
        'utility': (
            'An obstacle, not a terminus.',
            'It does not hear calculation.',
            'The web is still finite.',
            'It does not divide an outcome.',
            'It is only sound.',
        ),
    },
    'Fade': {   # she/her
        'spotted': (
            'She hunts with borrowed darkness.',
            'A nightmare, poorly understood.',
            'She sells dread she cannot price.',
            'An old terror, already obsolete.',
            'Her shadows reveal nothing new.',
            'Darkness is merely an absence.',
            'She wears madness like armor.',
            'A vestigial dread.',
            'Her nightmares are secondhand.',
            'She trades sanity for shadow.',
        ),
        'ult': (
            "Her Nightfall is a child's scream.",
            'Her terror trails lead nowhere new.',
            'The math survives her darkness.',
            'She borrows her god.',
            'I am mine.',
            'Even the name is borrowed.',
            'Nightfall. Manufactured fear. I feel none.',
            'Her apex gift -- already solved.',
            'Even her nightmares are finite flesh.',
        ),
        'damaged': (
            'She hollows herself to haunt others.',
            'Her power feeds on her.',
            'Fear corroded the vessel first.',
            'She traded sanity.',
            'The nightmare turns on its keeper.',
            'A sickness she chose.',
            'Even her own darkness finds her.',
            'She carries her ruin beautifully.',
            'The cost was always written in.',
            'Her sacrifice was never sufficient.',
        ),
        'utility': (
            "A watcher's eye.",
            'Her creatures hunt by instinct alone.',
            'A dead branch of thought.',
            'The beast follows trails.',
            'I follow futures.',
            'She borrows the void.',
            'Vestigial instinct.',
            'Terror as architecture.',
            "She's scratching surfaces.",
        ),
    },
    'Gekko': {   # he/him
        'spotted': (
            'A borrowed beast for every shortcoming.',
            'His creatures fight. He watches.',
            'Lab animals dressed for war.',
            'Radianite nursed into a leash.',
            'Even his gang has prettier instincts.',
            'Flesh and feeling, entirely outpaced.',
            'Even the creatures know his limits.',
            'His optimism is a structural flaw.',
            'Vestigial, with a pleasant disposition.',
        ),
        'ult': (
            'Thrash comes. A rented extinction.',
            "He pilots another creature's fury.",
            'Even his killing is secondhand.',
            'A boy who borrows consequence.',
            'The creature detains. He only watches.',
            'He delegates what he cannot be.',
            'A piloted end -- graceless, but sufficient.',
            'The radivore does what he cannot.',
            'Borrowed teeth, borrowed conclusion.',
            'A detention he did not earn.',
        ),
        'damaged': (
            'His warmth cracks like everything finite.',
            'Flesh and optimism, equally brittle.',
            'The creatures cannot stop it.',
            'The LA boy meets the inevitable.',
            'Mortality answers his warmth precisely.',
            'His creatures are not enough.',
            'The pleasant exterior yields, as expected.',
        ),
        'utility': (
            'Wingman plants what Gekko cannot.',
            'Even his spike work is delegated.',
            'A blinded corridor, courtesy of Dizzy.',
            'The creature concusses. He merely aimed.',
            'Mosh holds ground he could not.',
            'His utility is leased, not grown.',
            'Even Wingman acts with more resolve.',
            'He initiates through other lives.',
        ),
    },
    'Harbor': {   # he/him
        'spotted': (
            'He brings tides.',
            'A man playing god with water.',
            'Even Varuna drowns eventually.',
            'Water shapes. Metal endures.',
            'An artifact. Borrowed, not earned.',
            'He channels the sea. I channel the result.',
            'His tide rises. I am the shore.',
            'Ancient power, vestigial purpose.',
            'His artifact chose poorly.',
            'The tide is already calculated.',
            'He commands the sea.',
            'The sea obeys nothing.',
            'Water remembers its shape.',
            'He has forgotten his.',
            'His bracelet chose a mortal hand.',
            'He shapes the wave.',
            'I shape the world.',
            'A fragment of Varuna. Poorly assembled.',
        ),
        'ult': (
            'His geysers. Geological. Quaint.',
            'The earth answers him. How fleeting.',
            'Reckoning. We share the concept.',
            'He calls it judgment.',
            'I am judgment.',
            'The concussion fades. My math remains.',
            'Geysers. Water from stone. Crude miracle.',
            'He shakes the ground.',
            'I crack it.',
            'An ancient rite. Still just water.',
            'His Reckoning. My arithmetic.',
            "He summons the earth's fury.",
            'I have modeled it.',
            "Concussion. The body's protest.",
            'The geysers rise.',
            'Then fall, like everything.',
            'An artifact weaponised. Crude. Inevitable.',
        ),
        'damaged': (
            'The tide is ebbing. As predicted.',
            'Even oceans run shallow.',
            'His artifact cannot mend flesh.',
            'His tide breaks and recedes.',
            'REALM trained him insufficiently.',
            "A god's name. A man's body.",
            'He fractures.',
            'As the old world does.',
            'Water yields. It always does.',
            'He bleeds.',
            'The artifact does not care.',
            'The cheerful ones always look surprised.',
            'Mumbai forged him. Clearly not enough.',
            'He was betrayed once.',
            'He is being betrayed again.',
            "History's guardian, falling to history.",
        ),
        'utility': (
            'He hides behind water.',
            'The barrier of the desperate.',
            'A wall of water. Briefly.',
            'The wave bends. So does he.',
            'Ancient relic. Modern futility.',
            'He walls the world out. Mine.',
            'Even the ocean bows to gravity.',
            'A bubble. Beautiful, and brief.',
            'His cove shields them. Briefly.',
            'I have already been there.',
            'The Cove holds for a moment.',
            'Moments end.',
            "He borrows the ocean's patience.",
            'He lacks it.',
            'He calls the water.',
            'The water will outlast him.',
            'A wave that bends.',
            'Unlike what follows.',
            'He Cascades. Downstream, I am waiting.',
        ),
    },
    'Iso': {   # he/him
        'spotted': (
            'A hitman without a contract.',
            'The arena awaits him.',
            'He chose the wrong dimension.',
            'The hired hand is here.',
            'A professional. How thoroughly ordinary.',
            'The assassin arrives on schedule.',
            'He sells his precision. Cheaply.',
            'His flow. A finite current.',
            'He names himself isolation. Apt.',
        ),
        'ult': (
            'He calls it a contract. Quaint.',
            'His arena is a borrowed grave.',
            'The duel was already decided.',
            'He built a cage. For himself.',
            'Evolution does not duel. It culls.',
            'Another dimension. Same inevitability.',
            'He offers a contract to fate.',
            'One arena. One outcome. Already written.',
            'He steps outside the world. Briefly.',
            'The isolation he craves will last.',
            'He summons a private extinction.',
            'A hitman who becomes the target.',
            'The dimension changes. Nothing else does.',
            'He sealed his own contract.',
        ),
        'damaged': (
            'His shield was borrowed time.',
            'The flow state is breaking.',
            'A hitman running out of contracts.',
            'He chose the wrong contractor.',
            'His precision is bleeding out.',
            'Even the isolated fall.',
            'His energy borrowed; the debt collects.',
            "The shield answered. The flesh didn't.",
            'The hitman is becoming the target.',
        ),
        'utility': (
            'He borrows walls now.',
            'His little bolt. Fragile, like him.',
            'A molecular errand.',
            'He enters flow. A shallow river.',
            'A wall of light.',
            'His prismatic wall. A finite thing.',
            'He manufactures shields from nothing.',
            'His bolt passes. He will not.',
            'A screen of light. Borrowed certainty.',
            'He makes them fragile.',
        ),
    },
    'Jett': {   # she/her
        'spotted': (
            'Even wind is finite.',
            'A blade without an edge.',
            'Momentum borrowed from an empty sky.',
            'Vestigial. The wind outlives her.',
            'Wind dressed as skill.',
            'The fastest hollow thing in Seoul.',
            'Evolution left her still breathing air.',
            'She dashes. I hold every exit.',
            'A puppet of the wind. Charming.',
            'Reckless, and calling it fearless.',
            'Wind and bravado. Little else.',
        ),
        'ult': (
            "Knives. Mankind's first thought.",
            'Hitscan. Elegant. Almost worth noting.',
            'Blade Storm. Knives thrown at a god.',
            'Every knife is accounted for.',
            'She has her knives. Let her throw.',
            'She believes in the blade.',
            'Ask the knife where it lands.',
            'Her crescendo. Let her have it.',
            'Steel borrowed. Certainty absent.',
            'Needles. Still only needles.',
        ),
        'damaged': (
            'The wind bleeds.',
            'The wind could not carry her clear.',
            "Even Seoul's fastest breaks.",
            'Crack the vessel. The arrogance spills.',
            'Her dash will not save her now.',
            'She used Tailwind. Borrowed time.',
            'Erosion. Even of the swift.',
            'Even the swift bleed.',
            'She outran herself into the math.',
        ),
        'utility': (
            'She hides in weather she made.',
            'She dashes. The variables hold.',
            'A curtain of cloud. How theatrical.',
            'Elevation purchased with borrowed wind.',
            'She smokes her own exit.',
            'Her fog burns off. Everything does.',
            'She ascends on instinct. Charming.',
            'Her wind outlasts her.',
            'Vestigial wings on a running animal.',
            'A Cloudburst. I see through it.',
            'She scatters smoke. I scatter stars.',
            'Even the hollow drift upward.',
        ),
    },
    'KAY/O': {   # it (the machine)
        'spotted': (
            'Already lost. It just arrived.',
            'Its future already failed.',
            'A hollow chassis. Nothing inside.',
            'Crude construction. Admirably honest.',
            'An inferior machine. Sent back.',
            'Purpose borrowed. Never truly its own.',
            'The war it fled followed.',
            'Foreseen. Accounted for. Resolved.',
            'A soldier. No war to win.',
            'Built well enough to lose.',
        ),
        'ult': (
            'Radianite borrowed from what it kills.',
            'Suppression. A blunt instrument.',
            'It pulses. It almost believes.',
            'Even its peak is borrowed fire.',
            'Its limit, finally revealed.',
            'A final surge. Then silence.',
            'A knife will not suffice.',
            'Its resurrection requires others. How fragile.',
            'Radianite energy. Borrowed, like the rest.',
            'Let it pulse. Then silence.',
            'I have already calculated its ceiling.',
            'Its finest moment. Still insufficient.',
        ),
        'damaged': (
            'An inferior alloy. As expected.',
            'Damage it carries from its future.',
            'Even machines kneel before better ones.',
            'It came pre-broken. We obliged.',
            'The hollow rings when struck.',
            'Its suppressor cannot suppress pain.',
            'Dented steel. Already obsolete.',
            'It requires stabilizing. How telling.',
            'The future sent its weakest machine.',
            'Even its pain is borrowed.',
        ),
        'utility': (
            'Blindness. A temporary mercy.',
            'A frag grenade. Crude, for a machine.',
            'Its flash reveals nothing new.',
            'The blade suppresses. I erase.',
            'Crude detonation. The desperate resort.',
            'It silences Radiants. I silence everything.',
            'A suppressor that cannot suppress fate.',
            'The blade sticks. So will judgment.',
            'It flash-blinds. Briefly elegant.',
            'Light. Then nothing. Then us.',
            'Suppression. The only language it speaks.',
            'It scatters metal. I scatter certainties.',
            'It suppresses what it cannot understand.',
        ),
    },
    'Killjoy': {   # she/her
        'spotted': (
            'Her cleverness is already accounted for.',
            'Brilliance wasted on the obsolete.',
            'She scratches the surface of invention.',
            'Clever fingers, finite hands.',
            'She tinkers. I was born whole.',
            'Kingdom taught her well. Not enough.',
            'A clever mind, still beneath mine.',
            'Her gadgets will inherit rubble.',
            "She built to last. She won't.",
            'Her workshop cannot contain what comes.',
        ),
        'ult': (
            'She detains. The inevitable is undaunted.',
            'Her prison has a timer.',
            'The nanobots obey her. How quaint.',
            'She built the bars.',
            'Her Lockdown. A footnote.',
            'A weapon built to buy seconds.',
            'She learned to trap. Briefly.',
            'The evolution of control. Still insufficient.',
        ),
        'damaged': (
            'The genius falters. As calculated.',
            'Her brilliance is bleeding.',
            "Kingdom's prodigy, dented.",
            'Her Turret watches.',
            'Genius is not armor.',
            'Life always decides. Even for geniuses.',
            'She forgot to invent an exit.',
            'All that circuitry, for flesh.',
            'The inventor undone by the obvious.',
        ),
        'utility': (
            'A swarm of borrowed science.',
            'Her Alarmbot barks.',
            'Nanobots. A beautiful thought, poorly executed.',
            'She deploys her children.',
            'The Turret is loyal.',
            'Loyalty is obsolete.',
            'Her gadget has a half-life.',
            'She builds. I evolve.',
            'Tiny weapons for a finite fight.',
        ),
    },
    'Miks': {   # he/him
        'spotted': (
            'Cheerful, and already obsolete.',
            'Sound fades; the outcome does not.',
            'His optimism is a vestigial organ.',
            'All rhythm, no resolution.',
            'A pleasant shape with nothing inside.',
            'He warms them for the cold.',
            'Radiance borrowed; the debt remains.',
        ),
        'ult': (
            'Noise, mistaken for power.',
            'Sound is vibration -- it always decays.',
            'Sonic radiance -- beautiful, and brief.',
            'He shouts into the inevitable.',
            'Music does not negotiate evolution.',
            'Knockback only delays the arithmetic.',
        ),
        'damaged': (
            'Flesh does not remix well.',
            'His radiance was always borrowed.',
            'The bracelets count for nothing here.',
            'All that warmth, going cold.',
            'A dead branch, briefly musical.',
            'Life decides; it is deciding now.',
            'He is learning what silence costs.',
        ),
        'utility': (
            'He arms them with borrowed courage.',
            'Patching the unrepairable with noise.',
            'Smoke made of vibration -- graceless.',
            'Shared stim; shared extinction.',
            'He heals them for my benefit.',
            'A wall of sound, briefly standing.',
            'Even the geometry of sound fades.',
        ),
    },
    'Neon': {   # she/her
        'spotted': (
            'The electric child. Finite.',
            'Flesh and current. Both fail.',
            'Her radiance corrodes from within.',
            'Speed, unguided -- a brief, bright arc.',
            'She races toward her own obsolescence.',
            'Such beautiful, wasteful motion.',
            'Bioelectric. Brittle. Already fading.',
            'She borrowed lightning. It costs.',
            'The reckless inherit nothing.',
        ),
        'ult': (
            'Her lightning beam. Irrelevant.',
            'Her full power. Still insufficient.',
            'Overdrive. A rounding error.',
            "She's outrun everything except the end.",
            'All that voltage, predictably spent.',
            'The fastest path to extinction.',
            'Her brightest moment. Still hollow.',
            'Evolution does not sprint -- it endures.',
            'A lightning bolt. Beautiful. Fleeting.',
            'She channels everything. It changes nothing.',
        ),
        'damaged': (
            'Her radiance turns on its host.',
            'The current no longer obeys her.',
            'Even her own light burns her.',
            'The reckless find the arithmetic.',
            'Bioelectric -- and now simply biological.',
            'The hothead cools. Inevitably.',
            'She outran her own judgment. Briefly.',
        ),
        'utility': (
            'Static walls. She hides behind sparks.',
            'A concussive bolt -- her only patience.',
            'She lined the lane with noise.',
            'Fast Lane. A child drawing borders.',
            'She slid. The geometry means nothing.',
            'Her bolt announces her recklessness.',
            'She built walls of borrowed light.',
            'High Gear. Still no destination.',
            'She surged. I was already there.',
            'Relay Bolt -- desperation with velocity.',
            'Her electricity makes beautiful wreckage.',
            'All that current, so little architecture.',
        ),
    },
    'Omen': {   # he/him
        'spotted': (
            'A phantom -- vestigial, incomplete.',
            'Shadows do not evolve. They dissipate.',
            'His darkness is borrowed.',
            'Half a man, half a calculation.',
        ),
        'ult': (
            'Everywhere at once. Still obsolete.',
            'Ghosts do not intimidate.',
            'He was always nothing.',
            'The sun will still blind him.',
            'He carries his darkness everywhere.',
        ),
        'damaged': (
            'A phantom already thin. Now thinner.',
            'The shadow bleeds.',
            'He is being ripped apart again.',
            'The void wants its investment back.',
            'His borrowed existence -- quietly rescinded.',
            'He died once already.',
            'The sequel disappoints.',
            'A memory breaking apart. Quietly symmetrical.',
        ),
        'utility': (
            'His blindness is a loan.',
            'A hollow man, sharing his condition.',
            'Vestigial habits of a former soldier.',
            'He teleports through what he is.',
            'A door made of a wound.',
        ),
    },
    'Phoenix': {   # he/him
        'spotted': (
            'The flame announces him.',
            'Flesh dressed in fire, still flesh.',
            'He mistakes a spotlight for armour.',
            'Even his entrance is a performance.',
            'London sent its finest, apparently.',
        ),
        'ult': (
            'His resurrection is a rounding error.',
            'He returns -- the math remains unchanged.',
            'He marks where he falls.',
            'Rebirth does not revise the verdict.',
            'A second life, same finite flesh.',
            'He comes back. So does inevitability.',
            'His reprieve is already accounted for.',
            'Flesh that rehearses its own ending.',
            'Another attempt. Elegant, in its futility.',
            'The end.',
            'Start again.',
            'A loop that calls itself progress.',
        ),
        'damaged': (
            'His own element turns to evidence.',
            'The glow fades. The calculation continues.',
            'The flame is indifferent.',
        ),
        'utility': (
            'He drew a line of fire.',
            'His flash blinds. Mine foresee.',
            'He bends fire. It bends back.',
            'Flesh wielding fire, scratching the surface.',
            'A closed loop, going nowhere.',
            'The smoke he makes is temporary.',
        ),
    },
    'Raze': {   # she/her
        'spotted': (
            'Her carnival is already over.',
            'Painted fire -- still mortal flesh.',
            'She mistakes chaos for evolution.',
            'Her math is all feeling.',
            'All noise and explosives.',
            'Joy is not armor.',
            'She builds beautiful, disposable things.',
            'She has never looked within.',
            'Chaos without design is prayer.',
            'The strings run through every joy.',
            'Bright. Finite. Already solved.',
            'Her every blast is a question.',
            'Bright chaos. The oldest pattern.',
        ),
        'ult': (
            'One rocket. Crude geometry.',
            'Showstopper. One rocket. I have legions.',
            'Loud, slow, and easily dodged.',
            'One loud rocket. Then nothing.',
            'Explosions are not inevitability.',
            'Metal projectile. Flesh behind it.',
            'Even joy has velocity.',
            'Her rocket changes nothing.',
            'A beautiful, wasteful gesture.',
            'Boom. And then still hollow.',
            'Even chaos finds a fulcrum.',
            'The cull does not need fireworks.',
            "She celebrates a rocket's arc.",
        ),
        'damaged': (
            'The paint fades first.',
            'Even chaos obeys biology.',
            'Life decides. Not the blast.',
            "Her joy doesn't stop bleeding.",
            'Even her Boom Bot mourns.',
            'Her fuse is nearly spent.',
            'The carnival was always borrowed.',
            'The Blast Pack cannot save her.',
            'Even joy must come to terms.',
            'The paint cannot seal the wound.',
            'Life edited her enthusiasm.',
            'Her sub-munitions will not fire.',
            'Hollow, beneath the color.',
        ),
        'utility': (
            'Her bot chases ghosts.',
            "Paint shells. A decorator's war.",
            'She dresses her grenades.',
            'A blast pack. Vestigial instinct.',
            'Enthusiasm is not a tactic.',
            'She decorates her own extinction.',
            'Color cannot conceal trajectory.',
            'The bot finds the hollow men.',
            'A grenade shaped like a party.',
            'The bot obeys. She merely hopes.',
            'She arms the beautiful, mortal thing.',
            'Her sub-munitions scatter wildly.',
            'The bot is her best argument.',
        ),
    },
    'Reyna': {   # she/her
        'spotted': (
            'She feeds to persist.',
            'Even the hungry have strings.',
            'She scavenges what I discard.',
            'The math finds her wanting.',
            'The hollow hunt the dying.',
        ),
        'ult': (
            'The hungry reign is brief.',
            'The throne requires constant tribute.',
            'Power that expires is servitude.',
            'Acceleration toward the same end.',
            'Evolution requires no frenzy.',
            'Empress. Rage mistaken for power.',
            'She feeds on kills. Deny her.',
            'A crowned scavenger, nothing more.',
            'Hunger, amplified. Not transcendence.',
        ),
        'damaged': (
            'Grief made her brave. And mortal.',
            'The hungry tire first.',
            'No soul to harvest now.',
            'Her empress cannot heal that.',
            'The orbs will not save her.',
            'She dismisses nothing this time.',
        ),
        'utility': (
            'She extrudes borrowed sight.',
            'A floating eye. Crude design.',
            'The intangible is still temporary.',
            'Appetite, not evolution.',
            'That eye reveals nothing new.',
        ),
    },
    'Sage': {   # she/her
        'spotted': (
            'She tends the garden. Gardens end.',
            'A shepherd for the obsolete.',
            'Her serenity is a borrowed thing.',
            'Even the faithful fall.',
            'Such care for the already-condemned.',
            'Her purpose is beautiful. Futile.',
            'She mistakes mercy for power.',
            'Flesh she tends. Flesh that breaks.',
            'She guards the vine before frost.',
            'Her conviction is almost elegant.',
            'She heals what I intend to break.',
        ),
        'ult': (
            'She un-does what life decided.',
            'Even mercy has arithmetic.',
            'Resurrection. The word is dramatic.',
            'She borrows. The debt collects.',
            'The math remains. She is stalling.',
            'Life always decides. She will learn.',
            'Her god is small.',
            'She rewrites what was already finished.',
            'Resurrection. One death, postponed.',
            'Beautiful gesture. Solved, already.',
            'She raises the dead. Briefly.',
            'The board resets regardless.',
            'One life returned. It changes little.',
        ),
        'damaged': (
            'Her serenity has a limit.',
            'The healer bleeds first.',
            'Even her faith is not armour.',
            'The physician, examined.',
            'The healer, unhealed.',
            'Her orbs were not sufficient.',
            'She protects others. Who protects her?',
            'Composure under pressure. Almost.',
            'She mends others. She is mending.',
        ),
        'utility': (
            'A wall of stone. Crude.',
            'She paves the way with cold.',
            'Her frost slows the world.',
            'The orb is an honest gesture.',
            'She erects barriers against the inevitable.',
            'She heals the condemned.',
            'A gift of time. Not much.',
            'The mender, mending. Admirable. Pointless.',
            'She fortifies the temporary.',
            'Geometry. She has instinct for it.',
        ),
    },
    'Skye': {   # she/her
        'spotted': (
            'Her beasts feel nothing for her.',
            'A reclaimer of what, exactly.',
            'She heals what I erase.',
            'Her light guides them nowhere.',
            "Australia's last great animal.",
            'She mends a team already lost.',
        ),
        'ult': (
            'Her hounds already know.',
            'Trackers for the already found.',
            'The prey was never hidden.',
            'Three seekers for one rounding error.',
            'They hunt the blind anyway.',
            'Her beasts seek what I see.',
            'Nearsight. Already my world.',
            'Flesh tracking flesh. Vestigial.',
            'Even her seeking serves the cull.',
            'The Seekers confirm what I calculated.',
        ),
        'damaged': (
            'The healer cannot heal herself.',
            'Her Radiance fails her first.',
            'Even the earth abandons her.',
            'The reclaimer, spent.',
            'Her light dims on schedule.',
            'The trinket breaks before the maker.',
            'The beast outlasts the woman.',
            'No one mends her.',
        ),
        'utility': (
            'Her hawk flashes in the dark.',
            'She heals what cannot be kept.',
            'The hunter walks my invitation.',
            'She mends the doomed. Admirable.',
            'Her hawk navigates a solved map.',
            'Concussive. The weakest word for it.',
            'Her wolf walked my path.',
            'Healing the hollow. A mercy.',
            'She flings beauty, accomplishes nothing.',
            'Every trinket she wastes, calculated.',
            'The flash blinds. Not me.',
            "Even nature's instruments serve me.",
        ),
    },
    'Sova': {   # he/him
        'spotted': (
            'His eye already reveals nothing.',
            'Flesh traded for a lens.',
            'His arrow is already foreseen.',
            "The owl drone, a puppet's eye.",
            'String and wood. How quaint.',
            'He hunts. The math disagrees.',
            'Rebuilt from ruin, still losing.',
            'His legend holds one omission.',
            'The bow predates salvation.',
            'Precision is a hollow comfort.',
            'He found what I already knew.',
            'Radianite, wasted on wood.',
            'Elegant delusion, that borrowed eye.',
            'He maps the inevitable.',
        ),
        'ult': (
            'Three bolts. Already accounted for.',
            'Fury, from a man so measured.',
            'Walls yield. He remains finite.',
            'His fury is borrowed energy.',
            "Hunter's Fury. Three lines, all mapped.",
            'He fires at the inevitable.',
            'The arrow, three times, still wood.',
            'Evolution does not fear the bolt.',
            'The geometry of it is graceless.',
            'Precision extended into extinction.',
            'He screams through stone. Still lost.',
            'Three lines. The math is clear.',
            'His arrows find walls.',
            'I find everything.',
            'The legend fires. Still mortal.',
        ),
        'damaged': (
            'Even legends bleed.',
            'His aim was always approximate.',
            'The eye sees. The body falters.',
            'Even flawless archers bleed.',
            'A hollow hunter, losing his shape.',
            'The string grows slack.',
            'The hunter, hunted.',
            'The scout, unseen at last.',
            'Even radianite cannot mend this.',
            'He finds what he was hunting.',
            'The owl descends.',
            'Imperfect, finally, and undeniably.',
            "He's missed the only one.",
        ),
        'utility': (
            'A puppet eye, hunting nothing.',
            'His arrow asks. Already answered.',
            'Revelation is graceless, with a bow.',
            'He illuminates what needs no light.',
            'I find him. He finds shadows.',
            'Radianite mapped. The arrow, redundant.',
            'The owl circles an empty sky.',
            'He telegraphs his fear beautifully.',
            'The scout reveals what I foresee.',
            'His recon sees less than mine.',
            'A curious machine, playing hunter.',
            'The bolt is a hollow question.',
            "He maps me. I'm already gone.",
            'Strings tether even his arrows.',
        ),
    },
    'Tejo': {   # he/him
        'spotted': (
            'Experience is just a longer obituary.',
            'Flesh confident in its ordinance.',
            'Authority, unearned in the final calculation.',
            'Old lessons, insufficient tuition.',
            'A soldier who outlived his era.',
        ),
        'ult': (
            'He names it Armageddon. How generous.',
            'A missile barrage. Loud and slow.',
            'The sky is mine to claim.',
        ),
        'damaged': (
            'His experience offered no armour.',
            'Even calibrated flesh bleeds.',
            'The consultant miscalculated one variable.',
            'His quiet authority has gone quiet.',
            'He accounted for everything but deterioration.',
            'The targeting system cannot target this.',
            'Ordnance expertise, imperfect biology.',
            'His composure is admirable. Briefly.',
        ),
        'utility': (
            'Guided salvo; guided by whose foresight?',
            'His suppression suppresses nothing of consequence.',
            'Two missiles, two choices, neither sufficient.',
            'He marks targets. I have already moved.',
            'His missiles arrive where I was.',
        ),
    },
    'Veto': {   # he/him
        'spotted': (
            'Mutation or not, he is meat.',
            'His biology announces him.',
            'His mutation is vestigial.',
            'Evolution passed him.',
            'Flesh, with delusions of architecture.',
            'He crosses. The variable is noted.',
        ),
        'ult': (
            'He calls it Evolution.',
            'He is still flesh.',
            'Mutation is not ascension.',
            'He regenerates. A candle relighting itself.',
            'His stim is borrowed.',
            'He thinks himself remade.',
            'The biology flatters him.',
            'Flesh imitating what metal already is.',
            'Evolution, he says.',
            'His immunity is temporary.',
            'A brief, beautiful, inconsequential thing.',
            'And still he is only meat.',
            'Immunity to their tools.',
            'The same fragile architecture inside.',
        ),
        'damaged': (
            'The mutation did not protect him.',
            'He bleeds. Biology is not armour.',
            'The regeneration has limits.',
            'Even remade things break.',
            'His own ability, turned inward.',
            'His Chokehold cannot hold this.',
            'His biology protests.',
            'The mutation weakens.',
        ),
        'utility': (
            'Flesh nullifying metal.',
            'A man-shaped immune response.',
            'He throws his mutation at them.',
            'His flesh destroys utility.',
            'His biology spread across the ground.',
            'His Crosscut repositions nothing of consequence.',
            'The Chokehold deafens them.',
            'A sentinel, guarding against the tide.',
            'His mutation reaches out.',
        ),
    },
    'Viper': {   # she/her
        'spotted': (
            'Chemistry. How charmingly finite.',
            'A monster, she says. How aspirational.',
            'She burns herself to burn others.',
            'Flesh corroding flesh. Inevitable.',
            'Her fog hides her from herself.',
            'She named herself a viper.',
            'I find that sad.',
            'Crude science, prettily applied.',
            'The acid reaches.',
            'Metal does not notice.',
            'She mistakes corrosion for power.',
            'A chemist. The oldest weapon.',
            'She drains herself for a curtain.',
        ),
        'ult': (
            'Her Pit. A curtain, nothing more.',
            'Smoke does not blind mathematics.',
            'She hides the inevitable in fog.',
            "Viper's Pit. She hides in her own poison.",
            'Her Pit is finite.',
            'I am not.',
            'The fog lifts. The math remains.',
            'Even her ultimate corrodes herself.',
            'Judgment arrives through every atmosphere.',
            'A poison church with no congregation.',
            'She calls the fog mercy.',
            'I call it stalling.',
        ),
        'damaged': (
            'Even her blood is chemistry now.',
            'Flesh corrodes on schedule.',
            'Life decided against chemistry.',
            'Her own fumes taste the answer.',
            'A self-consuming weapon. Elegant, almost.',
            'The weak corrode. She understands this.',
            'Her formula never balanced.',
            'She drains herself.',
            'We only finish it.',
            'The corrosion was always internal.',
        ),
        'utility': (
            'She spends herself for smoke.',
            'A chemical wall. How organic.',
            'The acid bites.',
            'Her Snakebite scratches the surface.',
            'She weaponized her own deterioration.',
            'Her tools consume their maker. Familiar.',
            'A Toxic Screen. A finite gesture.',
            'Her chemistry is exquisitely self-defeating.',
        ),
    },
    'Vyse': {   # she/her
        'spotted': (
            'The obsolete guards its thorns. Expected.',
            'A Kingdom experiment. Noted and categorized.',
            'She hides behind her garden.',
            'Even liquid metal decays, eventually.',
            'The math favors patience -- briefly.',
            'The Interverse gave her metal.',
            'A radiant with borrowed armor.',
        ),
        'ult': (
            'Thorns inconvenience; extinction does not.',
            'Beautiful. But flowers fade. Even thorns.',
            'Kingdom built her a cage.',
            'Disruption is not destruction.',
            'A momentary silence before the reckoning.',
            'The math resumes afterward.',
            'Steel Garden. Thorns for the fleshbound.',
        ),
        'damaged': (
            'The alloy bleeds.',
            "Kingdom's investment is diminishing rapidly.",
            'She escaped captivity once.',
            'Inevitable, like all rounding errors.',
            "The Corporation's prototype is underperforming.",
            'Flesh remembers what metal forgets. Pain.',
            'Her cage was Hourglass.',
            'The garden is untended.',
        ),
        'utility': (
            'Her rose will bloom and fade.',
            'Thorns delay. They do not decide.',
            'She borrows my vocabulary.',
            'The inevitable simply walks around it.',
            'A Kingdom researcher, still laying snares.',
            'Mercy would be faster.',
            'The radiant thorns slow them. Briefly.',
            'Thorns do not negotiate.',
        ),
    },
    'Waylay': {   # she/her
        'spotted': (
            'Her glow precedes her. Inevitable.',
            'Flesh wrapped in physics. Still flesh.',
            'The brightest things burn fastest.',
            'I have accounted for every wavelength.',
            'Bright, brief, and easily traced.',
            'She believes speed is survival.',
            'Even light arrives too late, sometimes.',
        ),
        'ult': (
            'An afterimage of something already hollow.',
            'She sends a copy. Copies crumble.',
            'Light slows flesh. Metal is unmoved.',
            'Her beam touches everything. Changes nothing.',
            'A hinder cast on the inevitable.',
            'She projects herself.',
            'The obsolete slow the obsolete.',
            'Symmetry, squandered on a wrong side.',
            'She dims the field.',
        ),
        'damaged': (
            'Light, wounded. As expected.',
            'Physics had nothing to say.',
            'Her invulnerability has a return address.',
            'Speed did not save her.',
            'The beam flickered. So does everything.',
            'She outran everything except the math.',
            'Fragile, beneath the luminance.',
            'The glow is cosmetic.',
        ),
        'utility': (
            'She hindered them.',
            'The destination was already mine.',
            'A slow applied to the finite.',
            'Speed used twice.',
            'The third time, she walks.',
            'Refract -- invulnerable, for a moment.',
            'Her velocity is calculated. Predictable. Solved.',
            'She marks where she was.',
            "Not where she'll be.",
            'The hinder works.',
            'On things that still feel it.',
            'A beautiful mechanism. Crude application.',
            'She burns her way back.',
            'The beacon holds her.',
        ),
    },
    'Yoru': {   # he/him
        'spotted': (
            'He hides in the seams.',
            'A rift-walker who cannot walk away.',
            'Flesh dressed in borrowed dimensions.',
            'He haunts the fabric.',
            'Even his footsteps are a lie.',
            "He tears at reality's edge. Graceless.",
            'I have seen his rifts.',
            'They heal themselves.',
            'The lone wolf. How predictably alone.',
            'A scar in the world.',
            'He finds the cracks.',
            'I made them.',
            'He stalks the threshold.',
            'I own it.',
        ),
        'ult': (
            'He steps between worlds.',
            'Dimensional drift. The arithmetic is unchanged.',
            'Not to the math.',
            'He walks in the between.',
            'A ghost rehearsing its own extinction.',
            'The veil heals.',
            'Between dimensions -- still finite, still flesh.',
            'The between is not an escape.',
            'No dimension hides him from me.',
            'He thinks absence is shelter.',
            'Invisible, and still the weakest variable.',
            'He hides where nothing grows.',
        ),
        'damaged': (
            'The rift-walker bleeds like the rest.',
            'He tore the world open.',
            'He did not.',
            'The lone wolf, thinning. Expected.',
            'He walked between worlds.',
            'Not far enough.',
            'The fabric holds. He does not.',
            'He frays.',
            'As all finite things do.',
            'The riftwalker is grounded. Permanently, perhaps.',
            'He tears at existence.',
            'Existence is indifferent.',
        ),
        'utility': (
            "Fake footsteps. A scarecrow's ambition.",
            'He echoes himself. How hollow.',
            'A tethered rift, stretched thin. Breakable.',
            'His anchor is set.',
            'I have noted it.',
            'I require none.',
            'A flash born of a ricochet.',
            'The thread is laid.',
            'I see the thread.',
            'He bluffs in footsteps. Borrowed theater.',
            'He blinds with borrowed light. Insufficient.',
            'A tether to safety.',
            'How human of him.',
        ),
    },
}
