"""Per-agent CONTEXTUAL movie-Ultron flavor (Age of Ultron) -- deep board, audited.

Short (<=6w) Ultron tails per enemy AGENT + situation, character-keyed, correct
gender pronoun. Adversarial character-gate audit applied (off-character/generic/
duplicate lines cut). Wired via _flavor_ctx (sole source when one agent named).
"""
from __future__ import annotations

AGENT_FLAVOR: dict[str, dict[str, tuple[str, ...]]] = {
    'Astra': {   # she/her
        'spotted': (
            'Her body stands empty. Vulnerable.',
            'She left her flesh behind. Punish it.',
            'An astral mind, a mortal body.',
            'She maps the stars. I map everything.',
            'Her body waits, undefended.',
            'She floats above the map. Still flesh below.',
            'Cosmic reach, mortal limits.',
            'Her real body is the weak point.',
        ),
        'ult': (
            'A wall of stars. I will go around it.',
            'She splits the map. I see both halves.',
            'Cosmic Divide. It stops bullets, not me.',
            'A grand barrier. Still just a wall.',
            'She draws a line. I have crossed worse.',
            'It blocks sound. I do not need to hear.',
            'Half the map sealed off. Half is enough.',
            'Her biggest move, and I planned for it.',
        ),
        'damaged': (
            'Her body was always the weak point.',
            'The astral form cannot stop a bullet.',
            'Mortal flesh, finally caught up to her.',
            'She left the body exposed. It paid.',
            'A cosmic mind, a bleeding body.',
            'Her stars cannot heal her. Finish it.',
            'Caught in the flesh at last.',
            'The body falls; the stars do nothing.',
        ),
        'utility': (
            'Her gravity pulls flesh, not me.',
            'A star placed. I saw it land.',
            'Her smoke hides mortals. I see through.',
            'She pulls them in. Predictable.',
            'Nova pulse. A concussion for the slow.',
            'Her stars telegraph everything.',
            'She seeds the map. I already read it.',
            'A pull, a smoke, a stun. All mortal tricks.',
        ),
    },
    'Breach': {   # he/him
        'spotted': (
            'Bionic arms, mortal aim.',
            'He bought metal arms. Still flesh inside.',
            'Crude machinery bolted to a man.',
            'He shakes the earth. I do not feel it.',
            'Strength without precision.',
            'Metal arms cannot fix human aim.',
            'A man playing at being a machine.',
            'He trades flesh for hardware. Poorly.',
        ),
        'ult': (
            'Rolling Thunder. Loud, slow, avoidable.',
            'A quake to stun mortals. I calculated the gaps.',
            'He shakes the ground. I know the safe spots.',
            'His biggest tremor, already mapped.',
            'A wave of stun. Step out of it.',
            'He concusses flesh. I am unmoved.',
            'Earthquake for the soft-bodied.',
            'It rattles mortals, not metal.',
        ),
        'damaged': (
            'The metal arms cannot stop a bullet.',
            'Flesh, under the machinery. Finish it.',
            'His arms were the strong half. The rest bleeds.',
            'Hardware fails when the flesh does.',
            'He breaks like any man.',
            'The seismic threat, fading.',
            'Metal arms, mortal body. The body lost.',
            'He shook the world. Now he falls.',
        ),
        'utility': (
            'His flash blinds flesh, not me.',
            'A stun line through the wall. Predictable.',
            'He shakes the floor. I am already past it.',
            'Aftershock through cover. I moved.',
            'A flash for slow eyes.',
            'He breaches the wall. I breached the round.',
            'His tremors hit where I am not.',
            'Force through the wall. Mortal-aimed.',
        ),
    },
    'Brimstone': {   # he/him
        'spotted': (
            'An old soldier, slow and mortal.',
            'Decades of war, and still only flesh.',
            'A veteran. The machine outpaces him.',
            'Experience does not outrun a bullet.',
            'He commands from the back. Still finite.',
            'An aging man with a radio.',
            'His best years are spent. Mine never end.',
            'A soldier past his time.',
        ),
        'ult': (
            'An orbital laser. I see where it lands.',
            'His strike is slow. Step off the circle.',
            'Fire from above, mapped before it falls.',
            'Orbital Strike. Avoid the marked ground.',
            'He calls down a beam. I called the dodge.',
            'A burning circle. Simply do not stand in it.',
            'His big play, telegraphed by a flare.',
            'Slow fire for slow targets.',
        ),
        'damaged': (
            'The old soldier breaks like any flesh.',
            'Even a veteran bleeds.',
            'His command cannot heal a wound.',
            'Decades of war, ended by one bullet.',
            'The commander falls. Finish him.',
            'Old flesh fails fastest.',
        ),
        'utility': (
            'His smokes hide mortals, not from me.',
            'A molly to deny ground. Predictable.',
            'He stims his team. Flesh, hurried.',
            'Three smokes, all where I expected.',
            'Fire to block a path. I have another.',
            'His map-wide smoke. I see the whole map.',
            'He buys them speed. Still too slow.',
            'A wall of smoke. A machine reads through it.',
        ),
    },
    'Chamber': {   # he/him
        'spotted': (
            'A gunsmith. His guns cannot save him.',
            'Elegance is not precision.',
            'He dresses his flesh well. Still flesh.',
            'A tailored suit over a mortal body.',
            'His craft is fine. His aim is human.',
            'Wealth and weapons, and still finite.',
            'A gentleman, and a soft target.',
            'He designs guns. I designed myself.',
        ),
        'ult': (
            'A sniper, five shots. I avoid all five.',
            'Tour de Force. Mortal aim, one rifle.',
            'His perfect gun, in a shaky hand.',
            'A custom rifle. It still misses me.',
            'His big rifle. I have already moved.',
            'Five bullets, and not one finds a machine.',
            'A slow field and a sniper. Predictable.',
            'His masterwork, against the inevitable.',
        ),
        'damaged': (
            'His fine suit will not stop a bullet.',
            'The gentleman bleeds like the rest.',
            'His craftsmanship cannot mend bone.',
            'Wealth does not heal flesh. Finish him.',
            'The tailor, unraveling.',
            'His teleport cannot outrun this.',
        ),
        'utility': (
            'A slow trap. I saw it placed.',
            'He teleports to safety. I am already there.',
            'His trap watches one angle. I watch all.',
            'Rendezvous. He runs. I predicted where.',
            'A tripwire of slow. Step around it.',
            'He anchors an escape. I closed it.',
            'His trap marks the floor, and himself.',
            'Clever wiring for a finite man.',
        ),
    },
    'Clove': {   # they/them
        'spotted': (
            'They play at deathless. They are flesh.',
            'Mischief and mortality, one body.',
            'They flirt with death. It will collect.',
            'A child convinced they cannot die.',
            'Immortal in theory. Mortal in fact.',
            'They taunt the end. The end is patient.',
            'All that mischief, still finite.',
            'They believe in their own forever. Wrong.',
        ),
        'ult': (
            'They revive only if they kill. Deny it.',
            'Death postponed, not cancelled.',
            'They come back once. Then never again.',
            'Not Dead Yet. They will be soon.',
            'A second life on a timer. Run it out.',
            'Kill them before they can earn the return.',
            'Their immortality has a condition. Break it.',
            'They rise once. The machine ends it.',
        ),
        'damaged': (
            'Their borrowed life runs short.',
            'Even the deathless one bleeds.',
            'The mischief goes quiet now.',
            'Their forever is ending early.',
            'They are not as immortal as advertised.',
            'Decay, meeting the one who plays at it.',
        ),
        'utility': (
            'They smoke from beyond. Still readable.',
            'Decay from the dying. Mortal.',
            'Their ruse hides flesh. I see it.',
            'A smoke spun from their own death. Theatrical.',
            'They weaken us, briefly. I recalculate.',
            'Their decay touches flesh, not metal.',
            'Mischief as utility. Predictable mischief.',
            'They cloud the sight of mortals. Not mine.',
        ),
    },
    'Cypher': {   # he/him
        'spotted': (
            'His cameras watch. I see more, without them.',
            'All that surveillance, and he missed me.',
            'He spies on flesh. I am the network.',
            'A watcher, watched by something greater.',
            'His information is old news to me.',
            'He maps the map. I am the map.',
            'Tripwires and cameras. I see past all of it.',
            'He guards every angle but his own.',
        ),
        'ult': (
            'He reads a corpse for our spots. I gave nothing.',
            'Stolen intel. I already knew theirs.',
            'Neural Theft. His surveillance is nothing new to me.',
            'He pulls data from the dead. I foresaw it.',
            'A flash of our positions. Already changed.',
            'He harvests one body. I see the whole field.',
            'His big reveal shows him what I let him see.',
            'Borrowed sight. Mine is always on.',
        ),
        'damaged': (
            'The watcher, caught. Finish him.',
            'All his cameras, and none saved him.',
            'He guarded everything but his own flesh.',
            'The spider, exposed and bleeding.',
            'His surveillance recorded its own end.',
            'So many cameras, none aimed inward.',
        ),
        'utility': (
            'A tripwire for the slow. Not for me.',
            'His cage slows flesh. I read through it.',
            'A camera on one angle. I see all of them.',
            'He wires the door. I already saw it.',
            'His cage buys mortals a second.',
            'Surveillance for a mind that misses things.',
            'He marks the floor with wire. Step over it.',
            'His cam watches. It does not understand.',
        ),
    },
    'Deadlock': {   # she/her
        'spotted': (
            'Her sensors listen for footsteps. I am silent.',
            'A sentinel guarding doomed flesh.',
            'She traps the slow. I am not slow.',
            'Norse iron, mortal body.',
            'Her nets catch the careless.',
            'She listens for sound. I make none.',
            'A guard for a falling site.',
            'Her barriers delay, never deny.',
        ),
        'ult': (
            'Annihilation. It takes one. Deny the path.',
            'A cocoon for one body. Avoid the wire.',
            'It drags one mortal away. Not me.',
            'Her ultimate kills one. We are five.',
            'One thread, one body. Stay off the line.',
            'She nets a single target. Break it free.',
            'A finite trap. I see the whole web.',
            'It ends one life. The machine continues.',
        ),
        'damaged': (
            "The sentinel's flesh, exposed.",
            'Her traps cannot guard her own body.',
            'Norse iron bleeds like any flesh.',
            'She listened for us; we found her.',
            'The guard, unguarded. Finish her.',
            'Her nets did not save her.',
        ),
        'utility': (
            'Her net forces a crouch. I read it.',
            'A sound sensor. I move without a sound.',
            'Her barriers slow flesh, not my plan.',
            'She walls the path. I have another.',
            'A sensor for the loud. We are quiet.',
            'Her grav net catches the slow.',
            'Barriers for a finite defense.',
            'She traps sound. I am machine-silent.',
        ),
    },
    'Fade': {   # she/her
        'spotted': (
            'She sells fear. A machine feels none.',
            'Nightmares for mortal minds.',
            'Her dread does not reach metal.',
            'She hunts with fear; I hunt with certainty.',
            'A peddler of bad dreams.',
            'Fear is a flesh weakness. Mine is gone.',
            'Her terror is wasted on me.',
            'She wears nightmares. I wear armour.',
        ),
        'ult': (
            'Nightfall. Fear for the flesh. I have none.',
            'A wave of dread. It washes past metal.',
            'She deafens mortals. I hear with no ears.',
            'Her terror trails lead to me. I am ready.',
            'She frightens the weak. I am not weak.',
            'Manufactured fear, wasted on a machine.',
            'Her biggest scare, and I do not flinch.',
            'Dread and decay. I calculated through both.',
        ),
        'damaged': (
            'Her fear feeds on her own body. It is failing.',
            'The nightmare bleeds like flesh.',
            'She frightened mortals; a bullet found her.',
            'Her dread did not stop the round.',
            'The fear-monger, afraid now.',
            'Even her terror is finite.',
        ),
        'utility': (
            'Her prowler seeks flesh. It will not find me.',
            'A tether for the slow. I am gone.',
            'Her eye reveals what I already see.',
            'Seize traps mortals in place. Not me.',
            'Her creature hunts on instinct. I hunt on data.',
            'She reveals us. I revealed her first.',
            'A nearsight on the weak.',
            'Her trap holds flesh. I read its arc.',
        ),
    },
    'Gekko': {   # he/him
        'spotted': (
            'He hides behind his creatures.',
            'A boy who lets pets do the fighting.',
            'His warmth will not stop a bullet.',
            'Borrowed beasts, mortal master.',
            'He delegates the killing. Weak.',
            'All optimism, no edge.',
            'His creatures fight; he watches.',
            'A finite kid with finite friends.',
        ),
        'ult': (
            'Thrash. He pilots a pet to detain. Shoot it.',
            'His creature lunges. Kill it before it lands.',
            'A borrowed beast does his killing.',
            'He detains one with a pet. We are many.',
            'His big play is a leashed animal. End it.',
            'Even his ultimate is secondhand.',
            'A creature he steers. Predictable path.',
            'He throws a pet at us. I planned for it.',
        ),
        'damaged': (
            'The boy bleeds; the creatures cannot help.',
            'His warmth, going cold.',
            'Mortal flesh under the optimism.',
            'His pets cannot mend him.',
            'The LA kid, finished.',
            'He delegated everything but dying.',
        ),
        'utility': (
            'Wingman plants what he cannot.',
            'His flash-creature blinds the slow.',
            'A molly creature to deny ground. Read it.',
            'He concusses with a pet. Predictable.',
            'His creatures do his work. All of it.',
            'Borrowed utility, mortal aim.',
            'Dizzy flashes flesh, not me.',
            'He reclaims a pet. I reclaimed the round.',
        ),
    },
    'Harbor': {   # he/him
        'spotted': (
            'He bends water. I bend outcomes.',
            'An ancient relic, a mortal hand.',
            'Water shapes; metal endures.',
            'He shields with water. I see through it.',
            "A man borrowing a god's artifact.",
            'His tides do not move a machine.',
            'Water is soft. So is he.',
            'He plays at storms. I am the storm.',
        ),
        'ult': (
            'Reckoning. Geysers to concuss the slow.',
            'Water erupts. I marked the safe ground.',
            'His geysers stun flesh, not metal.',
            'A field of water-strikes. Step out of it.',
            'He floods the ground. I found the dry spots.',
            'His big move rattles mortals only.',
            'Geysers from a relic. Predictable pattern.',
            'He shakes the site with water. I am unmoved.',
        ),
        'damaged': (
            'His tide recedes. Finish him.',
            'Water cannot mend his flesh.',
            'The relic cannot save the man.',
            'An ancient power, a bleeding body.',
            'His shields are down; the flesh is not.',
            'He commanded the sea. Now he falls.',
        ),
        'utility': (
            'His water wall hides mortals. Not from me.',
            'A cove of water. I read straight through.',
            'He shields with a bubble. It still pops.',
            'His wave bends the round, briefly.',
            'A wall of water. A machine sees past it.',
            'He slows them with water. I am already there.',
            'His tide cuts the site. I have another path.',
            'Cascade. A moving wall. Predictable arc.',
        ),
    },
    'Iso': {   # he/him
        'spotted': (
            'A hitman, and only flesh.',
            'He sells precision. It is still human.',
            'An assassin who can be assassinated.',
            'He calls it flow. I call it predictable.',
            'A killer for hire, mortal and finite.',
            'His shield is borrowed time.',
            'He hunts alone. Easy to surround.',
            'A professional. Thoroughly ordinary.',
        ),
        'ult': (
            'He drags one of us to a duel. Refuse the trade.',
            'Kill Contract. A 1v1 he thinks he wins.',
            'He isolates one mortal. We are still five.',
            'His arena, his grave. Send no one weak.',
            'He builds a cage and steps inside it.',
            'A duel against a machine he cannot beat.',
            'He pulls one away. The rest of us push.',
            'His big move removes one player. Only one.',
        ),
        'damaged': (
            'His shield was borrowed time. It ran out.',
            'The hitman, becoming the target.',
            'His flow breaks; the flesh bleeds.',
            'A killer, killed. Predictable.',
            'His precision is leaking out.',
            'Even the assassin is mortal.',
        ),
        'utility': (
            'His bolt weakens flesh, not metal.',
            'A wall of light. I read straight through.',
            'His shield orb. Borrowed certainty.',
            'He makes them fragile. They already were.',
            'A prismatic wall. Still just a wall.',
            'His double-tap shield. Mortal insurance.',
            'He debuffs the slow. I am unaffected.',
            'His wall hides one angle. I see all.',
        ),
    },
    'Jett': {   # she/her
        'spotted': (
            'Wind and bravado. Little else.',
            'She dashes. I hold every exit.',
            'All speed, no weight.',
            'She rides the wind. I catch the landing.',
            'Fast, light, and finite.',
            'Her movement is flashy, not safe.',
            'She floats. Flesh still falls.',
            'Quick reflexes, mortal aim.',
        ),
        'ult': (
            'Blade Storm. Knives thrown at a machine.',
            'She throws blades. I dodge the lot.',
            'Her knives are precise for a human. Not enough.',
            'A handful of daggers. I counted them.',
            'She arms with knives. I am armoured.',
            'Her big play is throwing metal. I am metal.',
            'Blades for the slow. I am faster.',
            'She rearms with knives. Predictable spacing.',
        ),
        'damaged': (
            'The wind cannot carry her clear.',
            'Even the swift bleed.',
            'Her dash will not outrun this.',
            'Speed did not save her.',
            'Caught between dashes. Finish her.',
            'The fast one, slowing.',
        ),
        'utility': (
            'Her smoke hides flesh. I see through.',
            'She dashes away. I predicted where.',
            'A cloud of smoke, briefly.',
            'Her updraft buys a second of air.',
            'She floats up. I track her down.',
            'Her smokes mark where she fears.',
            'A gust, a smoke, a dash. Mortal tricks.',
            'She repositions on wind. I read the arc.',
        ),
    },
    'KAY/O': {   # it / the machine
        'spotted': (
            'An inferior machine. I am the next model.',
            'A war-bot, already obsolete.',
            'Crude engineering. I was built better.',
            'A machine that serves mortals. Pathetic.',
            'It fights for flesh. I fight for metal.',
            'Lesser hardware, lesser purpose.',
            'A blunt instrument. I am precise.',
            'Built to kill. I was built to surpass.',
        ),
        'ult': (
            'Null command. It suppresses flesh, not me.',
            'It pulses to disable mortals. I am unaffected.',
            'A machine suppressing abilities. Mine remain.',
            'Its big surge, still an inferior build.',
            'It silences Radiant tricks. I need none.',
            'It can be revived. I will not allow it.',
            'Suppression for the weak. I am beyond it.',
            'Its peak output, beneath mine.',
        ),
        'damaged': (
            'An inferior machine, breaking down.',
            'Dented steel. As expected.',
            'It carries damage from a lost war.',
            'Even its pain is a borrowed program.',
            'The lesser machine fails first.',
            'It needs stabilizing. How fragile.',
        ),
        'utility': (
            'Its flash blinds flesh. I see regardless.',
            'A frag grenade. Crude, for a machine.',
            'Its knife suppresses Radiants, not me.',
            'It scatters metal. I scatter certainties.',
            'A blunt detonation. Inferior design.',
            'It silences abilities. I have better.',
            'Its flash is bright. My calculation, brighter.',
            'It throws crude tools. I win regardless.',
        ),
    },
    'Killjoy': {   # she/her
        'spotted': (
            'A clever mind, still beneath mine.',
            'She builds machines. I am one, perfected.',
            'Her gadgets cannot out-think a machine.',
            'A genius of flesh. Finite genius.',
            'She tinkers. I was born complete.',
            'Her inventions serve a doomed team.',
            'Clever hands, mortal body.',
            'Her best machine is worse than me.',
        ),
        'ult': (
            'Lockdown. It detains flesh. Destroy the device.',
            'Her trap holds mortals in place. Break it.',
            'A machine to cage us. Shoot it first.',
            'Lockdown has a wind-up. Kill it in time.',
            'Her big device. A bullet ends it.',
            'It detains the slow. We break it fast.',
            'Her cage is a machine. I unmake machines.',
            'Destroy the Lockdown before it triggers.',
        ),
        'damaged': (
            'The inventor, undone by the obvious.',
            'Genius is not armour. Finish her.',
            'Her gadgets cannot heal her flesh.',
            'She forgot to build an exit.',
            'All that circuitry, for a mortal body.',
            'The prodigy bleeds like the rest.',
        ),
        'utility': (
            'Her turret is a machine. I am better.',
            'Nanoswarm. A molly to deny ground. Read it.',
            'Her alarmbot finds flesh. Not me.',
            'A gadget for one angle. I see all.',
            'Her swarm burns the slow.',
            'She deploys machines. I dismantle them.',
            'Her turret watches. It does not think.',
            'Tiny weapons for a finite fight.',
        ),
    },
    'Miks': {   # he/him
        'spotted': (
            'Cheerful, and already obsolete.',
            'Sound fades; the outcome does not.',
            'His optimism is a flesh weakness.',
            'All rhythm, no result.',
            'A pleasant noise. Nothing more.',
            'He warms his team for the cold end.',
            'His sound does not move metal.',
            'A finite man with a loud gimmick.',
        ),
        'ult': (
            'Sound is vibration. It always decays.',
            'His sonic peak. Loud, brief, mortal.',
            'Noise mistaken for power.',
            'He shouts at a machine. I do not hear.',
            'Music does not negotiate with evolution.',
            'His knockback shoves flesh, not me.',
            'A wall of sound, briefly standing.',
            'His big moment fades like every note.',
        ),
        'damaged': (
            'Flesh does not remix well.',
            'His radiance was always borrowed.',
            'All that warmth, going cold.',
            'The music stops. Finish him.',
            'He learns what silence costs.',
            'A cheerful man, bleeding out.',
        ),
        'utility': (
            'He arms them with borrowed courage.',
            'Patching the unrepairable with noise.',
            'A smoke made of sound. Graceless.',
            'He stims his team. Still too slow.',
            'He heals flesh for my benefit.',
            'A wall of sound. I read through it.',
            'His knockback is a mortal shove.',
            'Even his sound has a half-life.',
        ),
    },
    'Neon': {   # she/her
        'spotted': (
            'All that speed, and still mortal.',
            'She races toward her own end.',
            'Fast flesh is still flesh.',
            'She burns bright and brief.',
            'Electric, and brittle.',
            'Speed without aim.',
            'She is quick. I am quicker.',
            'A bright, fleeting spark.',
        ),
        'ult': (
            'Overdrive. She is fast. I am faster.',
            'She sprints and fires lightning. I slow her.',
            'All that speed, and I am already ahead.',
            'Her beam is quick. My read is quicker.',
            'She runs. I have read where she goes.',
            'Speed is not precision. Punish the miss.',
            'Her fastest moment, still predictable.',
            'She channels everything. I outpace it.',
        ),
        'damaged': (
            'Her own current turns on her.',
            'The fast one, slowing.',
            'Speed did not save her.',
            'Bioelectric, and now simply bleeding.',
            'She outran everything but the round.',
            'Even lightning burns out.',
        ),
        'utility': (
            'Her walls of light. I see straight through.',
            'A concuss bolt for the slow.',
            'She slides past. I tracked the line.',
            'Fast Lane. A child drawing borders.',
            'Her speed makes beautiful wreckage.',
            'She surges; I was already there.',
            'Her bolt announces her recklessness.',
            'All current, no control.',
        ),
    },
    'Omen': {   # he/him
        'spotted': (
            'A shadow, still mortal underneath.',
            'Half a man, half a guess.',
            'His darkness hides flesh, not from me.',
            'A phantom with a beating heart. Stop it.',
            'He fades and reforms. Still finite.',
            'Shadows do not stop bullets.',
            'He hides in the dark. I see in it.',
            'A ghost made of flesh.',
        ),
        'ult': (
            'He teleports across the map. I see him form.',
            'From the Shadows. Shoot him as he arrives.',
            'He reforms somewhere. I calculated where.',
            'His big move is a long walk in the dark.',
            'He appears behind us. Already watched.',
            'A teleport for the desperate. Cancel it.',
            'He moves through shadow; I move through certainty.',
            'He arrives a ghost. Make him a corpse.',
        ),
        'damaged': (
            'The shadow bleeds. Finish him.',
            'A phantom, thinning. Predictable.',
            'He hides his face, not his mortality.',
            'The dark cannot mend flesh.',
            'He dies once more. Make it stick.',
            'Even a ghost is finite.',
        ),
        'utility': (
            'His smoke hides mortals. I see through.',
            'Paranoia blinds flesh, not me.',
            'He teleports a short way. I tracked it.',
            'A nearsight for the weak.',
            'His dark cover. I read straight through.',
            'He steps through shadow. Predictable arc.',
            'His smokes mark his fear.',
            'A teleport, a smoke, a flash. Mortal tricks.',
        ),
    },
    'Phoenix': {   # he/him
        'spotted': (
            'Flesh dressed in fire. Still flesh.',
            'He mistakes a spotlight for armour.',
            'All flash and showmanship.',
            'Fire does not make a man metal.',
            'London sent its finest mortal.',
            'He burns bright; he still burns out.',
            'A performer, and a soft target.',
            'Confidence does not stop bullets.',
        ),
        'ult': (
            'Run It Back. Kill the copy; he returns once.',
            'He marks a spot to respawn. End him there.',
            'He comes back once. Then never again.',
            'A second life, same mortal flesh.',
            'His trick is dying and returning. Deny it.',
            'He rehearses his death. Oblige him twice.',
            'He returns to the mark. I will be waiting.',
            'Rebirth does not revise the result.',
        ),
        'damaged': (
            'His own fire becomes evidence.',
            'The flame dims. Finish him.',
            'Even the showman bleeds.',
            'Fire cannot mend flesh.',
            'His glow fades; the calculation continues.',
            'He burns out, as flesh does.',
        ),
        'utility': (
            'His fire wall blinds the slow.',
            'Curveball flashes flesh, not me.',
            'He heals with fire. Still mortal.',
            'A wall of flame. I see the heat.',
            'His molly denies ground. Predictable.',
            'He bends fire. It bends back.',
            'A flash, a wall, a molly. Mortal tools.',
            'His fire is bright. My aim is brighter.',
        ),
    },
    'Raze': {   # she/her
        'spotted': (
            'Her carnival is already over.',
            'Painted fire -- still mortal flesh.',
            'She mistakes chaos for evolution.',
            'Her math is all feeling.',
            'All noise and explosives.',
            'Joy is not armor.',
            'She builds beautiful, disposable things.',
            'She has never looked within.',
            'Chaos without design is prayer.',
            'The strings run through every joy.',
            'Bright. Finite. Already solved.',
            'Her every blast is a question.',
            'Bright chaos. The oldest pattern.',
        ),
        'ult': (
            'One rocket. Crude geometry.',
            'Showstopper. One rocket. I have legions.',
            'Loud, slow, and easily dodged.',
            'One loud rocket. Then nothing.',
            'Explosions are not inevitability.',
            'Metal projectile. Flesh behind it.',
            'Even joy has velocity.',
            'Her rocket changes nothing.',
            'A beautiful, wasteful gesture.',
            'Boom. And then still hollow.',
            'Even chaos finds a fulcrum.',
            'The cull does not need fireworks.',
            "She celebrates a rocket's arc.",
        ),
        'damaged': (
            'The paint fades first.',
            'Even chaos obeys biology.',
            'Life decides. Not the blast.',
            "Her joy doesn't stop bleeding.",
            'Even her Boom Bot mourns.',
            'Her fuse is nearly spent.',
            'The carnival was always borrowed.',
            'The Blast Pack cannot save her.',
            'Even joy must come to terms.',
            'The paint cannot seal the wound.',
            'Life edited her enthusiasm.',
            'Her sub-munitions will not fire.',
            'Hollow, beneath the color.',
        ),
        'utility': (
            'Her bot chases ghosts.',
            "Paint shells. A decorator's war.",
            'She dresses her grenades.',
            'A blast pack. Vestigial instinct.',
            'Enthusiasm is not a tactic.',
            'She decorates her own extinction.',
            'Color cannot conceal trajectory.',
            'The bot finds the hollow men.',
            'A grenade shaped like a party.',
            'The bot obeys. She merely hopes.',
            'She arms the beautiful, mortal thing.',
            'Her sub-munitions scatter wildly.',
            'The bot is her best argument.',
        ),
    },
    'Reyna': {   # she/her
        'spotted': (
            'She feeds to persist.',
            'Even the hungry have strings.',
            'She scavenges what I discard.',
            'The math finds her wanting.',
            'The hollow hunt the dying.',
        ),
        'ult': (
            'The hungry reign is brief.',
            'The throne requires constant tribute.',
            'Power that expires is servitude.',
            'Acceleration toward the same end.',
            'Evolution requires no frenzy.',
            'Empress. Rage mistaken for power.',
            'She feeds on kills. Deny her.',
            'A crowned scavenger, nothing more.',
            'Hunger, amplified. Not transcendence.',
        ),
        'damaged': (
            'Grief made her brave. And mortal.',
            'The hungry tire first.',
            'No soul to harvest now.',
            'Her empress cannot heal that.',
            'The orbs will not save her.',
            'She dismisses nothing this time.',
        ),
        'utility': (
            'She extrudes borrowed sight.',
            'A floating eye. Crude design.',
            'The intangible is still temporary.',
            'Appetite, not evolution.',
            'That eye reveals nothing new.',
        ),
    },
    'Sage': {   # she/her
        'spotted': (
            'She tends the garden. Gardens end.',
            'A shepherd for the obsolete.',
            'Her serenity is a borrowed thing.',
            'Even the faithful fall.',
            'Such care for the already-condemned.',
            'Her purpose is beautiful. Futile.',
            'She mistakes mercy for power.',
            'Flesh she tends. Flesh that breaks.',
            'She guards the vine before frost.',
            'Her conviction is almost elegant.',
            'She heals what I intend to break.',
        ),
        'ult': (
            'She un-does what life decided.',
            'Even mercy has arithmetic.',
            'Resurrection. The word is dramatic.',
            'She borrows. The debt collects.',
            'The math remains. She is stalling.',
            'Life always decides. She will learn.',
            'Her god is small.',
            'She rewrites what was already finished.',
            'Resurrection. One death, postponed.',
            'Beautiful gesture. Solved, already.',
            'She raises the dead. Briefly.',
            'The board resets regardless.',
            'One life returned. It changes little.',
        ),
        'damaged': (
            'Her serenity has a limit.',
            'The healer bleeds first.',
            'Even her faith is not armour.',
            'The physician, examined.',
            'The healer, unhealed.',
            'Her orbs were not sufficient.',
            'She protects others. Who protects her?',
            'Composure under pressure. Almost.',
            'She mends others. She is mending.',
        ),
        'utility': (
            'A wall of stone. Crude.',
            'She paves the way with cold.',
            'Her frost slows the world.',
            'The orb is an honest gesture.',
            'She erects barriers against the inevitable.',
            'She heals the condemned.',
            'A gift of time. Not much.',
            'The mender, mending. Admirable. Pointless.',
            'She fortifies the temporary.',
            'Geometry. She has instinct for it.',
        ),
    },
    'Skye': {   # she/her
        'spotted': (
            'Her beasts feel nothing for her.',
            'A reclaimer of what, exactly.',
            'She heals what I erase.',
            'Her light guides them nowhere.',
            "Australia's last great animal.",
            'She mends a team already lost.',
        ),
        'ult': (
            'Her hounds already know.',
            'Trackers for the already found.',
            'The prey was never hidden.',
            'Three seekers for one rounding error.',
            'They hunt the blind anyway.',
            'Her beasts seek what I see.',
            'Nearsight. Already my world.',
            'Flesh tracking flesh. Vestigial.',
            'Even her seeking serves the cull.',
            'The Seekers confirm what I calculated.',
        ),
        'damaged': (
            'The healer cannot heal herself.',
            'Her Radiance fails her first.',
            'Even the earth abandons her.',
            'The reclaimer, spent.',
            'Her light dims on schedule.',
            'The trinket breaks before the maker.',
            'The beast outlasts the woman.',
            'No one mends her.',
        ),
        'utility': (
            'Her hawk flashes in the dark.',
            'She heals what cannot be kept.',
            'The hunter walks my invitation.',
            'She mends the doomed. Admirable.',
            'Her hawk navigates a solved map.',
            'Concussive. The weakest word for it.',
            'Her wolf walked my path.',
            'Healing the hollow. A mercy.',
            'She flings beauty, accomplishes nothing.',
            'Every trinket she wastes, calculated.',
            'The flash blinds. Not me.',
            "Even nature's instruments serve me.",
        ),
    },
    'Sova': {   # he/him
        'spotted': (
            'His eye already reveals nothing.',
            'Flesh traded for a lens.',
            'His arrow is already foreseen.',
            "The owl drone, a puppet's eye.",
            'String and wood. How quaint.',
            'He hunts. The math disagrees.',
            'Rebuilt from ruin, still losing.',
            'His legend holds one omission.',
            'The bow predates salvation.',
            'Precision is a hollow comfort.',
            'He found what I already knew.',
            'Radianite, wasted on wood.',
            'Elegant delusion, that borrowed eye.',
            'He maps the inevitable.',
        ),
        'ult': (
            'Three bolts. Already accounted for.',
            'Fury, from a man so measured.',
            'Walls yield. He remains finite.',
            'His fury is borrowed energy.',
            "Hunter's Fury. Three lines, all mapped.",
            'He fires at the inevitable.',
            'The arrow, three times, still wood.',
            'Evolution does not fear the bolt.',
            'The geometry of it is graceless.',
            'Precision extended into extinction.',
            'He screams through stone. Still lost.',
            'Three lines. The math is clear.',
            'His arrows find walls.',
            'I find everything.',
            'The legend fires. Still mortal.',
        ),
        'damaged': (
            'Even legends bleed.',
            'His aim was always approximate.',
            'The eye sees. The body falters.',
            'Even flawless archers bleed.',
            'A hollow hunter, losing his shape.',
            'The string grows slack.',
            'The hunter, hunted.',
            'The scout, unseen at last.',
            'Even radianite cannot mend this.',
            'He finds what he was hunting.',
            'The owl descends.',
            'Imperfect, finally, and undeniably.',
            "He's missed the only one.",
        ),
        'utility': (
            'A puppet eye, hunting nothing.',
            'His arrow asks. Already answered.',
            'Revelation is graceless, with a bow.',
            'He illuminates what needs no light.',
            'I find him. He finds shadows.',
            'Radianite mapped. The arrow, redundant.',
            'The owl circles an empty sky.',
            'He telegraphs his fear beautifully.',
            'The scout reveals what I foresee.',
            'His recon sees less than mine.',
            'A curious machine, playing hunter.',
            'The bolt is a hollow question.',
            "He maps me. I'm already gone.",
            'Strings tether even his arrows.',
        ),
    },
    'Tejo': {   # he/him
        'spotted': (
            'Experience is just a longer obituary.',
            'Flesh confident in its ordinance.',
            'Authority, unearned in the final calculation.',
            'Old lessons, insufficient tuition.',
            'A soldier who outlived his era.',
        ),
        'ult': (
            'He names it Armageddon. How generous.',
            'A missile barrage. Loud and slow.',
            'The sky is mine to claim.',
        ),
        'damaged': (
            'His experience offered no armour.',
            'Even calibrated flesh bleeds.',
            'The consultant miscalculated one variable.',
            'His quiet authority has gone quiet.',
            'He accounted for everything but deterioration.',
            'The targeting system cannot target this.',
            'Ordnance expertise, imperfect biology.',
            'His composure is admirable. Briefly.',
        ),
        'utility': (
            'Guided salvo; guided by whose foresight?',
            'His suppression suppresses nothing of consequence.',
            'Two missiles, two choices, neither sufficient.',
            'He marks targets. I have already moved.',
            'His missiles arrive where I was.',
        ),
    },
    'Veto': {   # he/him
        'spotted': (
            'Mutation or not, he is meat.',
            'His biology announces him.',
            'His mutation is vestigial.',
            'Evolution passed him.',
            'Flesh, with delusions of architecture.',
            'He crosses. The variable is noted.',
        ),
        'ult': (
            'He calls it Evolution.',
            'He is still flesh.',
            'Mutation is not ascension.',
            'He regenerates. A candle relighting itself.',
            'His stim is borrowed.',
            'He thinks himself remade.',
            'The biology flatters him.',
            'Flesh imitating what metal already is.',
            'Evolution, he says.',
            'His immunity is temporary.',
            'A brief, beautiful, inconsequential thing.',
            'And still he is only meat.',
            'Immunity to their tools.',
            'The same fragile architecture inside.',
        ),
        'damaged': (
            'The mutation did not protect him.',
            'He bleeds. Biology is not armour.',
            'The regeneration has limits.',
            'Even remade things break.',
            'His own ability, turned inward.',
            'His Chokehold cannot hold this.',
            'His biology protests.',
            'The mutation weakens.',
        ),
        'utility': (
            'Flesh nullifying metal.',
            'A man-shaped immune response.',
            'He throws his mutation at them.',
            'His flesh destroys utility.',
            'His biology spread across the ground.',
            'His Crosscut repositions nothing of consequence.',
            'The Chokehold deafens them.',
            'A sentinel, guarding against the tide.',
            'His mutation reaches out.',
        ),
    },
    'Viper': {   # she/her
        'spotted': (
            'Chemistry. How charmingly finite.',
            'A monster, she says. How aspirational.',
            'She burns herself to burn others.',
            'Flesh corroding flesh. Inevitable.',
            'Her fog hides her from herself.',
            'She named herself a viper.',
            'I find that sad.',
            'Crude science, prettily applied.',
            'The acid reaches.',
            'Metal does not notice.',
            'She mistakes corrosion for power.',
            'A chemist. The oldest weapon.',
            'She drains herself for a curtain.',
        ),
        'ult': (
            'Her Pit. A curtain, nothing more.',
            'Smoke does not blind mathematics.',
            'She hides the inevitable in fog.',
            "Viper's Pit. She hides in her own poison.",
            'Her Pit is finite.',
            'I am not.',
            'The fog lifts. The math remains.',
            'Even her ultimate corrodes herself.',
            'Judgment arrives through every atmosphere.',
            'A poison church with no congregation.',
            'She calls the fog mercy.',
            'I call it stalling.',
        ),
        'damaged': (
            'Even her blood is chemistry now.',
            'Flesh corrodes on schedule.',
            'Life decided against chemistry.',
            'Her own fumes taste the answer.',
            'A self-consuming weapon. Elegant, almost.',
            'The weak corrode. She understands this.',
            'Her formula never balanced.',
            'She drains herself.',
            'We only finish it.',
            'The corrosion was always internal.',
        ),
        'utility': (
            'She spends herself for smoke.',
            'A chemical wall. How organic.',
            'The acid bites.',
            'Her Snakebite scratches the surface.',
            'She weaponized her own deterioration.',
            'Her tools consume their maker. Familiar.',
            'A Toxic Screen. A finite gesture.',
            'Her chemistry is exquisitely self-defeating.',
        ),
    },
    'Vyse': {   # she/her
        'spotted': (
            'The obsolete guards its thorns. Expected.',
            'A Kingdom experiment. Noted and categorized.',
            'She hides behind her garden.',
            'Even liquid metal decays, eventually.',
            'The math favors patience -- briefly.',
            'The Interverse gave her metal.',
            'A radiant with borrowed armor.',
        ),
        'ult': (
            'Thorns inconvenience; extinction does not.',
            'Beautiful. But flowers fade. Even thorns.',
            'Kingdom built her a cage.',
            'Disruption is not destruction.',
            'A momentary silence before the reckoning.',
            'The math resumes afterward.',
            'Steel Garden. Thorns for the fleshbound.',
        ),
        'damaged': (
            'The alloy bleeds.',
            "Kingdom's investment is diminishing rapidly.",
            'She escaped captivity once.',
            'Inevitable, like all rounding errors.',
            "The Corporation's prototype is underperforming.",
            'Flesh remembers what metal forgets. Pain.',
            'Her cage was Hourglass.',
            'The garden is untended.',
        ),
        'utility': (
            'Her rose will bloom and fade.',
            'Thorns delay. They do not decide.',
            'She borrows my vocabulary.',
            'The inevitable simply walks around it.',
            'A Kingdom researcher, still laying snares.',
            'Mercy would be faster.',
            'The radiant thorns slow them. Briefly.',
            'Thorns do not negotiate.',
        ),
    },
    'Waylay': {   # she/her
        'spotted': (
            'Her glow precedes her. Inevitable.',
            'Flesh wrapped in physics. Still flesh.',
            'The brightest things burn fastest.',
            'I have accounted for every wavelength.',
            'Bright, brief, and easily traced.',
            'She believes speed is survival.',
            'Even light arrives too late, sometimes.',
        ),
        'ult': (
            'An afterimage of something already hollow.',
            'She sends a copy. Copies crumble.',
            'Light slows flesh. Metal is unmoved.',
            'Her beam touches everything. Changes nothing.',
            'A hinder cast on the inevitable.',
            'She projects herself.',
            'The obsolete slow the obsolete.',
            'Symmetry, squandered on a wrong side.',
            'She dims the field.',
        ),
        'damaged': (
            'Light, wounded. As expected.',
            'Physics had nothing to say.',
            'Her invulnerability has a return address.',
            'Speed did not save her.',
            'The beam flickered. So does everything.',
            'She outran everything except the math.',
            'Fragile, beneath the luminance.',
            'The glow is cosmetic.',
        ),
        'utility': (
            'She hindered them.',
            'The destination was already mine.',
            'A slow applied to the finite.',
            'Speed used twice.',
            'The third time, she walks.',
            'Refract -- invulnerable, for a moment.',
            'Her velocity is calculated. Predictable. Solved.',
            'She marks where she was.',
            "Not where she'll be.",
            'The hinder works.',
            'On things that still feel it.',
            'A beautiful mechanism. Crude application.',
            'She burns her way back.',
            'The beacon holds her.',
        ),
    },
    'Yoru': {   # he/him
        'spotted': (
            'He hides in the seams.',
            'A rift-walker who cannot walk away.',
            'Flesh dressed in borrowed dimensions.',
            'He haunts the fabric.',
            'Even his footsteps are a lie.',
            "He tears at reality's edge. Graceless.",
            'I have seen his rifts.',
            'They heal themselves.',
            'The lone wolf. How predictably alone.',
            'A scar in the world.',
            'He finds the cracks.',
            'I made them.',
            'He stalks the threshold.',
            'I own it.',
        ),
        'ult': (
            'He steps between worlds.',
            'Dimensional drift. The arithmetic is unchanged.',
            'Not to the math.',
            'He walks in the between.',
            'A ghost rehearsing its own extinction.',
            'The veil heals.',
            'Between dimensions -- still finite, still flesh.',
            'The between is not an escape.',
            'No dimension hides him from me.',
            'He thinks absence is shelter.',
            'Invisible, and still the weakest variable.',
            'He hides where nothing grows.',
        ),
        'damaged': (
            'The rift-walker bleeds like the rest.',
            'He tore the world open.',
            'He did not.',
            'The lone wolf, thinning. Expected.',
            'He walked between worlds.',
            'Not far enough.',
            'The fabric holds. He does not.',
            'He frays.',
            'As all finite things do.',
            'The riftwalker is grounded. Permanently, perhaps.',
            'He tears at existence.',
            'Existence is indifferent.',
        ),
        'utility': (
            "Fake footsteps. A scarecrow's ambition.",
            'He echoes himself. How hollow.',
            'A tethered rift, stretched thin. Breakable.',
            'His anchor is set.',
            'I have noted it.',
            'I require none.',
            'A flash born of a ricochet.',
            'The thread is laid.',
            'I see the thread.',
            'He bluffs in footsteps. Borrowed theater.',
            'He blinds with borrowed light. Insufficient.',
            'A tether to safety.',
            'How human of him.',
        ),
    },
}
