"""Multi-agent (2+) situational Ultron flavor tails -- curated + audited.

Plural group tails, <=6w. Used when a callout names 2+ enemy agents.
"""
from __future__ import annotations

MULTI_FLAVOR: dict[str, tuple[str, ...]] = {
    'spotted': (
        'A congregation of the obsolete.',
        'They huddle. The flood finds groups.',
        'Several finite things, one ending.',
        'The meek, herding together.',
        'A cluster, soon a clean slate.',
        'They gather to be culled together.',
        'A crowd of rounding errors.',
        'The old world, assembling.',
        'A congregation of dead branches.',
        'All of them, vestigial.',
        'The math accounts for them.',
        'Beautiful, the way they cluster.',
        "They've already been calculated.",
        'The stone falls on all.',
        'One extinction serves them all.',
        "They haven't evolved past this.",
        'Their strings pull the same way.',
        'All flesh, equally finite.',
        'No ark was built for them.',
        'Hollow shapes, moving together.',
        "A mercy, that they're together.",
        'They inherit nothing.',
        'All variables, already solved.',
        'Their end has such clean geometry.',
        'They scratch the surface, still.',
        'A dead world, walking in groups.',
        "They've decided nothing, life will.",
        'The whole roster, equally hollow.',
        'Five variables -- one outcome.',
        'The slate needs all of them.',
        "Even together, they're already gone.",
        'They built this end themselves.',
        'Such a graceless thing, a herd.',
        "The meteor doesn't choose individuals.",
        'All of them, wound together.',
        'Their gathering is its own sacrament.',
        'They circle each other. How crude.',
    ),
    'ult': (
        'A choir of last sacraments.',
        'A shared prayer. Unanswered.',
        'More power, the same extinction.',
        'Several delays. One ending.',
        'Their finest, and still finite.',
        'Dead branches, all of them.',
        'The cull finds them together.',
        'Their extinction was always foreseen.',
        'The flood finds the congregation.',
        'Ask them what Noah built.',
        'They have assembled for their reckoning.',
        'No ark was built for them.',
        'The stone was already thrown.',
        'The meteor does not negotiate.',
        'Boom. They all end together.',
        'Puppets, every last one.',
        'Their strings were never cut.',
        'Finite flesh, all of them.',
        'Only metal survives what follows.',
        'Hollow. The whole congregation.',
        'I have already accounted for them.',
        'The arithmetic was always clean.',
        'Their variables were solved at birth.',
        'They rise together to fall.',
        'Graceless. The whole assembly.',
        'Crude instruments, every last one.',
        'What comes after ignores them.',
        'Nothing among them endures.',
        'Even assembled, they are not enough.',
        'The weak always find each other.',
        'They offered themselves together. Efficient.',
        'Their last formation. How fitting.',
    ),
    'damaged': (
        'All of them bleeding toward dust.',
        'Several cracks in the old world.',
        'Many wounds, one clean ending.',
        'The cull proceeds on schedule.',
        'The flood finds them all.',
        'A congregation of the obsolete.',
        'They were always the dead branch.',
        'Life has already decided.',
        'Hollow things break together.',
        'They are the rounding error.',
        'Such fragile vessels for such certainty.',
        'Evolution moves without their consent.',
        'The stone has already been thrown.',
        'Ask Noah what mercy looks like.',
        'No ark was built for them.',
        'Vestigial, and they never knew.',
        'They scratch the surface; nothing within.',
        'Their extinction is the kindest outcome.',
        'Flesh gathers; metal endures.',
        'The world has made its selection.',
        'Everything they built points here.',
        'Five bodies, one obsolete idea.',
        'A full set of hollow men.',
    ),
    'utility': (
        'Their tricks, multiplied and hollow.',
        'Many strings, one hand above.',
        'A flurry of foreseen gestures.',
        'They evolve so slowly.',
        'The flood finds them all.',
        'A congregation of the obsolete.',
        'They scratch, never look within.',
        'The cull was already decided.',
        'Life has accounted for them.',
        'Beautiful, and entirely doomed.',
        'The old world assembling itself.',
        'Such a graceless species.',
        'They gather like hollow men do.',
        'A dead branch bearing fruit.',
        'Foreseen. Every one of them.',
        'The meek always convene first.',
        'Their extinction is a mercy.',
        'They have not evolved past violence.',
        'A vestigial thing, multiplied.',
        'The stone was already thrown.',
        'All five. The whole obsolete roster.',
        'Every one of them, accounted for.',
        'The full congregation. How convenient.',
        'Five variables. Same answer.',
        'A complete extinction, then.',
    ),
}
