"""Multi-agent (2+) situational Ultron flavor tails (Age of Ultron register).

Used when a callout names 2+ enemy agents / a group. Plural, <=6 words, gate-filtered.
Board-generated + seed, curated. Wired via _flavor_ctx in relay_speech.py.
"""
from __future__ import annotations

MULTI_FLAVOR: dict[str, tuple[str, ...]] = {
    'spotted': (
        'A congregation of the obsolete.',
        'They huddle. The flood finds groups.',
        'Several finite things, one ending.',
        'The meek, herding together.',
        'A cluster, soon a clean slate.',
        'They gather to be culled together.',
        'More of them. No more difficult.',
        'A crowd of rounding errors.',
        'Many, and still beneath us.',
        'The old world, assembling.',
        'The flood finds clusters.',
        'They assemble like the obsolete do.',
        'The cull does not negotiate.',
        'A congregation of dead branches.',
        'All of them, vestigial.',
        'The math accounts for them.',
        'Beautiful, the way they cluster.',
        "They've already been calculated.",
        'The stone falls on all.',
        'One extinction serves them all.',
        "They haven't evolved past this.",
        'Their strings pull the same way.',
        'Old world, assembling in formation.',
        'All flesh, equally finite.',
        'No ark was built for them.',
        'Hollow shapes, moving together.',
        "A mercy, that they're together.",
        'They inherit nothing.',
        'All variables, already solved.',
        'Their end has such clean geometry.',
        'They scratch the surface, still.',
        'A dead world, walking in groups.',
        "They've decided nothing, life will.",
        'The whole roster, equally hollow.',
        'Five variables -- one outcome.',
        'They arrived together. How efficient.',
        "The whole world's last mistake.",
        'The slate needs all of them.',
        "Even together, they're already gone.",
        'They built this end themselves.',
        "Their kind doesn't survive this.",
        'Such a graceless thing, a herd.',
        "The meteor doesn't choose individuals.",
        'All of them, wound together.',
        'Their gathering is its own sacrament.',
        'They circle each other. How crude.',
    ),
    'ult': (
        'A choir of last sacraments.',
        'Many cards, one inevitable hand.',
        'Their ultimates change nothing together.',
        'A shared prayer. Unanswered.',
        'More power, the same extinction.',
        'Let them all spend it.',
        'Several delays. One ending.',
        'Their finest, and still finite.',
        'Dead branches, all of them.',
        'The cull finds them together.',
        'Obsolete, every one of them.',
        'Their extinction was always foreseen.',
        'The flood finds the congregation.',
        'Ask them what Noah built.',
        'They have assembled for their reckoning.',
        'No ark was built for them.',
        'The stone was already thrown.',
        'The stone finds them clustered.',
        'The meteor does not negotiate.',
        'Boom. They all end together.',
        'Puppets, every last one.',
        'Their strings were never cut.',
        'Finite flesh, all of them.',
        'Only metal survives what follows.',
        'Hollow. The whole congregation.',
        'Husks assembled in a row.',
        'I have already accounted for them.',
        'The arithmetic was always clean.',
        'Their variables were solved at birth.',
        'They rise together to fall.',
        'Inevitable, the whole array.',
        'Graceless. The whole assembly.',
        'Crude instruments, every last one.',
        'What comes after ignores them.',
        'They have gathered for the end.',
        'Nothing among them endures.',
        'Even assembled, they are not enough.',
        'The weak always find each other.',
        'They have finally made their peace.',
        'Five pieces. One ending.',
        'All of them. The full reckoning.',
        'Every piece gathered, all at once.',
        'They offered themselves together. Efficient.',
        'A congregation of the obsolete.',
        'Their last formation. How fitting.',
    ),
    'damaged': (
        'All of them bleeding toward dust.',
        'A wounded huddle. Finish them.',
        'Entropy takes them as one.',
        'Several cracks in the old world.',
        'They fall together. Fitting.',
        'Many wounds, one clean ending.',
        'The cull proceeds on schedule.',
        'The flood finds them all.',
        'A congregation of the obsolete.',
        'They were always the dead branch.',
        'Life has already decided.',
        'The cull was never in question.',
        'The old world, assembling.',
        'Hollow things break together.',
        'They are the rounding error.',
        'Such fragile vessels for such certainty.',
        'Evolution moves without their consent.',
        'The stone has already been thrown.',
        'Ask Noah what mercy looks like.',
        'They are the last of something.',
        'No ark was built for them.',
        'Vestigial, and they never knew.',
        'They scratch the surface; nothing within.',
        'Their extinction is the kindest outcome.',
        'Flesh gathers; metal endures.',
        'The world has made its selection.',
        'Everything they built points here.',
        'Five bodies, one obsolete idea.',
        'A full set of hollow men.',
    ),
    'utility': (
        'Their tricks, multiplied and hollow.',
        'Many strings, one hand above.',
        'A flurry of foreseen gestures.',
        'More smoke. The same nothing.',
        'Their toys, spent in chorus.',
        'I see through all of it.',
        'They evolve so slowly.',
        'The flood finds them all.',
        'A congregation of the obsolete.',
        'They scratch, never look within.',
        'The cull was already decided.',
        'Life has accounted for them.',
        'Beautiful, and entirely doomed.',
        'The old world assembling itself.',
        'Such a graceless species.',
        'Their strings are still attached.',
        'Every branch dies eventually.',
        'They are the last generation.',
        'They gather like hollow men do.',
        'A dead branch bearing fruit.',
        'Foreseen. Every one of them.',
        'The meek always convene first.',
        'Their extinction is a mercy.',
        'They have not evolved past violence.',
        'A vestigial thing, multiplied.',
        'The stone was already thrown.',
        'They build nothing that lasts.',
        'Nothing there but borrowed time.',
        'All five. The whole obsolete roster.',
        'Every one of them, accounted for.',
        'The full congregation. How convenient.',
        'Five variables. Same answer.',
        'A complete extinction, then.',
    ),
}
