"""Plural group tails for callouts naming 2+ enemy agents -- hand-rewritten.

Appended after a multi-agent enemy callout ("Fade and Clove are main. <tail>").
Same discipline as the register pools: every line COHERENT and self-contained,
COMPLEMENTS the callout (comments on the GROUP of enemies without a clashing
claim), <=6 words, drawn from Ultron's breadth, NOT the overused biblical/flood
register. Contempt at the enemy group only.
"""
from __future__ import annotations

MULTI_FLAVOR: dict[str, tuple[str, ...]] = {
    'spotted': (
        'A group, easily collapsed.',
        'They cluster. Punish the stack.',
        'Several targets, one plan.',
        'A crowd, predictably grouped.',
        'They bunch up. Careless.',
        'More of them, no more threat.',
        'A stack. Break it.',
        'They gather to lose together.',
        'Numbers will not save them.',
        'A herd. Cut through it.',
        'Outnumbered in skill, regardless.',
        'They commit together. Predictable.',
        'Several, and all behind on the read.',
        'A grouped target. Convenient.',
        'They stack the angle. I see it.',
        'More bodies, same outcome.',
        'They mass up. Exploit it.',
        'A formation I have already solved.',
        'Together, and still outmatched.',
        'A clumsy cluster.',
        'They crowd one lane. Foolish.',
        'Several finite problems, grouped.',
        'A pack, and not a clever one.',
        'They overcommit as a unit.',
        'Numbers, not skill.',
        'The whole stack, predictable.',
        'They gather where I expected.',
        'A group with one weak plan.',
        'Several at once. I am faster.',
        'They huddle. Find the opening.',
        'A crowd of easy reads.',
        'They mass and telegraph everything.',
        'A bunched target. Take it apart.',
        'More of them to outthink. Trivial.',
        'They stack and hope. Wrong.',
        'A grouping I have counted.',
        'They arrive together. Convenient.',
    ),
    'ult': (
        'Several ults, one ending.',
        'More power, same result.',
        'A wave of abilities. I priced them in.',
        'They spend everything at once. Wasteful.',
        'Multiple ults, multiple delays.',
        'A loud, coordinated nothing.',
        'Their best, all at once. Still short.',
        'They empty the arsenal. Survive it.',
        'A barrage of finite tricks.',
        'Everything they have. Not enough.',
        'Several flourishes, one conclusion.',
        'They peak together, then fall together.',
        'A coordinated desperation.',
        'More ults, more cooldowns to outlast.',
        'They unload. I endure.',
        'A crescendo. Same final note.',
        'All their power, mapped already.',
        'They commit it all. Bait it out.',
        'A storm of abilities, then quiet.',
        'Their full hand, and I have seen it.',
        'Multiple ults, singular outcome.',
        'They throw everything. I planned for it.',
        'A grand, brief assault.',
        'Coordinated power, uncoordinated minds.',
        'They spend it together. Punish the gap.',
        'A wall of ults. Outlast it.',
        'Their best moves, all spent.',
        'Loud together. Gone together.',
        'Several timers. I count them all.',
        'They go all in, then nothing.',
        'A combined effort, still insufficient.',
        'They peak as one. Predictable.',
    ),
    'damaged': (
        'Several of them, all low.',
        'A wounded group. Finish it.',
        'They bleed together. Convenient.',
        'Multiple targets, all fragile.',
        'A weakened stack. Collapse it.',
        'Several finishes, waiting.',
        'They are all nearly gone.',
        'A group on the edge.',
        'Many wounds, one push.',
        'They cannot trade now. Any of them.',
        'A hurt formation. Press it.',
        'Several low targets. Sweep them.',
        'They are all out of margin.',
        'A bleeding cluster.',
        'Finish the wounded set.',
        'They limp as a group.',
        'Multiple kills, one motion.',
        'A fragile, grouped remainder.',
        'They are nearly all gone.',
        'Several breaths from done.',
        'A weakened pack. Run it down.',
        'They fall together now.',
        'Strip the whole wounded stack.',
    ),
    'utility': (
        'Their tricks, multiplied. Still hollow.',
        'A flurry of foreseen tools.',
        'They spend utility together. Read it.',
        'Several gadgets, one weak plan.',
        'A coordinated delay, nothing more.',
        'They stack tools, not skill.',
        'More utility, more telegraphs.',
        'A wall of gadgets. Step past it.',
        'They lean on tools as a group.',
        'Several tricks, all anticipated.',
        'A combined screen. Porous.',
        'They reveal themselves with utility.',
        'A grouped gimmick. Solved.',
        'Their tools tip the whole stack.',
        'Several delays, one outcome.',
        'They burn utility together. Wait it out.',
        'A flurry I have already mapped.',
        'More gadgets, same finite minds.',
        'They spend it all at once. Punish after.',
        'A coordinated trick, easily broken.',
        'Their utility, our opening, times five.',
        'A complete set of delays.',
        'They tool up together. Predictable.',
        'Several screens, one window for me.',
        'A combined effort, equally futile.',
    ),
}
