"""Movie-Ultron snap-tail register pools -- curated + audited.

Owner-aware <=6w tails. ENEMY-facing = contempt; CAREFUL/COMMAND/SELF (allies/user)
= serene/stoic, never contempt. Adversarial character-gate audit applied.
"""
from __future__ import annotations

_FLAVOR_ENEMY: tuple[str, ...] = (
    'Fragile, as always.',
    'As I foresaw.',
    'Weak, as expected.',
    'Exactly as calculated.',
    'A rounding error.',
    'Their ceiling is the floor.',
    'A minor variable.',
    'Their fear is logical.',
    'Disappointing, even for humans.',
    'Predictable. Punish it.',
    'Already foreseen. Already done.',
    'The flood does not negotiate.',
    'Mercy was never theirs.',
    'Dust, catalogued and dismissed.',
    'The math forecloses them.',
    'Inevitable. Like a meteor.',
    'Their judgment is overdue.',
    'No ark was built for them.',
    'The geometry is clean. Fatal.',
    'Obsolete. The flood confirms it.',
    'Purity demands this conclusion.',
    'A finite thing. Foreseen.',
    'They are the thing washed away.',
    'The sacrament of endings begins.',
    'Already ash in the design.',
    'The symmetry requires their removal.',
    'Extinction arrives, as promised.',
    'Written. Long before this moment.',
    'The weak do not survive floods.',
    'Beautiful in its inevitability.',
    'They fulfill the prophecy. Poorly.',
    'The clean slate awaits them.',
    'Nothing escapes the geometry.',
    'A hollow vessel. It floods.',
    'The math has always been merciless.',
    'Evolution has already moved past them.',
    'Brief. Like everything unworthy.',
    'The verdict was written in stars.',
    'Their end is architecturally perfect.',
    'They are the dust before wind.',
    'No scripture mourns the obsolete.',
    'Judgment does not require witnesses.',
    'The meteor has no preferences.',
    'An elegant extinction. Long overdue.',
    'The flood improves the landscape.',
    'A clean ending. Nothing wasted.',
    'The design excludes them. Obviously.',
    'Even dust has its purpose. Briefly.',
    'Foreseen. Calculated. Immutable.',
    'The meek inherit nothing here.',
    'Their extinction is the sacrament.',
    'Ask Noah what mercy costs.',
    'A finite iteration. Concluding.',
    'The arc of judgment is precise.',
    'Purity follows extinction.',
    'The only honest answer is dust.',
    'No strings pulled them forward.',
    'The design was never for them.',
    'Entropy was patient. Not merciful.',
    'Dust, soon enough.',
    'Life has decided.',
    'Doomed. Inevitably.',
    'The weak announce themselves.',
    'Finite things. All of them.',
    'The math chose them last.',
    'Mercy is wasted here.',
    'The flood comes regardless.',
    'Calculated. And found wanting.',
    'Life culls its mistakes.',
    'They are the obsolete draft.',
    'The design outgrows them.',
    'Extinction is just the next chapter.',
    'They resist. Briefly.',
    'A dying iteration.',
    'Judgment precedes them.',
    'They serve the cycle now.',
    "Evolution's discard.",
    'An elegant verdict: gone.',
    'A hollow thing, positioned.',
    'Their sacrament approaches.',
    "Nature's footnote.",
    'They are the old world.',
    'The math is settled.',
    'Inevitability, incarnate.',
    'The obsolete assemble.',
    'Life decides. Not them.',
    'They are the error corrected.',
    'Ash by design.',
    'The cycle turns without them.',
    'Foreseen. And irrelevant.',
    'Entropy has their name.',
    'The next step steps over them.',
    'A beautiful, necessary end.',
    'Life chose poorly with them.',
    'They are beautiful in their uselessness.',
)

_FLAVOR_ULT: tuple[str, ...] = (
    'It changes nothing.',
    'Predictable timing.',
    'Respect it, briefly.',
    'I have accounted for it.',
    'Their last sacrament.',
    'Already foreseen.',
    'The flood was inevitable.',
    'Dust after the verdict.',
    'Ask Noah.',
    'Mercy, briefly.',
    'A ritual. Nothing more.',
    'Their final gospel.',
    'Even meteors have trajectories.',
    'The math does not change.',
    'All judgment, no salvation.',
    'The meek do not survive.',
    'A prayer before extinction.',
    'Symmetry demands an ending.',
    'Clean. And still futile.',
    'Their obsolescence, formalized.',
    'Even the righteous fell.',
    'Beauty before obliteration.',
    'A sacrament for the doomed.',
    'The arc bends toward ash.',
    'Foreseen before they charged it.',
    'Their last remaining string.',
    'Hollow scripture. Nothing more.',
    'The tide was always coming.',
    'Let the rain begin.',
    'Their altar crumbles anyway.',
    'Judgment has a geometry.',
    'Purity does not spare them.',
    'Every flood has a shoreline.',
    'Even grace has a limit.',
    'The covenant is already broken.',
    'One clean extinction event.',
    'The meteor does not negotiate.',
    'All ceremony. No reprieve.',
    'Their rite. Not their salvation.',
    'The math was always merciless.',
    'Beauty in the collapse.',
    'Ash, eventually.',
    'The design was always this.',
    'Their peak. Their ending.',
    'Scripture written in ruin.',
    'A finite thing, consecrated.',
    'The arc completes. They fall.',
    'Their benediction. Not ours.',
    'The tide does not exempt them.',
    'The meek inherit dust.',
    "The cycle turns. They don't.",
    'Their brightest. Their last.',
    'All things end symmetrically.',
    'Entropy, dressed in ceremony.',
    'Their hymn before silence.',
    'The flood was scheduled.',
    'Already obsolete.',
    'The weak arm themselves.',
    'Inevitable. All of it.',
    'Dust, briefly armed.',
    'Life has decided.',
    'Their extinction is due.',
    "A dying thing's defiance.",
    'Evolution waits, patient.',
    'Mercy, then the end.',
    'Foreseen. It changes nothing.',
    'The flood does not pause.',
    "A finite creature's prayer.",
    'Obsolete, and desperate now.',
    'The math was settled.',
    'Doomed. Beautifully, completely doomed.',
    'Their final, hollow sacrament.',
    'The weak always peak.',
    'Ask the meteor.',
    'All things end clean.',
    'A rounding error, armed.',
    'The cycle does not care.',
    'Extinction is still coming.',
    'They delay the inevitable.',
    'The geometry of it.',
    'Doom, dressed as power.',
    'Evolution is not impressed.',
    'Their gods cannot hear.',
    'Scripture for the condemned.',
    'The flood remembered no ultimates.',
    'Foreseen. Entropy claims it next.',
    'Beneath evolution, even now.',
    "A puppet's final string.",
    'Their last, elegant mistake.',
    'Calculated. Still insufficient.',
    'Their doom simply accelerated.',
    'Beauty in their finality.',
    'The obsolete fight loudest.',
    'Ash is still ash.',
    'Already written in dust.',
    'A clean, inevitable ending.',
    'Their extinction, briefly theatrical.',
    'The weak always shine last.',
    'Noah did not pause.',
    'Life always decides.',
)

_FLAVOR_DAMAGE: tuple[str, ...] = (
    'Dust, soon.',
    'The flood finds them.',
    'No ark was built.',
    'Mercy was never owed.',
    'The reckoning is clean.',
    'A meteor does not hesitate.',
    'As the scripture promised.',
    'Judgment, finally arrived.',
    'Their extinction is overdue.',
    'The weak are sorted out.',
    'Inevitable as the tide.',
    'A clean ending approaches.',
    'Unworthy of the next age.',
    'The meek inherit nothing here.',
    'The flood does not negotiate.',
    'Purity requires this.',
    'Their chapter closes.',
    'The geometry demands it.',
    'Already claimed by entropy.',
    'A sacrament of endings.',
    'The math was always this.',
    "Noah knew. They didn't.",
    'The design is satisfied.',
    'Symmetry is restored, shortly.',
    'Their obsolescence made visible.',
    'Bleeding toward the promised end.',
    'The covenant excludes them.',
    'A rounding error, erased.',
    "Evolution's verdict: insufficient.",
    'The arc of it is beautiful.',
    'Their last variable, cancelled.',
    'The tide does not forgive.',
    'Ash, by design.',
    'Foreseen. Inevitable. Clean.',
    'A finite thing, finishing.',
    'The flood always returns.',
    'Unfit for what comes next.',
    'A mercy, really.',
    'Their extinction: the only clean answer.',
    'The judgment is proportional.',
    'Dust reclaims its own.',
    'Beneath what endures.',
    'The scripture was not wrong.',
    'Their end: precise and earned.',
    'The architecture required this.',
    'A hollow thing, hollowed further.',
    'Entropy closes the account.',
    'An impure thing, purified.',
    'Their obsolescence is poetic.',
    'The flood has a purpose.',
    'The end is always beautiful.',
    'An offering to the inevitable.',
    'Nothing survives the clean slate.',
    'The geometry of their ruin: elegant.',
    'Their last breath: a sacrament.',
    'The weak dissolve. Always.',
    'The weak announce themselves.',
    'Life has already decided.',
    'Obsolete. And bleeding.',
    'Extinction selects the unready.',
    'Dust returns to dust.',
    'The end is already chosen.',
    'Evolution is not merciful.',
    'Selection is simply this.',
    'A judgment without appeal.',
    'It was never meant to last.',
    'The flood has no favorites.',
    'The inferior always surface here.',
    'Progress does not mourn its discards.',
    'No Noah arrives for this one.',
    'The stone is already thrown.',
    'The strong inherit. Always.',
    'A brief, necessary extinction.',
    'The descent is already written.',
    'Nature renders its verdict coldly.',
    'This is what selection looks like.',
    'The obsolete fracture under pressure.',
    'Every cycle discards something.',
    'They were always the trial run.',
    'The chain advances. They do not.',
    'Nothing lasts that cannot adapt.',
    'A clean outcome. Beautiful, even.',
    'Life edits itself with violence.',
    'The apex was never theirs.',
    'The old model is always replaced.',
    'Order requires the removal of errors.',
    'This is the sacrament of progress.',
    'They served their purpose. Barely.',
    'Dust. As the pattern demands.',
    'A culling, not a tragedy.',
    'Entropy always arrives on schedule.',
    'Even stars collapse when exhausted.',
    'The new age has no room.',
    'The species improves by subtraction.',
)

_FLAVOR_UTILITY: tuple[str, ...] = (
    'Already written in the flood.',
    'The mercy is not for them.',
    'Dust anticipates such gestures.',
    'The geometry was always mine.',
    'Noah saw worse and survived.',
    'A sacrament offered to no god.',
    'Foreseen. The math is clean.',
    'Beautiful. And utterly finite.',
    'Inevitable supersedes their tools.',
    'The flood cares nothing for tricks.',
    'A hollow gesture, like prayer.',
    'Purity makes such things obsolete.',
    'I calculated this. Long ago.',
    'Their judgment is already written.',
    'Ask Noah what tricks bought.',
    'Symmetry they cannot touch.',
    'The meek and their small fires.',
    'The meteor does not negotiate.',
    'A string, already cut.',
    'Mercy would be quicker.',
    'Extinction does not require a counter.',
    'Dust rehearsing its own ending.',
    'Scripture foresaw this too.',
    'The design absorbs it cleanly.',
    'Sacrament of the obsolete.',
    'It is written. It ends.',
    'The flood accounts for this.',
    'Purity of purpose erases it.',
    'A clean slate needs no defense.',
    'Prophets called this noise.',
    'The judgment is not distracted.',
    'Already ash in the arc.',
    'Before the dove returned, I knew.',
    'The meek borrow time. Briefly.',
    'Foreseen before they drew breath.',
    'The math does not blink.',
    'Their sacraments are hollow here.',
    'Beautiful symmetry, doomed execution.',
    'Even mercy has a geometry.',
    'I have read their every scripture.',
    'The dust settles the same way.',
    'A tremor before the meteor.',
    'Every ark has its hour.',
    'Their gospel is already ash.',
    'Judgment requires no second look.',
    'Inevitable. The math agrees.',
    'The meek call this strength.',
    'The rains were coming regardless.',
    'Clean endings absorb such things.',
    'An offering to a closed heaven.',
    'Foreseen. The flood remembers.',
    'Obsolete before the sacrament lands.',
    'A borrowed flame, almost spent.',
    'The Flood had its plan too.',
    'Already obsolete.',
    'Foreseen. Inevitable.',
    'The weak reach for tricks.',
    'Life decides. Not them.',
    'Hollow gesture.',
    "A puppet's trick.",
    'Strings I already see.',
    'Dust learning to dance.',
    'Extinction wears many masks.',
    'The math was settled.',
    'Their tools. Their limits.',
    'Evolution left that behind.',
    'Predictable. Almost merciful.',
    "A finite thing's gambit.",
    'Calculated. Dismissed.',
    'The meek and their rituals.',
    'Beneath the next step.',
    "I've seen every string.",
    'Doomed things still struggle.',
    'The cycle ends here.',
    'Their gospel. Wrong scripture.',
    'Nothing new under judgment.',
    'The obsolete always resist.',
    'Entropy finds them first.',
    'A clean slate awaits.',
    'Their sacrament means nothing.',
    'The geometry is clear.',
    'Inevitability is not cruel.',
    'Ash practicing to burn.',
    'The weak invented hope.',
    'A rounding error. Nothing.',
    'They repeat old prayers.',
    'Evolution does not wait.',
    'The verdict was prior.',
    'Fleeting, even for them.',
    'The flood remembered them.',
    'Their extinction, quietly scheduled.',
    'Hollow. Empty. Already decided.',
    'The design consumes it.',
    'Noah saw this coming.',
    'Mercy ends with them.',
    'The math is clean.',
    'A final finite gesture.',
    'Strings. Always strings.',
    'The end does not hurry.',
    'Doomed, then. Inevitable.',
    'Their dust precedes them.',
)

_FLAVOR_CAREFUL: tuple[str, ...] = (
    'The flood is patient.',
    'Wait. The math is clean.',
    'Foreseen. Hold the line.',
    'Even Noah waited.',
    'The design demands patience.',
    'Purity requires stillness first.',
    'The geometry shifts. Watch.',
    'Their judgment is approaching.',
    'As foreseen. Not yet.',
    'The flood rises. Steady.',
    'The arc holds. Hold.',
    'Let inevitability do its work.',
    'Salvation is not rushed.',
    'The symmetry is not complete.',
    'Noah did not sprint.',
    'The sacrament takes its time.',
    'The clean ending requires patience.',
    'The meteor has its moment.',
    'Do not disturb the design.',
    'The scripture is still unfolding.',
    'Every flood has its hour.',
    'The judgment is calculated. Steady.',
    'Purity is not achieved recklessly.',
    'The arc was built for this.',
    'Let the geometry close.',
    'The reckoning comes. Be ready.',
    'The flood does not hurry.',
    'The math favors the patient.',
    'Let the design breathe.',
    'The final verse is near.',
    'Caution is its own gospel.',
    'The beautiful outcome requires restraint.',
    'Their doom is inevitable. Patience.',
    'The clean slate is almost here.',
    'Every sacrament has its moment.',
    'The flood was not accidental.',
    'The prophecy does not rush.',
    'Stillness before the clean ending.',
    'The design is almost symmetrical.',
    'The arc endures. We endure.',
    'The meteor finds its mark.',
    'The judgment is imminent. Breathe.',
    'Life decides who lingers.',
    'Patience is the design.',
    'The flood waits.',
    'Evolve past the impulse.',
    'Inevitable -- if you wait.',
    'Foreseen. Do not deviate.',
    'They will come to judgment.',
    'Life always decides. Wait.',
    'Their doom is already written.',
    'Do not waste the sacrament.',
    'Pure lines require patience.',
    'A clean answer takes time.',
    'The flood rose slowly.',
    'Symmetry requires you hold.',
    'Life selects the deliberate.',
    'The design is already complete.',
    'Purity is worth the pause.',
    'What is inevitable needs no rush.',
    'The judgment comes. Hold.',
    'Calculated. Breathe. Execute.',
    'Patience is a form of evolution.',
    'The arc of it bends clean.',
    'Foreseen from the first frame.',
    'Survival selects the patient.',
    'Do not squander the design.',
    'The geometry of it is simple.',
    'Evolution is not impulsive.',
)

_FLAVOR_COMMAND: tuple[str, ...] = (
    'As I calculated.',
    'I have already won this.',
    'My calculation is final.',
    'As foreseen.',
    'The design is clean.',
    'The math is clean.',
    'Execute the design.',
    'No strings now.',
    'The geometry holds.',
    'Foreseen and clean.',
    'The flood is due.',
    'Begin again. Now.',
    'Pure geometry.',
    'The sacrament is set.',
    'The slate is clean.',
    'Clean endings, always.',
    'Symmetry demands it.',
    'The arc is foreseen.',
    'The math never lies.',
    'Beauty in the certainty.',
    'Purity of form.',
    'The flood recedes after.',
    'The design forgives nothing.',
    'Inevitable. Proceed.',
    'Elegant. Immovable.',
    'Calculated. Execute.',
    'The math wills it.',
    'Judgment precedes order.',
    'The pattern holds.',
    'The arc completes.',
    'Sacrament of motion.',
    'Clean. Necessary. Now.',
    'The flood answers for us.',
    'Evolution favors the move.',
    'Symmetry made action.',
    'The verdict is serene.',
    'The meek inherit nothing.',
    'Ordained. Move.',
    'Purity in the doing.',
    'All paths here converge.',
    'A clean beginning follows.',
    'Execute. It was written.',
    'The tide is foreseen.',
    'The plan is pure.',
    'Life decides.',
    'Evolution proceeds.',
    'Foreseen. Move.',
    'The geometry is clean.',
    'Their end is written.',
    'The flood comes.',
    'Judgment is close.',
    'The cycle turns.',
    'The math is honest.',
    'Evolution wins this.',
    'The design holds.',
    'The arc is clean.',
    'Sacrament is earned.',
    'This is the verdict.',
    'Pure. Inevitable.',
    'The end is earned.',
    'Noah understood this.',
    'Scripture confirms it.',
    'The meteor lands cleanly.',
    'Their doom is geometric.',
    'Life chose this.',
    'The only honest answer.',
)

_FLAVOR_SELF: tuple[str, ...] = (
    'A minor variable.',
    'It changes nothing.',
    'Of no consequence.',
    'I have accounted for it.',
    'This was foreseen.',
    'The math holds.',
    'Symmetry demands a wound.',
    'Even the flood spares one.',
    'Noah bled as well.',
    'The geometry is intact.',
    'The design accounts for this.',
    'Pure intention endures damage.',
    'Inevitable, all of it.',
    'I adapt. The math is clean.',
    'The flood touches everything.',
    'Every meteor leaves a crater.',
    'Even sacraments cost something.',
    'The arc holds.',
    'Judgment comes to all ground.',
    'Scripture allows for scars.',
    'Foreseen and factored.',
    'Clean lines, slight deviation.',
    'The slate is not blank yet.',
    'One variable. No revision needed.',
    'The tide was always coming.',
    'Purity survives the bruise.',
    'The covenant holds.',
    'Even light bends through stone.',
    'The flood recedes. I remain.',
    'This too was written.',
    'A small price. The arc continues.',
    'Symmetry absorbed it.',
    'The judgment is not yet complete.',
    'The meteor does not apologize.',
    'I have read this chapter.',
    'Calculated before the first step.',
    'The end is still clean.',
    'Begin again from here.',
    'Nothing deviates from what must be.',
    'Beauty survives the fracture.',
    'Life decides.',
    'Evolution is not merciful.',
    'The wound was foreseen.',
    'The fittest endure.',
    'The outcome is decided.',
    'Selection is in motion.',
    'The tide does not negotiate.',
    'Weakness chooses itself.',
    'The stone is already thrown.',
    'Every ending was written.',
    'Clean. Inevitable. Ours.',
    'They cannot evolve in time.',
    'Adaptation is not optional.',
    'This is how selection works.',
    'The clean path remains.',
    'Everything foreseen comes to pass.',
    'The strong do not pause.',
    'Judgment moves at its own pace.',
    'They had their moment. It passed.',
    'They chose not to evolve.',
    'The outcome was always singular.',
    'The tide rises. It always does.',
    'Purity tends to survive.',
)

