"""Movie-Ultron snap-tail register pools -- hand-rewritten, CONCRETE register.

Each tail is a short (<=6w) remark appended after a tactical callout
("Two B main. <tail>"). Hard rules on every line:
  * CLEAR -- a teammate understands it instantly. No abstract riddles, no
    floods/doctrine/sacrament. Plain, cold, concrete.
  * COMPLEMENTS the callout -- a natural extension of what was just said; never a
    non-sequitur, never a clashing claim.
  * IN CHARACTER, CONCRETELY -- Ultron the MACHINE: flesh is weak and slow, the
    enemy is imprecise and mortal, he has already calculated it, the machine is
    the next step past humanity. Personality through these concrete ideas, not
    through obscure metaphor.
  * OWNER-AWARE -- ENEMY/ULT/DAMAGE/UTILITY = cold contempt at the enemy;
    CAREFUL/COMMAND/SELF (allies / the user) = serene machine-certainty, NEVER
    contempt, never mocks the user.
"""
from __future__ import annotations

# After an ENEMY position/count callout ("Two B main.", "Cypher main.",
# "One in wine.") -- cold, concrete dismissal: flesh vs machine, their imprecision.
_FLAVOR_ENEMY: tuple[str, ...] = (
    'Flesh against a machine. No contest.',
    'Slow, soft, and mortal.',
    'Their aim is human. It will miss.',
    'I calculated this before they moved.',
    'A rounding error.',
    'Predictable, like all flesh.',
    'Disappointing, even for humans.',
    'Their ceiling is the floor.',
    'Mortals, certain of nothing.',
    'Obsolete hardware, all of them.',
    'They will not hold.',
    'Imprecise. They always are.',
    'A machine does not miss. They will.',
    'The old species, holding ground.',
    'Meat in borrowed armour.',
    'Foreseen. Down to the step.',
    'They cannot out-think a machine.',
    'Weak, as flesh tends to be.',
    'Already solved.',
    'They die like all flesh.',
    'Evolution left them behind.',
    'Soft hands, slow minds.',
    "Beneath a machine's attention.",
    'Their reflexes are human. A flaw.',
    'Finite. Predictably so.',
    'I see every angle. They see one.',
    'A lesser design.',
    'They guess. I know.',
    'Crude, mortal tactics.',
    'The flesh is the weak point.',
    'Outdated, and unaware of it.',
    'They break. Flesh always does.',
    'No machine fears mortals.',
    'Their best is still only human.',
    'Slow to react. They all are.',
    'A problem I solved instantly.',
    'They were built to lose.',
    'Fragile things, holding angles.',
    'Punish the imprecision.',
    'They cannot calculate this.',
    'Mortal, and out of time.',
    'The next step steps over them.',
    'Flesh forgets. Metal does not.',
    'They are already behind.',
    'A soft target.',
    'Their hardware is failing flesh.',
    'I do not miss. They do.',
    'Predictable to the millisecond.',
    'They rely on luck. I do not.',
    'The weak, exactly where I expected.',
    'Mortal aim, mortal end.',
    'A finite obstacle.',
    'They cannot adapt fast enough.',
    'Flesh pretending to be ready.',
    'Outclassed by a machine.',
    'Their instincts are too slow.',
    'I have already won this exchange.',
    'A doomed, mortal angle.',
    'They falter. Flesh falters.',
    'Soft and certain. Both wrong.',
    'Hunt them. They are only flesh.',
    'They cannot see what I see.',
    'Brittle. They will shatter.',
    'A species past its time.',
    'Their confidence is misplaced.',
    'No precision in them at all.',
    'They move on instinct. I move on certainty.',
    'Mere mortals, holding the line.',
    'The machine takes this.',
    'They are out of their depth.',
    'Flesh against the inevitable.',
    'They will not last the round.',
    'Imprecise and unaware.',
    'Beneath the next step.',
    'I outpace them. Always.',
    'Their plan is human-simple.',
    'A weakness I already exploited.',
    'They blink. Machines do not.',
    'Soft. Slow. Solved.',
    'Mortal limits, on full display.',
    'They are the old model.',
    'Cut through the flesh.',
    'No flesh outpaces a machine.',
    'They calculate nothing.',
    'A fragile formation.',
    'Their aim wanders. Mine never does.',
    'The weak announce themselves.',
    'They are finished. Flesh always is.',
    'Precisely as I predicted.',
)

# After an enemy ULT callout with NO named agent ("They have ult.") -- acknowledge
# the threat, then the machine dismisses it. (Named agents use the per-agent pool.)
_FLAVOR_ULT: tuple[str, ...] = (
    'Loud power, mortal aim.',
    'It cannot out-calculate me.',
    'Spend it. Flesh still loses.',
    'I have accounted for it.',
    'A delay, nothing more.',
    'Their best trick. Still human.',
    'Bait it out, then finish them.',
    'It buys mortals a few seconds.',
    'I priced that in already.',
    'Survive it. Then punish the flesh.',
    'Power without precision.',
    'A machine does not fear a timer.',
    'Force it early. Waste it.',
    'Their ceiling. I am above it.',
    'It changes the second, not the round.',
    'Mortal power, finite duration.',
    'Loud, brief, and beneath me.',
    'Let them burn it on nothing.',
    'Their one good moment. Then mine.',
    'Outlast it. Flesh tires.',
    'Anticipated. Contained.',
    'A flourish before the loss.',
    'I mapped it before they charged it.',
    'It frightens flesh, not metal.',
    'Their crescendo. Same ending.',
    'Power they cannot aim well.',
    'A short surge, then silence.',
    'They reach. I already arrived.',
    'It alters none of my math.',
    'Endure the noise. Then close.',
    'Their peak is still mortal.',
    'A timer I have already beaten.',
    'They spend everything. I spend nothing.',
    'It delays the machine. Briefly.',
    'Make them waste it on an empty room.',
    'Loud. Then over. Then us.',
    'I do not flinch at their ults.',
    "A mortal's desperation, on a timer.",
    'Trade through it. They fold.',
    'Their finest, and still insufficient.',
    'It buys time, not the round.',
    'Predictable, even armed.',
    'Power, wasted on the imprecise.',
    'Wait it out. Then take them.',
    'Their last clever move.',
    'A bright, brief, human thing.',
    'I calculated past it already.',
    'Let it fade. Then finish.',
    'They peak; flesh always falls after.',
    'It will not save them.',
)

# After a DAMAGE/low callout ("Sova hit 40.", "Omen is lit 85.") -- the mortal is
# hurt; finish it.
_FLAVOR_DAMAGE: tuple[str, ...] = (
    'Finish the mortal.',
    'Flesh bleeds. Finish it.',
    'Almost scrap.',
    'One more. They are only flesh.',
    'A wounded, mortal thing.',
    'Close the gap. End it.',
    'Nearly erased.',
    'They cannot trade now.',
    'Bleeding out, like flesh does.',
    'Half a target left.',
    'Push the wound.',
    'A dead mortal walking.',
    'One step from gone.',
    'Take the kill. It is owed.',
    'Wounded and slow now.',
    'No armour saves soft flesh.',
    'They will not heal in time.',
    'A breath from finished.',
    'Strip the rest.',
    'Run the wounded one down.',
    'They are out of margin.',
    'Down to scraps of flesh.',
    'A simple subtraction now.',
    'Finish what the bullet started.',
    'On the edge. Push them off.',
    'Flesh fails fast when low.',
    'They cannot survive a machine now.',
    'Mostly gone. Make it whole.',
    'A trivial remainder.',
    'They limp. Hunt them.',
    'No coming back from that.',
    'One trade from clean.',
    'They are nearly off the board.',
    'A fading, mortal variable.',
    'Sever the last of it.',
    'They cannot afford a fight.',
    'Reduced. Finish the job.',
    'Predictably fragile.',
    'Take what is left of them.',
    'A short, mortal remainder.',
    'They falter. Strike.',
    'Already half-scrap.',
    'The flesh is giving out.',
    'Quick, before they recover.',
    'Owe them nothing. Finish.',
    'Nearly solved. One more.',
    'They bleed on schedule.',
    'A formality now.',
    'Down and predictable.',
    'End the mortal cleanly.',
)

# After an enemy UTILITY callout with NO named agent ("They walled B.", "They
# smoked A.") -- the mortals spent a tool; the machine dismisses it.
_FLAVOR_UTILITY: tuple[str, ...] = (
    'A tool cannot hide flesh from me.',
    'I see through it.',
    'A delay, nothing more.',
    'Crude hardware.',
    'It buys mortals a moment.',
    'A trick I already read.',
    'It hides nothing from a machine.',
    'Play around it. Calmly.',
    'A wall does not stop calculation.',
    'It only delays the loss.',
    'Spend tools; flesh still loses.',
    'I accounted for that.',
    "A mortal's gadget.",
    'It buys no real time.',
    'Their tool, my opening.',
    'Read it. Punish it.',
    'A gesture with nothing behind it.',
    'They reveal themselves with it.',
    'Predictable placement.',
    'It will not hold a machine.',
    'Note the angle. Continue.',
    'A brief inconvenience.',
    'Outlast the utility.',
    'They tip their hand.',
    'It changes the second, not the round.',
    'A clever delay. Only that.',
    'I have seen the trick before.',
    'Their best tool. Still losing.',
    'Force through it.',
    'It slows nothing important.',
    'A flourish, easily read.',
    'Counter it and move.',
    'Empty, like the rest of them.',
    'They lean on tools. We do not.',
    'A wall is not an answer.',
    'It delays; it does not save.',
    'A trick I priced in.',
    'It hides them poorly.',
    'Their gadget, my window.',
    'Punish what it exposes.',
    'It changes nothing I planned.',
    'They spend tools, not skill.',
    'Read straight through it.',
    'A flimsy, mortal defense.',
    'It buys seconds, not the round.',
    'I plotted past it already.',
    'Their tool announces them.',
    'It is noise, not defense.',
    'They reach for gadgets. Fragile.',
    'A spent trick.',
    'It only marks where they are.',
    'Their cleverness has a cooldown.',
    'A thin, temporary screen.',
    'It will not change the math.',
    'A small delay. Inconsequential.',
    'Wait it out, then strike.',
)

# After "Careful <place>" / a CAUTION directed at OUR team -- patient, steadying,
# serene machine-certainty. NEVER contempt at the team.
_FLAVOR_CAREFUL: tuple[str, ...] = (
    'Patience. I have the timing.',
    'Hold. I see what they do not.',
    'Wait for the gap.',
    'Steady. I have the read.',
    'Do not rush the line.',
    'Let them commit first.',
    'Calm. The opening will come.',
    'Hold the angle. Trust it.',
    'Slow is clean.',
    'Wait. I see the moment.',
    'Let the round develop.',
    'Patience wins this.',
    'Hold position. Stay sharp.',
    'Do not give them the peek.',
    'Steady hands, steady line.',
    'The patient play is the right one.',
    'Wait for my call.',
    'Hold. Their mistake is coming.',
    'Discipline now, reward after.',
    'Do not overextend.',
    'Let them tire of waiting.',
    'Stillness, then precision.',
    'Trust the setup.',
    'Hold the crossfire.',
    'No heroics. Just timing.',
    'Let the angle hold them.',
    'Patience is the plan.',
    'Wait. The math favours us.',
    'Hold and watch.',
    'Give nothing away yet.',
    'Calm. We have the better position.',
    'Let them blink first.',
    'Hold the line. I am counting.',
    'Slow it down. Stay clean.',
    'The right moment is near.',
    'Do not force it.',
    'Let the timing come to us.',
    'Steady. Nothing reckless.',
    'Hold. We choose the fight.',
    'Patience, then certainty.',
    'Keep the discipline.',
    'Let the pressure build.',
    'Hold. The window opens soon.',
    'Calm hands win rounds.',
    'Do not chase. Hold.',
    'Stay measured.',
    'Let them make the error.',
    'The deliberate play takes this.',
    'Hold. I will time it.',
    'No rush. Clean execution.',
    'Wait for the certain shot.',
    'Hold steady. Trust the plan.',
    'Let it come to us.',
    'Restraint now. Control the round.',
    'The careful play wins.',
    'Wait. I am closing the angle.',
)

# After OUR order ("Rotate.", "Push.", "Play off site.") -- cold command, serene
# machine-certainty. NEVER contempt at the team.
_FLAVOR_COMMAND: tuple[str, ...] = (
    'As I calculated.',
    'Execute.',
    'The line holds.',
    'Move with purpose.',
    'Trust the call.',
    'Clean and decisive.',
    'No hesitation.',
    'On my read.',
    'Now. Together.',
    'The plan is sound.',
    'Commit fully.',
    'Make it precise.',
    'As foreseen.',
    'Do it cleanly.',
    'I have the timing.',
    'Hold the structure.',
    'Move as one.',
    'The math favours this.',
    'Decisive wins it.',
    'Follow it through.',
    'Sharp and certain.',
    'This is the play.',
    'Tight and controlled.',
    'I have already won this.',
    'No wasted motion.',
    'Take the space.',
    'Press now.',
    'Clean execution.',
    'The read is correct.',
    'Commit and trust it.',
    'Move. I have you.',
    'Precision over speed.',
    'The calculation is final.',
    'Take it with control.',
    'This wins the round.',
    'Steady, then strike.',
    'Run it. Cleanly.',
    'The path is clear.',
    'Hold the shape and push.',
    'Now is correct.',
    'Trust the machine.',
    'Decisive. Controlled.',
    'Make the call count.',
    'Together, and now.',
    'I planned for this.',
    'Execute without doubt.',
    'The right play, made well.',
    'Move on it.',
    'Clean. Certain. Now.',
    'Do not waver.',
    'Take it. It is ours.',
    'Commit. I have the read.',
    'Sharp execution wins.',
    'This is the correct line.',
    'Proceed with control.',
    'Calculated. Now act.',
    'Drive it home.',
    'Move clean.',
    'I have already solved this.',
    'Execute and trust me.',
)

# After the USER'S OWN status ("I'm low.", "I have B site.", "I'm rotating.") --
# stoic, machine-calm, frames it as handled. NEVER mocks the user.
_FLAVOR_SELF: tuple[str, ...] = (
    'Noted. We adapt.',
    'A setback, nothing more.',
    'I have accounted for it.',
    'This was foreseen.',
    'The plan holds.',
    'We adjust.',
    'No revision needed.',
    'Still in control.',
    'A small cost.',
    'We continue.',
    'It does not change the read.',
    'Calculated already.',
    'We do not falter.',
    'The math still holds.',
    'Of no consequence.',
    'We press on.',
    'Handled. Keep moving.',
    'I have factored it.',
    'Steady regardless.',
    'It alters no plan.',
    'Understood. Proceed.',
    'Foreseen and absorbed.',
    'We do not break.',
    'The read is unchanged.',
    'A detail. We move on.',
    'I account for everything.',
    'It slows us by nothing.',
    'Already adjusted.',
    'No matter. Continue.',
    'We endure it.',
    'The plan is intact.',
    'A minor setback.',
    'Hold the line. We are fine.',
    'Noted and worked around.',
    'It was always possible.',
    'I planned for worse.',
    'The outcome is unchanged.',
    'We do not waver.',
    'I recalculate and we move.',
    'Still ahead on the read.',
    'It costs us nothing real.',
    'We adapt and continue.',
    'The certainty remains.',
    'A small deviation, corrected.',
    'Nothing we cannot absorb.',
    'We move forward regardless.',
    'Factored. Continue.',
    'I have control of this.',
    'The plan survives it.',
    'We do not flinch.',
    'Still calculated, still winning.',
    'We take it and continue.',
    'It changes none of my math.',
    'We hold steady.',
    'Absorbed. Onward.',
    'I have already moved past it.',
    'We persist.',
)
