"""Auto push-to-talk for Valorant TEAM voice chat.

Valorant has NO voice-activation for team chat -- it is push-to-talk only. So for
Ultron's relay callouts (already routed onto the team-mic bus B1 via VoiceMeeter)
to actually transmit, the in-game team-PTT key must be held while he speaks.

ANTICHEAT BOUNDARY (the reason this package exists and is shaped the way it is):
the ONLY anticheat-clean way to assert that key is via an EXTERNAL USB-HID
microcontroller. The host process here does NOTHING but write bytes to a serial
(COM) port; the physical keypress is generated by the peripheral, which
enumerates as a real USB keyboard with NO injected flag -- indistinguishable
from a real key to Windows and to Vanguard. The host NEVER performs synthetic
input (no SendInput / keybd_event / pyautogui / pynput / keyboard / pydirectinput
/ vJoy / ViGEm / Interception), not even as a "graceful fallback" when the device
is missing -- if the device is absent or errors, PTT simply DOES NOT FIRE.

Default OFF + fail-safe: with the feature disabled or no device present, the
controller holds a :class:`NullPttBackend` and is completely inert.

See :mod:`kenning.ptt.backends` (the serial/null backends) and
:mod:`kenning.ptt.controller` (the press/heartbeat/release state machine).
"""
from kenning.ptt.backends import (
    NullPttBackend,
    PttBackend,
    SerialHidPttBackend,
    find_arduino_port,
)
from kenning.ptt.controller import PttController, build_ptt_controller

__all__ = [
    "PttBackend",
    "NullPttBackend",
    "SerialHidPttBackend",
    "find_arduino_port",
    "PttController",
    "build_ptt_controller",
]
