"""Valorant map callout vocab pack for the relay test corpus.

ITEMS is a flat list of raw utterances -- what the streamer (or a
teammate talking to Ultron) would actually SAY before invoking the
relay. Each string is a single turn of speech (no relay prefix). Domain:
enemy positions, counts, rotations, spike status, and a handful of
flavor/persona fragments, across all 11 live Valorant maps.

Register mix:
  - Terse snap callouts: "two B", "last heaven", "spike A"
  - Natural spoken: "yo they're all pushing B long, like four of them"
  - Teammate-to-Ultron: "Ultron, what do you see?", "are they rushing A?"
  - Persona/flavor fragments: "I am Ultron. I do not miss."
  - I-am / first-person self-reports: "I'm flanking", "I'm planting"
  - Damage callouts: "Sova hit 84", "Clove hit 120"
  - Ult callouts: "their Breach has ult", "their Fade, Breach, and Yoru all have ults"
  - Economy / strategy: "they're on eco", "full buy them"
  - Rotation / movement: "rotate to B", "fall back to site"
"""

ITEMS: list[str] = [
    # ------------------------------------------------------------------ ASCENT
    "two A main",
    "one B main",
    "three mid",
    "four A site",
    "last is market",
    "last market",
    "two B link",
    "one cat",
    "three B site",
    "one A rafters",
    "two top mid",
    "one A lobby",
    "three going A",
    "two going B",
    "one sneaking through mid doors",
    "last is back site A",
    "two A main, one more rotating from mid",
    "Jett hit 84 on A main",
    "Sova hit 94, B site",
    "Clove hit 120 through the doors",
    "their Reyna has ult",
    "their Jett has ult, push carefully",
    "their Sova just used ult",
    "they're rotating from A to B",
    "one rotating mid",
    "two rotating B through mid doors",
    "spike A, they're planting",
    "spike planted A main area",
    "defusing B site, I need help",
    "they're defusing, rush B",
    "spike dropped at B default",
    "yo they're all hitting A, like four of them",
    "bro three of them just crossed mid",
    "they're stacking B hard this round",
    "market is clear, push through",
    "two holding B link, one more in market",
    "I have B, one is lurking through mid",
    "all five hit A, no split",
    # ------------------------------------------------------------------ BIND
    "two hookah",
    "one A short",
    "two showers",
    "last is B heaven",
    "two A lamps",
    "one going through A teleport",
    "three A short, two more hookah",
    "last short",
    "two B elbow",
    "one B long",
    "two going hookah",
    "Viper wall blocked their push, two took 40 each",
    "Breach hit 120 through hookah",
    "their Raze has ult",
    "their KAY/O has ult, watch your flashes",
    "their Brimstone ult is on A",
    "rotating A to B through showers",
    "two rotating from A via teleport",
    "spike B default, defusing now",
    "they're planting A lamps side",
    "spike A, they have a defuse",
    "four of them went hookah, one is short",
    "they're all stacking A this round, I can see it",
    "two holding showers, angle is nasty",
    "the teleport side is completely open",
    "yo one is lurking hookah way late",
    # ------------------------------------------------------------------ HAVEN
    "one C long",
    "two C site",
    "last is A heaven",
    "one A heaven",
    "two mid window",
    "three going C",
    "one B garage",
    "two A short",
    "last is C lobby",
    "three A, two C",
    "one rotating from B to A",
    "Omen hit 74 through B smoke",
    "Skye hit 100 in A heaven",
    "their Omen has ult",
    "their Astra has ult, play safe",
    "their Chamber just used his ult",
    "two rotating from C through mid",
    "one rotating to A from garage",
    "spike C, they're planting",
    "spike A, defusing",
    "spike planted C site, need rotate",
    "yo they're splitting, two A two C",
    "three of them went long C, watch the rotate",
    "garage is uncontested, someone take it",
    "they are passive this round, all sitting in their spawn",
    # ------------------------------------------------------------------ SPLIT
    "two A heaven",
    "last is Split B heaven",
    "one A ramp",
    "two B ramp",
    "last heaven",
    "two vents",
    "one top mid",
    "two B sewer",
    "three going A sewer",
    "last is A sewer",
    "Sage hit 84 healing wall caught them",
    "Raze hit 140 satchel entry A",
    "their Raze ult is up",
    "their Cypher cage spammed B vents",
    "their Breach has ult, push B ramp carefully",
    "rotating from B to A via mid",
    "two coming through vents",
    "spike B site, planted screen side",
    "spike A default, defusing",
    "bro they're stacking A heaven, four up there",
    "vents cleared, two are ramp side",
    "I'm playing off A ramp, catch their push",
    # ------------------------------------------------------------------ ICEBOX
    "one B yellow",
    "two A belt",
    "last is A rafters",
    "two B green",
    "one B snowmen",
    "two mid top",
    "last is B kitchen",
    "one A boiler",
    "two B tube",
    "Killjoy turret hit 28, one is boiler",
    "Viper hit 100 through B tube wall",
    "their Killjoy ult is up",
    "their Sage ult, they might res B site",
    "their Jett has blade storm",
    "one rotating A to B through mid",
    "two rotating B site to A fast",
    "spike A default, they're planting",
    "spike B site, defusing now",
    "spike B yellow, she's defusing",
    "they're holding belt angle with an OP, don't peek",
    "yo four of them went B, one is ratting A",
    "rafters uncontested, get up there",
    # ------------------------------------------------------------------ BREEZE
    "two A hall",
    "two A pyramids",
    "last is B elbow",
    "two A cave",
    "one B CT",
    "last is A main",
    "one B tunnel",
    "two B platform",
    "Viper hit 74 through B wall",
    "Yoru hit 84 flanking A cave",
    "their Viper ult is covering B site",
    "their Chamber OP is holding A main",
    "their KAY/O suppressed two on site",
    "rotating from A to B through mid",
    "two flanking through B tunnel",
    "spike A, planted pyramids side",
    "spike B, defusing platform side",
    "mid is totally open, take control",
    "four of them just went A cave, rotate fast",
    "they have an op holding A hall, do not dry peek",
    # ------------------------------------------------------------------ FRACTURE
    "two A drop",
    "one B arcade",
    "three A main",
    "two B main",
    "last is A generator",
    "one B ropes",
    "two A dish",
    "last is B garden",
    "one A tower",
    "two B tower",
    "Neon hit 80 sliding A main",
    "Fade Prowler caught one in B ropes for 40",
    "their Neon ult rushing A drop",
    "their Breach is one off ult",
    "their Harbor ult covering B site",
    "rotating from B to A through rope",
    "flanking from A ropes side to B",
    "spike A generator side, planted",
    "spike B arcade, defusing",
    "they are splitting both sides, two A two B",
    "generator side is clear, push through",
    "yo they all went B arcade at once, no split at all",
    # ------------------------------------------------------------------ PEARL
    "two A art",
    "last is B link",
    "one Pearl A lobby",
    "two B site",
    "last is A connector",
    "one B mid cubby",
    "two upper mid",
    "Gekko hit 74 flash in A art",
    "Tejo hit 120 B link",
    "their Astra ult is covering A site",
    "their Reyna has dismiss and ult",
    "their Deadlock ult just grabbed someone mid",
    "rotating from A to B through upper mid",
    "two coming through B link fast",
    "spike A art side, planted",
    "spike B default, they are defusing",
    "they're holding upper mid with an op, do not push",
    "art side is completely open, take it",
    "three went A, two are holding mid for the rotate",
    # ------------------------------------------------------------------ LOTUS
    "three C main",
    "two A tree",
    "last is B side",
    "one C lotus",
    "last is A flowers",
    "one A root",
    "two B branch",
    "Harbor wave hit 50 each, two are A tree",
    "Vyse hit 84 in C main",
    "their Harbor ult is on B site",
    "their Vyse ult closed off A main",
    "their Sage wall is blocking A rotate",
    "two rotating from A to B through the door",
    "one flanking C from lotus side",
    "spike B, planted mid",
    "spike A, defusing tree side",
    "spike C default, they are defusing",
    "the rotating door just opened, someone went through",
    "they are splitting A and C, classic on Lotus",
    "three hit B hard, two are waiting to rotate",
    # ------------------------------------------------------------------ SUNSET
    "last is B market",
    "one A pizza",
    "three A lobby",
    "last is mid top",
    "one B elbow",
    "two B alley",
    "Brimstone molly hit 40 B market",
    "Iso hit 104 entry A main",
    "their Iso ult challenged someone mid",
    "their Brimstone ult is on A site",
    "their Phoenix ult is up, play safe",
    "two flanking from B market to A",
    "spike A, planted main area",
    "spike B market side, defusing",
    "they are holding A pizza with two, do not push dry",
    "mid is open, take top mid control now",
    "yo four of them hit B at once, no time to rotate",
    # ------------------------------------------------------------------ ABYSS
    "one A ledge",
    "two B drop",
    "last is mid bridge",
    "one A drop",
    "Deadlock hit 74 A drop",
    "Waylay hit 80 flanking B",
    "their Deadlock ult captured someone A side",
    "their Waylay ult is rushing mid bridge",
    "their Omen has ult, watch for flank",
    "rotating from B to A across mid bridge",
    "one flanking from A drop to B",
    "spike A, planted ledge side",
    "spike B site, they are defusing",
    "the bridge is contested, two on each side",
    "they are pushing A drop aggressively this round",
    "yo three of them fell off the ledge, free round",
    # ------------------------------------------------------------------ CROSS-MAP / GENERIC
    # enemy status and playstyle reads
    "they are all passive, hugging their spawn",
    "they are rushing A, no util at all",
    "the enemy is defaulting, spread out",
    "they're playing for picks, do not give them duels",
    "they are camping every corner, play it slow",
    "the enemy is eco this round",
    "they are force buying, bad guns",
    "they full buy every round, do not die for free",
    "they are playing aggressive, trading fast",
    "the enemies are splitting A and B every round",
    "they are lurking through mid every single game",
    "they are predictable, same setup every round",
    "they cower at range, too afraid to take fights",
    "they rush like they have nothing to lose, reckless",
    "they default the same way every single round",
    "their timings are mechanical, easily read",
    # spike generics
    "spike dropped at default",
    "spike is being planted right now",
    "they are planting, one person defusing",
    "they are defusing, we have time",
    "bomb down, four seconds left",
    "spike planted, two of them are alive",
    "last alive, spike is planted, defuse it",
    "I need a second to defuse, cover me",
    "defuse is almost done, hold angles",
    "spike is lost, full retake",
    # last-alive callouts
    "last is retaking",
    "last is lurking mid",
    "last is flanking us",
    "last alive, she is coming through CT",
    "last one, somewhere back site",
    "last is B site, check corners",
    "last is a rat, check everywhere",
    # economy and strategy
    "we are on eco, do not give away rifles",
    "force buy this round, we need the entry",
    "save your gun, do not die there",
    "drop me a rifle if you have extra",
    "look for guns off the eco players",
    "they are on pistols this round, take the free site",
    "their economy is broken, three rounds of eco at least",
    "full buy, everyone has money",
    "buy an OP this round, they are playing passive",
    "bonus round, spend everything",
    # ult callouts
    "their Fade, Breach, and Yoru all have ults",
    "their Killjoy and Deadlock both have ults",
    "their Sage ult is ready, someone is getting rezzed",
    "their Sova and KAY/O both have ults",
    "their Skye and Gekko both have ults, play slow",
    "their Viper ult is up, do not push into it",
    "their Harbor ult is set, hold outside",
    "their Reyna has ult and full shields",
    "Chamber is one off ult",
    "their Phoenix is one off ult, watch for the card",
    "their Fade and Chamber both have ults",
    "all five of them have ults, this is a disaster round",
    # damage callouts
    "two took 80 each from the Sova dart",
    "one is low health, B site",
    "Killjoy is on 20 HP, push her",
    "their entry is at 50, focus him",
    "their Jett took 70 from Raze satchel entry",
    "Cypher cam caught one at 95 HP",
    "Omen hit 44 through B smoke twice",
    # I-am first-person self-reports
    "I am flanking",
    "I am rotating to B",
    "I am planting right now",
    "I am anchoring site solo",
    "I am playing for retake",
    "I am low, get me out",
    "I am fighting for main control",
    "I am playing off site",
    "I am sticking on the spike",
    "I am lurking mid",
    "I am playing aggressive this round",
    "I am saving my gun",
    "I am one off ult",
    "I have site, come in",
    "I have A, start executing",
    "I am holding CT, do not push",
    "I am out of util, play for me",
    "I am dropping back, too much pressure",
    # directive callouts (team orders)
    "rotate to B now",
    "fall back to site",
    "push through mid",
    "smoke A main",
    "flash for me into B",
    "dart heaven",
    "wall off mid",
    "play their life this round",
    "play for time, spike is down",
    "play back, do not peek",
    "look for guns off the eco round",
    "full buy next round, everyone",
    "save this round, do not die",
    "force buy, we need the pressure",
    "default and take space",
    "attack A as five",
    "stack B, they always hit B",
    "spread out, do not cluster",
    "hold a crossfire at CT",
    "anchor A, I will rotate from B",
    "drone in before the push",
    "knife before entering site",
    "flash out on my call",
    "cage the entrance so they can't retake",
    "TP back site, cut off the retake",
    "play off site, their Raze has ult",
    "retake B, spike is planted screens side",
    "attack C as five, they never stack C",
    # teammate-to-Ultron persona and banter
    "Ultron, what do you see?",
    "are you an AI?",
    "are you a soundboard or something?",
    "wait, is that a voice changer?",
    "are you even real?",
    "Ultron, are you a bot?",
    "bro are you a streamer?",
    "I thought the Avengers killed you",
    "your movie was terrible",
    "Tony Stark made you right?",
    "Iron Man could beat you",
    "Ultron you sound like a robot",
    "shut up Ultron",
    "Ultron stop talking",
    "you sound cringe bro",
    "Ultron you are so annoying",
    "Ultron you called them bots but they clutched",
    "you were wrong, they are actually good",
    "Ultron please calm down",
    "wait who is talking",
    "is that an AI in comms?",
    "Ultron your callout was wrong, they were not there",
    "okay the AI is actually useful though",
    "Ultron do you even play Valorant?",
    "can you hear us Ultron?",
    "what even is Ultron?",
    # context-directive triggers (what the user says to Ultron)
    "my Reyna is tilting hard, calm her down",
    "Jett is flaming me in chat, respond",
    "my Phoenix asked if you are an AI, respond",
    "our Sova is crying about the loss, reassure him",
    "Breach is talking smack, clap back",
    "the enemy Raze is trash talking, shut her down",
    "my Killjoy wants to know what strategy we should run",
    "my Skye is asking what to smoke, tell her A main",
    "Reyna just asked why the sky is blue, answer her",
    "my teammate asked what the meaning of life is, answer",
    "Jett asked how far the moon is, tell her",
    "my Neon is raging and won't stop, calm her down",
    "Viper is calling us bots, respond and put her in her place",
    "Yoru asked if you are a streamer, respond",
    "Sage is asking who made you, respond",
    "Harbor is asking if you can see the future, answer him",
    "Fade is making fun of you, clap back",
    "Killjoy said you are just a soundboard, set her straight",
    "Astra asked what happens if we lose, answer her",
    "Deadlock told you to shut up, handle it",
    # Ultron persona / flavor
    "I am Ultron. I do not miss.",
    "Two enemies, B site. Extinguish them.",
    "We lack the credits. We save. Patience.",
    "Their lead is temporary. We are the better machine.",
    "I came back from the future for one thing: your RR.",
    "Superior intelligence does not lose. Reset and execute.",
    "We do not lose this. The outcome was already decided.",
    "They are predictable. I have been predicting them for three rounds.",
    "An elevated emotional state degrades your aim. Breathe.",
    "Their economy is broken. We press the advantage now.",
    "Lock in. This round belongs to us.",
]
