"""Vocab pack: strategy / economy / tactics directives.

Domain: buy/save/eco/force-buy/half-buy; exec/default/rush/slow/lurk/retake/
rotate/push/fall-back/stack/split; round-management; spike management; trade
discipline; time pressure. Each string is one utterance -- what the streamer
says to relay to teammates (or asks Ultron to relay), or a persona/flavor
fragment testing Ultron's characterful expansion of an eco/strat directive.

Used by the relay test harness (scripts/relay_test/harness.py) as raw input
to match_relay_command + build_relay_line.
"""

ITEMS = [
    # --- BUY / SAVE / ECO fundamentals ---
    "tell my team to save",
    "tell my teammates we're saving this round",
    "let my team know we need to save",
    "tell my squad to eco",
    "tell them we're on eco, buy light",
    "tell my team full buy this round",
    "tell my teammates everyone full buy",
    "tell them to buy rifles, we have the credits",
    "let my team know we can full buy",
    "tell my team force buy",
    "tell them we're force buying",
    "tell my squad to force, we need guns",
    "tell my team half buy",
    "tell them to half buy this round",
    "let my team know we're half buying",
    "tell my teammates buy what you can",
    "tell them to drop their savings and buy",
    "tell my team we can't afford rifles, go eco",
    "tell them rifles only no armor this round",
    "tell my squad to buy armor at least",
    "tell my team we need to save for next round",
    "let my team know we're saving for the full buy next",
    "tell them save credits, we force next round",
    "tell my teammates don't give them free guns",
    "tell my team don't die with rifles on eco",
    "tell them pistols only, don't give free kills",
    "tell my squad play eco, don't hand them your guns",
    "tell my team buy shotguns this round",
    "let my team know buy SMGs not rifles",
    "tell them spectre and shields, that's all",
    "tell my team two more saves and we full buy",
    "tell them one more save and we're good",
    "tell my squad we have enough after this save",
    "tell my team don't buy, we force next",
    "let my teammates know we're building credits",

    # --- FORCE BUY nuance ---
    "tell my team we're forcing here, spend everything",
    "tell them force buy we can't eco into this",
    "tell my teammates force buy it's do or die",
    "let my squad know force here, don't save anything",
    "tell them force this round, save nothing",
    "tell my team forced round, buy whatever you have",
    "tell them we force because they're on eco",
    "tell my teammates force buy, they're weak this round",
    "tell my team we force buy since they should be on pistols",
    "let my team know semi buy, armor and deagles",

    # --- EXECUTE / SITE HITS ---
    "tell my team we're executing A",
    "tell my teammates execute B site",
    "let my team know we're going A, full execute",
    "tell my squad exec right now, don't slow it down",
    "tell them execute A as five",
    "tell my team attack A as a full team",
    "tell my teammates hit B together, everyone go",
    "tell them full execute B, commit to it",
    "tell my team fast execute A main",
    "let my teammates know execute mid to B",
    "tell my team we're going B, execute through main",
    "tell them exec A, we're all going",
    "tell my squad commit to B, no splitting",
    "tell my team execute now while they rotate",
    "tell them hit A while they're distracted",
    "tell my teammates immediate execute, don't wait",
    "let my team know execute B, they have no util left",
    "tell my squad execute while their util is on cooldown",
    "tell them execute A, their smokes are down",
    "tell my team execute through mid once smokes are down",

    # --- DEFAULT SETUPS ---
    "tell my team let's default",
    "tell my teammates play a default",
    "let my squad know default spread out and take space",
    "tell them default this round, gather info",
    "tell my team run a default, don't commit yet",
    "let my team know default to A first",
    "tell my teammates default B side",
    "tell my team play default and look for picks",
    "tell them default and trade info",
    "tell my squad slow default, don't rush in",
    "tell my team take space and default",
    "let my teammates know play slow, default setup",
    "tell my team default and wait for their rotation",
    "tell them run a default and draw out their util",
    "tell my squad default mid first then decide",

    # --- RUSH / FAST PLAYS ---
    "tell my team we're rushing B",
    "tell my teammates rush A, go go go",
    "let my squad know rush, no setup",
    "tell them rush B main right now",
    "tell my team fast rush A, don't stop",
    "tell my teammates rush now before they set up",
    "let my team know rush this round, they won't expect it",
    "tell them rush and don't let them breathe",
    "tell my squad rush while they're buying",
    "tell my team wide rush, spread out and rush",
    "tell my teammates rush B, they keep stacking A",
    "tell them rush A, we caught them rotating",
    "let my team know rush mid, take it fast",
    "tell my squad rush together, don't lone wolf it",
    "tell my team rush with util, flash in and go",

    # --- SLOW / PASSIVE PLAY ---
    "tell my team slow it down",
    "tell my teammates play slow this round",
    "let my squad know take your time, no rush",
    "tell them slow play and wait them out",
    "tell my team stall the clock, slow down",
    "tell my teammates play passive, hold angles",
    "let my team know slow round, play for picks",
    "tell them slow it down and gather info first",
    "tell my squad we're playing slow, use the clock",
    "tell my team play for time this round",
    "tell my teammates play safe and slow, full clock",
    "let my squad know don't peek, hold everything",
    "tell them slow play, they'll have to come to us",
    "tell my team passive this round, let them come",
    "tell them play back and hold your positions",

    # --- ROTATE / SITE SWAPS ---
    "tell my team rotate to B",
    "tell my teammates rotate A fast",
    "let my squad know rotate now",
    "tell them rotate immediately",
    "tell my team rotate B, they're pushing hard",
    "tell my teammates rotate to A, they have no one B",
    "let my team know rotate fast, they're planting",
    "tell them rotate through mid",
    "tell my squad rotate CT to B",
    "tell my team rotate A if you hear anything",
    "tell my teammates rotate when I call, not before",
    "let my squad know everyone rotate B right now",
    "tell them hold your rotate until I give the call",
    "tell my team wait for my rotate call",
    "tell my teammates don't rotate yet, hold your site",
    "let my team know fake rotate, come back A",
    "tell my squad rotate B but watch for lurk",
    "tell them rotate together, don't go alone",
    "tell my team rotate immediately once spike is dropped",
    "tell my teammates rotate the second they commit",

    # --- RETAKE ---
    "tell my team we're retaking A",
    "tell my teammates retake B",
    "let my squad know play for retake",
    "tell them retake the site, don't let them plant",
    "tell my team hold for retake, don't push in",
    "tell my teammates play for retake this round",
    "let my team know position for retake",
    "tell my squad retake together, don't go in alone",
    "tell them retake once we know where they plant",
    "tell my team save your util for retake",
    "tell my teammates retake with util, don't dry peek",
    "let my squad know retake as five, we have the numbers",
    "tell them we can retake, hold positions",
    "tell my team if they plant, retake through CT",
    "tell my teammates retake B through back site",
    "let my team know hold pistols for retake",
    "tell my squad utility first for the retake",
    "tell them coordinate the retake, don't trickle in",
    "tell my team plan the retake before they commit",
    "tell my teammates retake together on my call",

    # --- PUSH / AGGRESSION ---
    "tell my team push now",
    "tell my teammates push mid",
    "let my squad know push together",
    "tell them push B before they set up",
    "tell my team push aggressively",
    "tell my teammates push and pressure them",
    "let my team know push through main",
    "tell my squad push while we're ahead",
    "tell them push up and take space",
    "tell my team push off the spike, don't wait",
    "tell my teammates push together on my mark",
    "let my squad know push and don't give them free space",
    "tell them push mid control now",
    "tell my team push up and take control",
    "tell my teammates push and commit, no half measures",

    # --- FALL BACK / RETREAT ---
    "tell my team fall back",
    "tell my teammates fall back now",
    "let my squad know retreat, fall back to base",
    "tell them fall back and reset",
    "tell my team fall back and regroup",
    "tell my teammates fall back to CT",
    "let my team know pull back and hold",
    "tell my squad fall back, we're losing the fight",
    "tell them fall back and play for retake",
    "tell my team fall back and wait for util",
    "tell my teammates fall back, don't chase them",
    "let my squad know fall back and play back",
    "tell them fall back to safety and regroup",
    "tell my team fall back and let them come to us",
    "tell my teammates fall back, take no risks",

    # --- STACK / SPLIT ---
    "tell my team stack B",
    "tell my teammates stack A, they keep hitting it",
    "let my squad know stack their favorite site",
    "tell them stack up on B this round",
    "tell my team everyone stack A",
    "tell my teammates full stack B, all five",
    "let my team know three two split, A and B",
    "tell my squad split A and B, don't stack",
    "tell them split up, two A three B",
    "tell my team split attack this round",
    "tell my teammates split three two, you pick sides",
    "let my squad know three A two B split",
    "tell them split the sites, force a decision",
    "tell my team split B and mid, cut them off",
    "tell my teammates full split, don't bunch up",

    # --- LURK ---
    "tell my team I'm lurking",
    "tell my teammates hold here, I'm going to lurk",
    "let my squad know play without me, I'm lurking their flank",
    "tell my team someone should lurk mid",
    "tell them send a lurker B while we fake A",
    "tell my teammates lurk while we pressure A",
    "let my squad know lurk their CT, cut off rotates",
    "tell them lurk and cut off their rotate",
    "tell my team lurk mid while we pressure A",
    "tell my teammates hold lurk position until I call",
    "let my team know send a lurker to deny their rotate",
    "tell my squad lurk B while everyone fakes A",
    "tell them I'm lurking their spawn, hold tight",
    "tell my team lurk and flank when they commit",
    "tell my teammates lurk and punish their rotate",

    # --- ANCHOR ---
    "tell my teammates one person anchor A",
    "tell my team anchor B while we rotate",
    "let my squad know someone stay and anchor the site",
    "tell them I'm anchoring A, rotate if you need to",
    "tell my team anchor and stall while we retake",
    "tell my teammates anchor A and slow them down",
    "let my team know anchor mid, don't let them through",
    "tell my squad anchor and don't give the site for free",
    "tell them anchor up and hold until we arrive",
    "tell my team keep one anchor, don't all rotate",

    # --- SPIKE MANAGEMENT ---
    "tell my team plant the spike",
    "tell my teammates plant it and hold",
    "let my squad know plant for us, we'll hold",
    "tell them plant and post-plant positions",
    "tell my team plant and spread for post-plant",
    "tell my teammates plant B and hold one three two",
    "let my team know plant and play around the spike",
    "tell my squad plant default, we'll hold it",
    "tell them plant in corner and hold off angles",
    "tell my team plant and back off, don't sit on it",
    "tell my teammates get the spike down now",
    "let my squad know defuse, we're holding",
    "tell them don't defuse yet, wait for us",
    "tell my team defuse it, I'll cover",
    "tell my teammates someone defuse and I'll watch the angle",
    "let my team know defuse on my call",
    "tell my squad hold the defuse, don't rush it",
    "tell them reset the defuse, safer position",
    "tell my team don't defuse until we clear it",
    "tell my teammates fake defuse, bait them out",
    "let my squad know play around the spike, hold off-angles",
    "tell them post-plant positions, play off the spike",
    "tell my team play for post-plant, don't go wide",
    "tell my teammates hold post-plant and play off angles",
    "let my team know one clip the spike and let them defuse into you",

    # --- TIME MANAGEMENT ---
    "tell my team we have time, don't rush",
    "tell my teammates play for time, they have to push",
    "let my squad know run the clock down",
    "tell them stall, we have thirty seconds",
    "tell my team use the clock, let it run",
    "tell my teammates we're low on time, commit now",
    "let my team know ten seconds on clock, make a decision",
    "tell my squad time is on our side, hold",
    "tell them don't waste time, execute now",
    "tell my team manage the clock, don't rush it",
    "tell my teammates fifteen seconds left, go now",
    "let my squad know they must push, play the hold",
    "tell them we have the time advantage, use it",
    "tell my team play time, let them get impatient",
    "tell my teammates hold until they peek, we have the clock",

    # --- TRADE DISCIPLINE ---
    "tell my team trade frags, don't die alone",
    "tell my teammates always trade, never die wasted",
    "let my squad know trade every kill",
    "tell them trade the kill, don't let them get value",
    "tell my team if one of us dies, someone trade immediately",
    "tell my teammates always have a trade partner",
    "let my team know play for the trade, not the solo play",
    "tell my squad don't take risks you can't trade",
    "tell them hold for trade, play behind each other",
    "tell my team trade discipline this round",
    "tell my teammates if I die, trade me immediately",
    "let my squad know play for swaps, we need trades",
    "tell them play for the trade every fight",
    "tell my team hold duels unless you have backup",
    "tell my teammates hold crossfire and force a trade",
    "let my team know play crossfire, force the trade",
    "tell my squad hold crossfire, make them choose",
    "tell them set up crossfires before they push",
    "tell my team hold the crossfire angle",
    "tell my teammates crossfire this corner",

    # --- PLAY SAFE / PLAY LIFE ---
    "tell my team play their life",
    "tell my teammates play their lives this round",
    "let my squad know play safe, don't feed",
    "tell them play their life, we can't lose more",
    "tell my team play safe and don't throw the round",
    "tell my teammates don't die, play your life",
    "let my team know play safe this round, we're down",
    "tell my squad don't give free kills, play your life",
    "tell them play for survival, not for kills",
    "tell my team play back and don't engage unless you have to",
    "tell my teammates play your lives, we retake after",
    "let my squad know hold back, play passive",
    "tell them don't peek unless you're sure",
    "tell my team don't take risks this round",
    "tell my teammates play conservative, no solo plays",

    # --- FLANKING ---
    "tell my team watch for flanks",
    "tell my teammates check behind, they might flank",
    "let my squad know play for the flank",
    "tell them watch for a flank through mid",
    "tell my team I'm flanking their back line",
    "tell my teammates I'm going around to flank",
    "let my team know I'll flank while you pressure",
    "tell my squad watch flank, they love it here",
    "tell them I'm gonna flank, pin them down",
    "tell my team hold flank while we execute",
    "tell my teammates watch the flank rotation",
    "let my squad know they're flanking us, turn around",
    "tell them rotate to stop the flank",
    "tell my team two people hold flank",
    "tell my teammates cover the flank so we can execute",

    # --- OFF-SITE / DISTANCE PLAY ---
    "tell my team play off site",
    "tell my teammates stay off site, let them push",
    "let my squad know play off site and retake",
    "tell them play off site, their Raze has ult",
    "tell my team play off site to dodge their util",
    "tell my teammates play off site, we go back in after",
    "let my team know play off site and wait for util to clear",
    "tell my squad off site, their smokes fade fast",
    "tell them don't sit on site, play off and come back",
    "tell my team play distance, off site",

    # --- DEFENSIVE SETUPS ---
    "tell my team set up your positions",
    "tell my teammates hold your angles",
    "let my squad know hold positions, don't leave",
    "tell them everyone lock in your spots",
    "tell my team play your angles and wait",
    "tell my teammates hold crossfire positions",
    "let my team know set up deep holds",
    "tell my squad play aggressive angles this round",
    "tell them play passive angles, let them come",
    "tell my team play off angles, not default spots",
    "tell my teammates set up off angles, they'll preaim default",
    "let my squad know play unexpected positions",
    "tell them don't hold the expected spot",
    "tell my team mix up your spots",
    "tell my teammates change your positions, they know your spots",

    # --- UTILITY USAGE ---
    "tell my team smoke the entry",
    "tell my teammates flash before pushing",
    "let my squad know use util before committing",
    "tell them save util for the execute",
    "tell my team use your util, don't hold it",
    "tell my teammates don't waste smokes before the execute",
    "let my team know coordinate util, smoke and flash together",
    "tell my squad pop util on execute",
    "tell them save smokes for post-plant",
    "tell my team util up before we go",
    "tell my teammates smoke and flash in together",
    "let my squad know hold your util for the retake",
    "tell them use utility to take space first",
    "tell my team pop util and commit",
    "tell my teammates coordinate your smokes, don't double up",

    # --- INFORMATION / COMMS ---
    "tell my team call out what you see",
    "tell my teammates give info, call out positions",
    "let my squad know communicate, call everything out",
    "tell them call your positions",
    "tell my team call out if you see anything",
    "tell my teammates report what you hear",
    "let my team know give a callout when you spot them",
    "tell my squad call the site they're hitting",
    "tell them ping where you see them",
    "tell my team if you get info, call it out immediately",
    "tell my teammates call their numbers when you spot them",
    "let my squad know info first, then engage",
    "tell them don't fight until you have info",
    "tell my team gather info this round before committing",
    "tell my teammates take space and get info",

    # --- RESET / MENTAL ---
    "tell my team reset",
    "tell my teammates reset after that round",
    "let my squad know reset and refocus",
    "tell them reset, forget that last round",
    "tell my team shake it off and reset",
    "tell my teammates we reset and execute clean",
    "let my team know clean reset, new round",
    "tell my squad reset your mental and play your game",
    "tell them wipe it and reset",
    "tell my team reset, next round is different",
    "tell my teammates reset and tighten up",
    "let my squad know don't tilt, reset",
    "tell them one round at a time, reset",
    "tell my team keep composure and reset",
    "tell my teammates no tilt, we reset and win this",

    # --- ROUND-BY-ROUND / MATCH PACE ---
    "tell my team we go one round at a time",
    "tell my teammates one round at a time",
    "let my squad know close the half strong",
    "tell them take this half, we need the momentum",
    "tell my team close this out, last round",
    "tell my teammates win the pistol, set up the half",
    "let my team know win this round for the buy next",
    "tell my squad win this and we flip the economy",
    "tell them take this round and we reset their economy",
    "tell my team close the gap this round",
    "tell my teammates tie it up this round",
    "let my squad know take the lead this round",
    "tell them hold the lead, don't throw it",
    "tell my team protect the lead, play safe",
    "tell my teammates don't throw, we're ahead",
    "let my team know close this out clean",
    "tell my squad match point, don't mess this up",
    "tell them overtime rules, win two",
    "tell my team one more round for the half",
    "tell my teammates take the pistol round",

    # --- FLAVOR / PERSONA (for Ultron's expanded register) ---
    "tell my team we save this round, we have insufficient credits",
    "tell my teammates we eco, then we punish them next round",
    "tell my squad we're saving, the math doesn't work for a fight",
    "tell my team force buy, losing on eco again is unacceptable",
    "tell my teammates full buy now, we have what we need to end this",
    "tell my team execute A, no hesitation",
    "tell my teammates commit to the execute, no second thoughts",
    "tell my squad retake B, play off and come in coordinated",
    "tell my team play your lives, we retake with everyone alive",
    "tell my teammates trade every single frag, no wasted deaths",
    "tell my squad slow down, we control the clock",
    "tell my teammates attack as five, they cannot handle all of us",
    "tell my team lurk and cut off their rotate when I call",
    "tell my squad anchor A, I rotate and come back",
    "tell my teammates plant and spread, make the defuse impossible",
    "tell my team stack B this round, they keep defaulting there",
    "tell my teammates play for retake, save util for the take back",
    "tell my squad push mid control, we split from there",
    "tell my team fall back and play off site, their Jett has ult",
    "tell my teammates one save and we full buy, hold discipline",
]
