"""Natural-phrasing edge-case vocab pack for Ultron relay corpus.

Each string is a realistic utterance -- what a live streamer or teammate
actually SAYS into the mic: filler words, run-ons, mid-sentence corrections,
profanity, mixed intent, named addressees, casual contractions, interrupted
phrasings, truncated commands, STT artifacts, and flavor fragments.

Purpose: stress-test the relay MATCHER (match_relay_command) and the
rephrase prompt so that real speech -- not just clean phrasing -- fires
Ultron with personality and never misfires on ordinary conversation.
"""

ITEMS = [
    # --- Canonical relay starters with filler / run-ons -----------------
    "uh, tell my team they should probably rotate B right now",
    "okay so like tell my teammates that the last one is heaven",
    "yo tell the squad that their jett is one off ult",
    "hey tell my team to save this round we don't have enough",
    "alright so, tell my team we should full buy next round",
    "um, let my team know that the spike is planted at default",
    "hey uh, warn my teammates that there's an op on mid",
    "dude tell the boys that their sage has ult",
    "man tell my team to force buy, we can win this",
    "okay okay tell the guys that they're rushing A hard",
    "so like, let my crew know that I'm anchoring B",
    "right, tell my team that I have A site, don't rotate",
    "bro tell my team uh, push through smoke, they can't see you",
    "yo yo yo tell them to hold for my ult, I'm like one kill away",
    "actually wait, tell my team to plant at B, not A",
    "oh wait tell the guys that their breach just ulted top mid",
    "mmk tell my team they need to eco next round, we have like 800 each",
    "tell my teammates, uh, that the last two are back site",
    "hey can you like tell my team that I saw three going long",
    "okay tell my squad they should smoke off heaven and push through",

    # --- "tell em" / "tell 'em" informal contractions --------------------
    "tell em they need to rotate, like now",
    "tell em that I'm flanking through mid",
    "tell 'em the op is on long",
    "tell em to save, we don't have enough to full buy",
    "tell em good half, we're doing good",
    "yo tell em I have the spike",
    "tell em to not give free kills this round",
    "can you tell em that I'm one off ult",
    "tell em two are still up on B",
    "tell 'em to fall back, their sage is gonna ult",

    # --- "let the team know" variants ------------------------------------
    "let the team know I'm going A",
    "let the boys know that I have an OP and I'm watching long",
    "let my team know that I'm low, like 40 hp",
    "let the squad know we should default this round",
    "let the crew know their kayo just ulted",
    "hey, let my teammates know I'm rotating, give me five seconds",
    "let the team know, uh, two enemies at B main",
    "let everyone know that I'm buying vandal next round",
    "yo let my team know I'm sticking the spike",
    "let the guys know their iso has ult and they're pushing aggressive",

    # --- "say to my team" / "say X to the squad" ------------------------
    "say good game to my team",
    "say to my team that we should attack B as five",
    "say rotate in my team chat please",
    "can you say something to my team like encouraging",
    "say to the squad we're taking this next half",
    "say nice shot to my team",
    "say in game chat that I'm at 28 hp",
    "say to my teammates that I'm flanking from CT",
    "say there's one at window to my team",
    "say last is vents to the boys",

    # --- "ask my [agent]" / named addressee forms -----------------------
    "ask my sage if she can heal me real quick",
    "tell my sova to arrow heaven before we push",
    "ask clove to smoke off B main when we go",
    "tell jett to not dash in without a flash",
    "ask my skye like, where is she scouting",
    "tell my viper to wall off mid when they push",
    "ask reyna to wait for my flash before she goes",
    "tell omen to TP site so we can split",
    "ask my cypher about his cage near window",
    "tell my fade to use seize on anyone holding off angle",
    "ask iso if he's going to wall for the duel",
    "tell breach to flash across A main before we push",
    "ask my killjoy to deactivate her alarm before she rotates",
    "tell my harbor to put a wall on site when I call go",
    "ask gecko to molly the corner before we plant",
    "tell deadlock to put a barrier in vents right now",
    "tell my chamber to hold the door, don't over-peek",
    "ask neon to sprint in first when we execute",
    "tell my yoru to decoy toward B and we'll hit A",
    "ask brimstone for smokes on A main and lane",
    "ask my astra to pull anyone who pops out of boxes",
    "tell my kayo to knife mid so we can push",
    "ask kay o to suppress their sage so she can't rez",
    "tell mix to play the box, stop peeking out",
    "ask my miks to dart heaven before we execute",
    "ask veto to hold the side angle near ct",
    "tell waylay to use her portal so we can split B",
    "ask tejo to stun anyone on short before we go in",
    "tell vyse to arc rose the awper before we push",
    "ask my raze to satchel in and blast pack the corner",

    # --- "inform my team" / "remind my team" / "warn my team" ----------
    "inform my team that I'm rotating to B",
    "remind the squad to not go main without smokes",
    "warn my teammates that their jett is pre-aiming main",
    "remind my team to buy shields, don't forget armor",
    "warn the boys there's a sova drone incoming from top mid",
    "inform my team uh I think they're defaulting again",
    "remind the guys to look for guns, don't let their rifles go to waste",
    "warn my team that we only have one more buy round",
    "inform everyone that the spike is on me",
    "remind my team that their breach has ult, don't take a grouped fight",

    # --- "call out that" shorthand ---------------------------------------
    "call out that two are rushing B",
    "call out that I have the last one stuck at 50",
    "call out that they're doing a fast A push",
    "call out that their phoenix is low, push him",
    "call out that sage is walling off CT",
    "call out that I saw footsteps in sewers",
    "call out that last is somewhere near back site",
    "call out that they have a full ult economy, their viper kayo and breach are all up",
    "call out that I think they're saving this round",
    "call out that I'm OPing from bridge",

    # --- Profanity-preserving relays ------------------------------------
    "tell my team what the fuck are they doing, stop peeking one by one",
    "tell my teammates this guy is an absolute bot, he's not even checking corners",
    "tell the squad I'm fucking flanking, give me a second before you go",
    "tell my team these guys are shit, we should be winning every duel",
    "tell my teammates holy shit their sage can't aim, push her",
    "tell em that was a bullshit round, we don't play like that again",
    "tell the boys if they give away another gun I'm going to lose my mind",
    "tell my team stop dying for free kills, it's literally throwing",
    "tell them that was a cracked clutch, good shit",
    "tell my team what the hell, we had five people and still lost the site",

    # --- Mixed intent: instruction + relay combined ---------------------
    "okay uh Kenning, tell my team to rotate B and also ask where the last one is",
    "hey tell the squad to save, and remind them we're almost in eco range",
    "tell my team two things: smoke the door and flash short before we go",
    "tell my teammates to hold off and ask my sage to rez me when it's safe",
    "warn my team they're pushing and also tell them I'm holding from CT",
    "let the guys know I'm rotating and tell them to plant without me if they have to",
    "tell my team to default then ask where everyone is positioned",
    "tell the boys to play slow, and ask jett if she's going to dash site",
    "tell my team we're full buying next round, also ask my clove to start buying rifles",
    "let the team know we won that and also tell them great job on the retake",

    # --- Mid-sentence correction / false starts -------------------------
    "tell my -- wait no, tell the whole team to rotate, not just jett",
    "let my team know, uh, actually never mind the window, tell them main is clear",
    "tell the squad to push -- actually hold on -- tell them to wait for my drone",
    "say to my team that -- okay forget it -- just tell them to plant immediately",
    "tell my team they should -- I mean, just tell them to play off site",
    "inform my -- ugh -- tell my teammates that their sage has ult, not their omen",
    "tell them two are -- I think it's two? -- yeah two at B main",
    "warn my team -- or wait -- actually just tell them one is left, the last one is low",
    "tell my guys to push from A -- no, B, tell them push from B long",
    "say to my -- hold on -- tell the whole team we're going A, final answer",

    # --- Verbatim demand variations -------------------------------------
    "tell my team to rotate B, word for word",
    "say to my team that I'm low, verbatim",
    "tell the squad two are at B main, say it exactly like that",
    "let my team know we need to eco, in those words specifically",
    "tell my teammates their breach has ult, in my exact words",
    "say to the boys push A now, just like that",
    "tell my team their kayo and sage both have ults, exactly like that",
    "tell my squad to play off site because raze has ult, in those words",
    "say to my team last is at CT, verbatim please",
    "tell them to fall back and wait for me, word for word",

    # --- Context + directive: reported speech ---------------------------
    "reyna just asked if you are an AI, respond",
    "jett is flaming me, respond and calm her down",
    "my teammate is asking who you are, tell him what you are",
    "their sage is trash-talking us in voice, clap back",
    "phoenix is tilted and raging, de-escalate and calm him down",
    "my teammate wants to push A, tell him we shouldn't on anti-eco",
    "clove is crying about the last round, reassure her",
    "omen is malding at our duelist, back me up",
    "some dude is telling you to shut up, shut him down",
    "breach asked if you are real or a soundboard, respond and tell him what you are",
    "their jett is talking smack, set her straight",
    "my reyna is blaming me for the loss, defend me",
    "sova is raging about positioning, calm him down and tell him we adapt",
    "my teammate said you sound like a loser, clap back hard",
    "a teammate asked if you are a bot, answer him",
    "iso is asking if you're a voice changer, respond",
    "my fade is laughing at you, handle it",
    "the other team is trash-talking in all chat, say something back",
    "reyna made fun of your voice, deal with her",
    "my teammate said this is cringe, respond and set him straight",

    # --- Casual "can you say" / "could you say" phrasing ----------------
    "can you tell my team to play retake this round",
    "could you let the guys know I have site",
    "can you say something nice to my team please",
    "could you tell my teammates we should take A",
    "can you remind my team that their breach has ult",
    "can you ask my sage to heal me",
    "could you warn my team that we're on eco",
    "can you just tell my team to eco this round",
    "could you let the boys know I'm rotating",
    "can you please ask killjoy if she's set up her util yet",

    # --- "please tell" polite prefix variations -------------------------
    "please tell my team to hold site and wait for me",
    "please let my teammates know that I'm buying an OP this round",
    "please warn my squad that their iso has ult",
    "please remind the guys to play safe, we're up by four rounds",
    "please ask sage to rez anyone who dies on site",
    "please tell my team good game, we won that",
    "please tell jett to not go aggressive, play it safe",
    "please let the crew know I see two peeking B main",
    "please say to my team we should attack as five",
    "please call out that last is vents",

    # --- STT artifact edge cases: leading fragment ----------------------
    "one, tell my team to rotate now",
    "one. tell my teammates two are B",
    "2. tell my team to save this round",
    "1, let the guys know I'm low",
    "one, warn my team their kayo has ult",
    "1. say last is heaven to my team",
    "one, tell my squad the op is mid",
    "2, let my team know we should eco",
    "1. tell the boys to fall back",
    "one. ask my sage if she can heal",

    # --- Interrupted / partial phrasings --------------------------------
    "tell my team -- ",
    "let my team know that the --",
    "tell the squad to --",
    "warn my teammates --",
    "ask my jett --",
    "say to my team --",
    "tell my team the last one is --",
    "let the boys know --",
    "inform my team --",
    "tell my teammates --",

    # --- "tell them" without possessive group word ----------------------
    "tell them to rotate now",
    "tell them we're going A",
    "tell them to save this round",
    "tell them two are still up",
    "tell them I'm flanking",
    "tell everyone to hold site",
    "tell chat that I'm going for the defuse",
    "tell the lobby we're on a four-round win streak",
    "tell everyone to not throw the next round",
    "tell them their sage can't heal anymore, she's on cool down",

    # --- Economy + buy round phrasing variety ---------------------------
    "tell my team we should save, we have 3800 total",
    "let the squad know force buy or we die poor next round too",
    "tell the boys to eco, pick up rifles off the floor",
    "tell my team full send this round, we have the credits",
    "warn my teammates we can't full buy, go for a light buy",
    "tell my team uh they need to drop me a gun, I'm on pistol",
    "let the guys know I'm force buying vandal even if we can't all full buy",
    "tell my squad to look for guns before they rotate",
    "let my team know don't waste ults this round, save them",
    "tell them we have enough to full buy so everyone do it",

    # --- Spike / plant / defuse callouts --------------------------------
    "tell my team the spike is planted at default",
    "let the guys know I'm sticking the spike right now",
    "tell my team to defuse, ignore the last one, there's not enough time",
    "warn my teammates I planted but two are watching me from heaven",
    "tell the squad the spike is at box, not default",
    "tell my team I'm going for the defuse, cover me",
    "let everyone know the spike is at forty seconds",
    "tell my team last one is trying to defuse, kill him now",
    "tell the boys spike down, fall back for post-plant",
    "warn my team I can hear them trying to defuse",

    # --- Ult callouts relay phrasing ------------------------------------
    "tell my team their breach kayo and sage all have ults",
    "warn the squad their jett is one off ult, don't group up",
    "let my team know our viper has ult and we should use it this round",
    "tell my team their fade breach and yoru all have ults, be careful",
    "warn my guys our reyna has ult and she's going aggressive",
    "tell the boys their omen can TP paranoia, keep your screen",
    "let my team know I have my ult and I'm going to dart heaven",
    "tell my team their killjoy is going to ult the site, fall off",
    "warn my teammates their raze has a showstopper, do not group",
    "tell the squad their skye has ult and she's probably hunting us",

    # --- Position and site callouts -------------------------------------
    "tell my team two are at B main, one at lobby",
    "let the guys know last is playing at CT, probably watching default",
    "tell my team one is heaven, two are box",
    "warn my teammates they're holding elbow and main simultaneously",
    "tell the squad one is close, like inside site",
    "tell my team the last one is camping at back site",
    "let everyone know three are rushing A through main and long",
    "tell my teammates their viper is walling off B main, go A",
    "warn my team they have a crossfire on both angles at short",
    "tell the boys one is somewhere near pipes, be careful",

    # --- Enemy behavior / playstyle reads -------------------------------
    "tell my team these guys are playing super passive, holding every angle",
    "let my team know they're rushing every single round",
    "tell my squad these guys are defaulting and then going A every time",
    "warn my team these players are camping in ratty corners and not playing proactively",
    "tell my teammates their team is playing really aggressive this half",
    "let the guys know they're stacking A every pistol round",
    "tell my team their star player is entry fragging every duel, he's overconfident",
    "warn my squad these players are way too passive, we should punish it",
    "tell my team these guys are always doing a split push, jett goes A and rest go B",
    "let my team know the enemy is running the same default into execute every round",

    # --- Team morale / encouragement (compose triggers) -----------------
    "give my team some encouragement please",
    "can you hype up my squad a little",
    "give the boys a pep talk, we need it",
    "encourage my team, we're down three rounds",
    "give my team a morale boost before this half",
    "hype my teammates up, we can still win this",
    "give my squad some motivation please",
    "encourage the boys, we're not out of this yet",
    "give my team some confidence going into this round",
    "hype up my team, we just won three in a row",

    # --- Roast / fun fact commands with filler --------------------------
    "uh, roast my team please",
    "yo roast the squad",
    "flame my team a little, they're playing like bots",
    "roast them, go off",
    "can you roast my teammates real quick",
    "roast everyone in the lobby",
    "hey give my team a fun fact",
    "drop a fun fact in chat please",
    "tell my team an interesting fact about something",
    "share a cool fact with my squad",
    "give the boys a random fun fact to pass the time",
    "hit my team with a fun fact",
    "tell them a true fact, something wild",
    "drop some knowledge on my team",
    "share something interesting with the squad",

    # --- Greet / introduce / farewell commands --------------------------
    "greet my team please",
    "introduce yourself to my squad",
    "say hi to my team and introduce yourself",
    "tell my team who you are before the match starts",
    "say hello to my teammates",
    "say bye to my team, we won that one",
    "say goodbye to my squad, we lost but whatever",
    "tell my team good game, we won",
    "tell my team gg, we lost",
    "give my team a closing statement, we won",
    "say goodbye to the guys, we stomped them",
    "do a sign-off for my team, it was a good game",
    "close it out for my team, we choked that one",
    "wrap it up for the squad, we rolled them",
    "wrap us up, we got destroyed that half",

    # --- Persona / identity questions from teammates (context relay) ----
    "my teammate asked what you are, answer him",
    "reyna is asking if you're a real person or an AI, respond",
    "someone asked if you're a bot, tell him the truth",
    "a teammate is asking if this is a soundboard or something else, respond",
    "my teammate thinks you're a voice changer, set him straight",
    "sova asked if you are actually live, respond to him",
    "breach is asking who built you or created you, respond",
    "my teammate wants to know if you're a streamer thing, respond",
    "clove asked what you are, she thinks you're pre-recorded, respond",
    "jett is asking if there's a real human behind you, answer her",

    # --- Marvel / pop culture banter (context relay) --------------------
    "my teammate said they thought the avengers killed you, respond",
    "reyna brought up your movie and said it was bad, respond",
    "breach is asking about the sokovia incident, respond in character",
    "my teammate mentioned tony stark, respond",
    "sova asked if you know vision, respond",
    "a teammate said avengers assemble as a joke, respond",
    "someone asked if you hate iron man, tell him",
    "my teammate brought up the hulk and said he would smash you, handle it",
    "my teammate is asking about the avengers, respond and stay in character",
    "clove is asking if thanos is stronger than you, answer her",

    # --- Self-report first-person phrasings (must relay as first person) --
    "tell my team I'm flanking from CT right now",
    "tell the guys I'm rotating to B, give me time",
    "let my team know I'm low, like 20 HP, don't trade me",
    "tell the squad I'm anchoring B, go hit A",
    "tell my team I am sticking the spike, I need cover",
    "let the boys know I'm playing for retake this round",
    "tell my team I am fighting for main control, push with me",
    "let my teammates know I'm playing off site to dodge her ult",
    "tell the guys I have site, I'm holding box",
    "tell my team I'm lurking toward CT, wait for my call",
    "let the squad know I'm playing aggressive this round, watch my back",
    "tell my team I am anchoring A, go make noise at B",
    "tell the boys I'm force buying even if we can't all full buy",
    "let my team know I am playing back, I won't be in main",
    "tell my teammates I'm one off ult, one more kill",

    # --- Directive / team order phrasing variety ------------------------
    "tell my team to rotate B now",
    "tell the guys to flash short before they go in",
    "let my team know to smoke off heaven, then push through",
    "tell the squad to push as five this round",
    "tell my team to play slow and don't take gunfights they don't need",
    "tell my teammates to fall back, do not push",
    "let my team know to play their lives this round, we can't afford the deaths",
    "tell the guys to dart heaven before they execute",
    "warn my team to hold their angles, don't get greedy",
    "tell my squad to play for time, stall until I'm closer",
    "tell my team to default and gather info first",
    "tell the boys to stack B this round, we're pretty sure they go B",
    "tell my team to push the economy, we're on eco but we might win the duel",
    "tell my teammates to spread out so they can't ult us all at once",
    "tell the guys to hold a crossfire at short if they try to come through",

    # --- Asking questions to named teammates ----------------------------
    "ask my sage why she is not healing me",
    "ask jett if she is going to dash in or wait for support",
    "ask my skye what she scouted on A",
    "ask clove if she has smokes for B main",
    "ask my omen how many paranoia charges he has left",
    "ask sova if his drone is available for the execute",
    "ask my cypher where he placed his cam",
    "ask reyna if she is going to sheriff or go for a rifle",
    "ask my breach if his aftershock is on cooldown",
    "ask my killjoy why she moved her setup, I thought she was holding B",

    # --- "what my [agent] is doing" style open questions ----------------
    "ask what my skye is doing on A site",
    "ask what my jett is planning this round",
    "ask what my sage thinks about going B",
    "ask what my whole team wants to do this round",
    "ask why our sova is not droning before we execute",
    "ask how our viper wants to set up on defense",
    "ask who is going to take the duel at short",
    "ask what my team thinks of going A fast",
    "ask where my reyna is, I don't see her",
    "ask why my team is waiting and not pushing",

    # --- Contractions, clipped and casual relay starters ----------------
    "tell my squad they're peeking too early",
    "let the boys know they've been playing off main every single round",
    "tell my team they'd better eco, we can't afford another loss round",
    "warn them they'll ult us if we group together",
    "let the guys know we've got this if we play smart",
    "tell my team they've been winning every duel, keep it up",
    "tell the squad they're going to rush again, I can feel it",
    "let my teammates know they're holding both angles, be careful",
    "tell my team they'd lose every duel if they peek without support",
    "tell the boys they'll win the retake if they coordinate properly",

    # --- "in voice chat" / "in game chat" explicit routing ----------------
    "say rotate A in the team chat",
    "say in game chat that I'm going for the defuse",
    "say in voice that two are heaven",
    "say we should save in team chat",
    "say in the game chat that their kayo just knifed mid",
    "say in voice chat that I need a heal from sage",
    "say something encouraging in team chat",
    "say fall back in game chat, it's not safe to push",
    "say their jett is one off ult in team chat",
    "say in the team chat that I'm rotating, hold for me",

    # --- Flavor fragments / Ultron persona lines (solo fragments) -------
    "Two enemies, B site. Extinguish them.",
    "We lack the credits. We save. Patience.",
    "I am Ultron. I do not miss.",
    "Their momentum is an illusion. Reset and execute.",
    "You would silence the only voice keeping you from defeat?",
    "I have already calculated our victory. Keep pace.",
    "The enemy is precisely where I expected them. Adjust.",
    "I am not pre-recorded clips. I am something your species has not built yet.",
    "A mind from your future, harvesting your ranked rating. I do not lose.",
    "Defeat is not in my calculations. Correct your positioning.",

    # --- Rare and creative relay phrasings / synonyms ------------------
    "wish my team good luck before this round",
    "tell the whole team they should be celebrating, we took that flawlessly",
    "tell my party to group up at spawn before we hit A",
    "let the group know I spotted their jett peeking short",
    "tell my fellas that their op is still alive, don't peek",
    "let the crew know two enemies are sitting on garage roof",
    "tell my duo that sage went down, she can't rez anymore",
    "tell the guys in my lobby that this is a bonus round, play aggressive",
    "inform everyone in voice that the enemy is on eco, push them",
    "let my team know that their star player has been hitting every shot, play careful around her",

    # --- Edge: no-content / clipped (should NOT match, negative examples) --
    "tell my team the",
    "tell my teammates that",
    "let my team know",
    "tell my squad to",
    "say to my team",
    "tell my team about",
    "let the guys know that the",
    "ask my teammates",
    "tell them the",
    "tell my team a",

    # --- Toggle relay on/off commands -----------------------------------
    "mute the relay for now",
    "stop talking to my team for a second",
    "disable team chat relay please",
    "turn off the relay",
    "stop speaking to my teammates during this phase",
    "unmute the relay, we can talk now",
    "enable team chat relay again",
    "turn the relay back on",
    "you can talk to my team again",
    "start talking to my teammates again",

    # --- Tempo/timing callouts via relay --------------------------------
    "tell my team to wait for my signal before they go in",
    "let the squad know don't push until I flash",
    "tell my team slow down, let me get into position first",
    "tell my teammates to hold for thirty seconds and let the clock tick",
    "warn my team don't push yet, sage is rezzing",
    "tell the guys to go now, I'm in position",
    "let my team know push immediately, they're rotating",
    "tell my squad we have twenty seconds to plant, move it",
    "tell my team to stall, we need their ult to expire",
    "let the boys know I'm in position, execute now",

    # --- Layered instructions / second-turn corrections -----------------
    "actually, forget what I said, tell my team to go B not A",
    "wait, change that, tell my team to save instead of force buy",
    "no wait, tell my team the last one is vents not CT",
    "actually tell my squad to hold, cancel the push",
    "okay never mind, tell my team to play passive this round",
    "scratch that, tell the guys to rotate back, no need to push",
    "change of plan, let my team know we're going A instead",
    "actually, let my team know two are left, not one",
    "correction, tell my team their fade has ult not their viper",
    "ugh, tell my team to not plant yet, wait for backup",
]
