"""Relay test vocab pack: streamer opinions on maps, agents, and ranked meta.

Each string is a single utterance -- what the streamer says to relay to
teammates / to Ultron, or a direct opinion/flavor fragment representing the
domain of map love/hate, agent praise/complaints, meta takes, tilt, and
carry claims. Feed these into the relay harness matcher + rephrase to
exercise Ultron's off-snap character work.

Usage:
    from scripts.relay_test.vocab_packs.opinions_maps_meta import ITEMS
"""

ITEMS = [
    # --- map love ---
    "tell my team I love this map",
    "tell my teammates Bind is my favorite map",
    "let my team know Ascent is the best map in the game",
    "tell my team Haven is a perfect map",
    "tell my team I love playing on Split",
    "tell my teammates Lotus is a beautiful map",
    "tell my team Sunset is genuinely great",
    "let my team know Pearl is underrated",
    "tell my team Fracture is actually fun",
    "tell my teammates this map is clean",
    "tell my team I enjoy this map a lot",
    "tell my team Breeze is one of the best designed maps",
    "tell my team Abyss is my kind of map",
    "tell my teammates I always do well on Haven",
    "tell my team this is my best map",
    "let my team know I have a good record on this map",
    "tell my team Ascent plays perfectly for our comp",
    "tell my teammates Split is exactly what we needed",
    "let my team know Bind teleporters are my favorite mechanic",
    "tell my team I would never veto this map",

    # --- map hate ---
    "tell my team I hate Icebox",
    "tell my teammates Icebox is the worst map",
    "let my team know I despise this map",
    "tell my team I would always veto Icebox if I could",
    "tell my teammates this map is terrible",
    "tell my team Breeze is a nightmare to play",
    "let my team know I have a horrible win rate on this map",
    "tell my team I cannot stand Fracture",
    "tell my teammates this is my least favorite map",
    "tell my team Icebox is not fun to play",
    "let my team know this map tilts me every time",
    "tell my teammates I hate the layout of this map",
    "tell my team the sightlines on this map are awful",
    "tell my teammates this map punishes aggressive play too hard",
    "tell my team I never win on Breeze",
    "let my team know I wish we had vetoed this",
    "tell my team I would rather play any other map",
    "tell my teammates the rotates on this map are too long",
    "tell my team I hate the open angles on this map",
    "tell my team this map is not made for my playstyle",

    # --- map veto talk ---
    "tell my team we should have vetoed Icebox",
    "tell my teammates we vetoed the wrong map",
    "let my team know we should always veto Breeze",
    "tell my team I wish we could have banned this map",
    "tell my teammates we need to agree on our veto before queue",
    "let my team know next time we veto this map first",
    "tell my team our veto strategy is wrong",
    "tell my teammates always veto Icebox, never veto Ascent",
    "tell my team we gave them their best map",
    "tell my teammates they banned our best map",

    # --- agent love ---
    "tell my team I love playing Jett",
    "tell my teammates Jett is my favorite agent",
    "let my team know Reyna is the best duelist",
    "tell my team Jett is broken on this map",
    "tell my teammates I only play Jett",
    "tell my team Omen is the most fun agent",
    "let my team know Neon is insane right now",
    "tell my team Clove is the best controller",
    "tell my teammates Cypher is my comfort pick",
    "tell my team I love playing Sova on this map",
    "let my team know Sage is criminally underrated",
    "tell my team Raze is so satisfying to play",
    "tell my teammates Killjoy is perfectly designed",
    "let my team know I have the most hours on Jett",
    "tell my team Phoenix feels great right now",

    # --- agent hate / complaints ---
    "tell my team Chamber is still broken",
    "tell my teammates Chamber needs another nerf",
    "let my team know I hate playing against Viper",
    "tell my team Viper walls are frustrating to play against",
    "tell my teammates I always lose to a good Yoru",
    "tell my team Yoru is the most annoying agent in the game",
    "let my team know Harbor is the worst agent in the game",
    "tell my teammates Harbor needs a rework",
    "tell my team Astra is too complicated for no reason",
    "let my team know Deadlock is useless on attack",
    "tell my team Skye flash is the most broken utility",
    "tell my teammates Breach is borderline broken right now",
    "let my team know I hate facing a Breach and Skye combo",
    "tell my team Iso is still not in a good spot",
    "let my team know Gekko is overhyped",

    # --- agent meta / tier takes ---
    "tell my team Jett is S tier on every map",
    "tell my teammates Reyna is the best agent for ranked",
    "let my team know Omen is A tier right now",
    "tell my team Viper is mandatory on Breeze and Icebox",
    "tell my teammates Sova is the best initiator in ranked",
    "tell my team you need an Omen or Brimstone on this map",
    "let my team know Clove is sleeper tier S this patch",
    "tell my teammates KAY/O is criminally underplayed",
    "tell my team Fade is better than Skye right now",
    "let my team know Sage should be in every comp",
    "tell my team Neon is meta right now",
    "tell my teammates Cypher is secretly top tier on this map",
    "tell my team running double controller is the move",
    "let my team know double duelist comps are a mistake in ranked",
    "tell my teammates five op is the only way to play Icebox",

    # --- this agent is broken ---
    "tell my team that agent is broken",
    "tell my teammates whoever made that ability was on something",
    "let my team know this kit is completely overtuned",
    "tell my team that ability has zero counterplay",
    "tell my teammates the hitbox on that ability is insane",
    "tell my team that utility should not exist",
    "let my team know that ult is unfair",
    "tell my team this agent has too much value for zero skill",
    "tell my teammates that kit does everything",
    "let my team know whoever picked that agent got a free win agent",

    # --- ranked is pain ---
    "tell my team ranked is a nightmare right now",
    "tell my teammates ranked is broken this act",
    "let my team know soloq is a disaster",
    "tell my team ranked matchmaking is terrible",
    "tell my teammates the rank system is a lie",
    "let my team know I have been hardstuck for three weeks",
    "tell my team deranking feels rigged",
    "tell my teammates ranked is not fun this episode",
    "tell my team I hate solo queue",
    "let my team know ranked queue gives me the worst teammates every game",
    "tell my team the rank distribution is completely broken",
    "tell my teammates I should be higher ranked than this",
    "let my team know I play way better than my rank",
    "tell my team losing RR to teammates who do not try is infuriating",
    "tell my teammates this ranking system does not reward skill",
    "let my team know I am going to hit Radiant eventually and it will not be pretty",
    "tell my team ranked is psychological warfare not a game",
    "tell my teammates every time I win streak I get thrown into a loss streak",
    "let my team know riot matchmaking is personal",
    "tell my team I am taking a break from ranked after this",

    # --- hard carrying ---
    "tell my team I am hard carrying right now",
    "tell my teammates I am the only reason we are still in this",
    "let my team know I am carrying this whole lobby",
    "tell my team without me we would be down ten rounds",
    "tell my teammates I have been the entry every single round",
    "let my team know I am doing everything out here",
    "tell my team I have more damage than the rest of the team combined",
    "tell my teammates the stats do not lie, I am the best player here",
    "tell my team I cannot keep playing five versus five by myself",
    "let my team know this is a solo carry situation",
    "tell my teammates I am the only one buying rifles",
    "tell my team I have three aces this half and they are complaining",
    "let my team know I am not letting a four versus five beat me",
    "tell my team I refuse to lose this after my performance",
    "tell my teammates I am built different on this map",

    # --- I am washed ---
    "tell my team I am washed today",
    "tell my teammates my aim is not working today",
    "let my team know I am off today, my bad",
    "tell my team I am playing like a bronze today",
    "tell my teammates I am having the worst game of my life",
    "tell my team my mechanics are broken today",
    "let my team know I am losing every duel I take",
    "tell my team I cannot hit a single shot today",
    "tell my teammates I have been missing everything, I am not usually like this",
    "let my team know my brain is not working today",
    "tell my team I need to warm up in the range",
    "tell my teammates aimlabs is free and I need to use it",
    "tell my team I am uninstalling after this",
    "let my team know I peaked last week, it is downhill from here",
    "tell my teammates I am sorry for dragging you down today",

    # --- tilt / frustration ---
    "tell my team I am so tilted right now",
    "tell my teammates I cannot believe what just happened",
    "let my team know I am on tilt, please be patient with me",
    "tell my team I am losing my mind this game",
    "tell my teammates I am barely holding it together",
    "tell my team that death was so avoidable, I am tilting",
    "let my team know I need a second to calm down",
    "tell my team I am getting flamed and it is making things worse",
    "tell my teammates that was the most frustrating death I have ever had",
    "let my team know I need everyone to stop flaming and just play",
    "tell my team I am tilted off the planet",
    "tell my teammates I am about to uninstall this game",
    "let my team know I keep getting unlucky all game",
    "tell my team the RNG in this game is criminal",
    "tell my teammates I have died to this exact angle four times today",

    # --- love playing agent on this specific map ---
    "tell my team I love playing Jett here",
    "tell my teammates Jett is so strong on this map",
    "let my team know this is the best map for Reyna",
    "tell my team I could play Sova on Icebox every day",
    "tell my teammates Killjoy on Ascent is the best combo",
    "tell my team Omen is perfect for this map",
    "let my team know I always play Cypher here and it works",
    "tell my team Jett on Breeze is a cheat code",
    "tell my teammates Neon on Bind is so fun to play",
    "let my team know Sage on Split is still secretly broken",
    "tell my team I love how Viper fits into this map",
    "tell my teammates Raze on this map is incredible",
    "let my team know Harbor on Pearl is actually viable",
    "tell my team this is why I main Jett on Ascent",
    "tell my teammates I only pick Fade on this specific map",

    # --- meta complaints ---
    "tell my team the meta is stale right now",
    "tell my teammates riot keeps buffing the wrong agents",
    "let my team know the patch broke the meta completely",
    "tell my team this patch is not balanced at all",
    "tell my teammates riot keeps nerfing my agents",
    "tell my team the same three agents have been meta for six months",
    "let my team know the new agent is already broken",
    "tell my teammates riot does not test patches properly",
    "tell my team the current meta does not reward mechanics",
    "let my team know I am tired of seeing the same four agents every game",
    "tell my team vision denial was more interesting before the nerfs",
    "tell my teammates the controller meta is ruining ranked",
    "let my team know too many flash abilities exist right now",
    "tell my team one way smokes should not be so dominant",
    "tell my teammates the sentinel meta is boring to play against",

    # --- specific map opinions (detailed) ---
    "tell my team Icebox is the worst designed map in the game",
    "tell my teammates the angles on Icebox are unfair",
    "let my team know Icebox rewards passive play too much",
    "tell my team Breeze feels too open for ranked",
    "tell my teammates Fracture has the most unique layout in the game",
    "tell my team Haven is the most complete map Riot ever made",
    "let my team know Split mid is the most important real estate in any map",
    "tell my team Ascent is the most balanced map they have shipped",
    "tell my teammates Lotus has the best rotation paths",
    "let my team know Sunset is a sleeper pick for our comp",
    "tell my team Abyss is beautiful but punishing",
    "tell my teammates Pearl B site is the most stressful place in the game",
    "let my team know Bind teleporters change the whole meta on this map",
    "tell my team the vertical angles on Icebox are completely broken",
    "tell my teammates this map pool needs a refresh",

    # --- direct persona / flavor fragments (Ultron relaying the streamer's voice) ---
    "tell my team Bind is the best map in the pool and I will die on this hill",
    "tell my teammates I only queue when Icebox is not in the pool",
    "let my team know my map win rate on Ascent is above seventy percent",
    "tell my team I have not lost on Haven in two weeks",
    "tell my teammates if you ever make me play Breeze again I am logging off",
    "tell my team I have played Jett for three thousand hours and I am not stopping",
    "let my team know ranked is suffering and I am here for all of it",
    "tell my teammates I am the best Jett in this lobby and it is not close",
    "tell my team I am built for this map specifically",
    "let my team know I have more kills than the entire enemy team and we are losing",
    "tell my teammates my agents get nerfed every single patch",
    "tell my team I refused to learn any agent except Jett and I regret nothing",
    "let my team know I would rather lose on Bind than win on Icebox",
    "tell my teammates I have watched every pro player play Reyna and I still lose",
    "tell my team I have five hundred hours on Icebox and I still hate it",
    "tell my teammates this is my comfort map and I am still struggling",
    "let my team know I started playing this game for fun and somehow ended up hardstuck",
    "tell my team the enemy team is playing this map like pros and I am not",
    "tell my teammates this map is why I main controller on weekdays",
    "let my team know I would veto every map except Ascent if the game let me",
]
