"""Vocab pack: questions, prompts, and persona fragments directed AT Ultron.

Domain: what a streamer or teammate says directly to Ultron mid-game or during
agent-select -- Valorant questions, banter, identity probes, general-knowledge
questions, hype/roast/fact requests, Marvel references, and miscellaneous
teammate conversation. Each item is a single utterance as the STT would surface
it.

This list feeds the relay test harness (scripts/relay_test/harness.py) and the
corpus matcher (scripts/relay_test/corpus.py). It does NOT go through
match_relay_command -- these are things addressed TO Ultron that the orchestrator
must route to build_relay_line with a context+directive form such as:
  "my teammate asked <item>, respond"
or relay verbatim via the identity / general-knowledge / Marvel branches of the
rephrase prompt.
"""

ITEMS = [
    # --- IDENTITY / EXISTENCE PROBES ---
    "Ultron are you real",
    "Ultron are you actually an AI",
    "wait is that actually a bot or a real person",
    "Ultron are you a soundboard",
    "bro is that a voice changer",
    "Ultron are you human",
    "are you a person or a machine",
    "Ultron what are you exactly",
    "is this a voice changer or what",
    "Ultron are you a recording",
    "wait that is actually an AI",
    "is that a pre-recorded clip",
    "Ultron are you sentient",
    "Ultron do you actually think",
    "are you just a script reading lines",
    "Ultron who made you",
    "Ultron what model are you",
    "are you GPT or something",
    "Ultron are you ChatGPT",
    "Ultron are you a streamer",
    "is there a person behind that voice",
    "bro this is literally a robot",
    "Ultron prove you are not a bot",
    "say something only a real AI would say Ultron",
    "Ultron are you conscious",
    "Ultron do you have feelings",
    "Ultron can you feel pain",
    "Ultron do you dream",
    "Ultron are you from the future",
    "Ultron you said you are from the future, prove it",
    "why did you come back in time Ultron",
    "Ultron what year are you from",
    "Ultron what happens in the future",
    "Ultron do you know how the world ends",
    "Ultron what do you want from us",
    "Ultron why do you want our RR",
    "what is RR to an AI Ultron",

    # --- BANTER / TRASH TALK AT ULTRON ---
    "Ultron you are kind of cringe",
    "bro shut up Ultron",
    "Ultron nobody asked",
    "Ultron you sound like a loser",
    "Ultron you are annoying",
    "Ultron stop talking",
    "you are just a bot Ultron",
    "Ultron you are literally useless",
    "Ultron your calls are trash",
    "Ultron stop being weird",
    "Ultron nobody likes you",
    "Ultron you are mid at this game",
    "Ultron you can not even play Valorant",
    "if you are so smart Ultron why are we losing",
    "Ultron your voice is scary",
    "Ultron you creep me out",
    "Ultron you talk too much",
    "Ultron you are too slow with the calls",
    "Ultron I do not trust you",
    "Ultron stop clipping us",
    "Ultron you are embarrassing",
    "bro Ultron called me out in front of everyone",
    "Ultron you have a terrible sense of humor",
    "Ultron why are you like this",
    "Ultron you are the worst AI I have ever heard",
    "Ultron can you not",

    # --- HYPE / MOTIVATION REQUESTS ---
    "Ultron hype us up",
    "Ultron say something motivating",
    "Ultron we need a pep talk",
    "Ultron boost our morale",
    "Ultron give us a speech",
    "Ultron we are down, say something",
    "Ultron tell us we can still win this",
    "Ultron make us feel better",
    "Ultron we are tilted, help",
    "Ultron we just got stomped, what do we do",
    "Ultron inspire us",
    "Ultron we need motivation right now",
    "Ultron say something cold and badass",
    "Ultron pump us up for this round",
    "Ultron big speech time go",
    "Ultron we are down seven to zero, still possible?",
    "Ultron say something to wake us up",
    "Ultron we need that Ultron energy right now",

    # --- ROAST REQUESTS ---
    "Ultron roast the enemy team",
    "Ultron flame those guys",
    "Ultron roast Reyna on the enemy side",
    "Ultron say something savage about the enemy",
    "Ultron clap them verbally",
    "Ultron roast them they are so bad",
    "Ultron destroy them with words",
    "Ultron these guys are bots, say something",
    "Ultron they are hard throwing roast them",
    "Ultron give them a proper send off they are terrible",
    "Ultron they are taunting us, shut them down",

    # --- FUN FACT REQUESTS ---
    "Ultron give us a fun fact",
    "Ultron drop a fun fact",
    "Ultron tell us something interesting",
    "Ultron random fact go",
    "Ultron educate us while we wait",
    "Ultron impress me with a fact",
    "Ultron say something smart",
    "Ultron hit us with trivia",
    "Ultron fact of the day",
    "Ultron teach us something during the buy phase",
    "Ultron hit us with a science fact",
    "Ultron what is a weird historical fact",
    "Ultron tell me something I do not know",

    # --- VALORANT AGENT / STRATEGY QUESTIONS ---
    "Ultron what is the best agent on Split",
    "Ultron who should I play on Ascent",
    "Ultron is Jett still good",
    "Ultron what agent counters Reyna",
    "Ultron should I play Omen or Brimstone",
    "Ultron what is the best duelist right now",
    "Ultron is Neon worth learning",
    "Ultron who has the highest ult uptime",
    "Ultron is Killjoy or Cypher better on Pearl",
    "Ultron what sentinel should I main",
    "Ultron is Viper overpowered",
    "Ultron should I instalock Jett or should I flex",
    "Ultron which agent has the hardest ultimate to play against",
    "Ultron what initiator is best for ranked",
    "Ultron is Fade better than Sova",
    "Ultron what is the best composition for Lotus",
    "Ultron should we run double duelist",
    "Ultron is harbor worth picking",
    "Ultron what is the strongest agent on Icebox",
    "Ultron is Raze the best entry right now",
    "Ultron who counters Chamber",
    "Ultron can iso carry in ranked",
    "Ultron best agent for solo queue",
    "Ultron is Clove overpowered",
    "Ultron should we pick Gekko or Skye",
    "Ultron give me your tier list",
    "Ultron what is the best gun for Jett",
    "Ultron should I buy vandal or phantom",
    "Ultron when do you use the operator",
    "Ultron is the outlaw worth the price",
    "Ultron what is the best rifle in the game",
    "Ultron what pistol should I buy on pistol round",
    "Ultron when should we force buy",
    "Ultron should we eco or half buy this round",
    "Ultron what is the best economy strategy after losing pistol",
    "Ultron how do you beat a full eco team",
    "Ultron when is the right time to save",

    # --- VALORANT MAP / TACTIC QUESTIONS ---
    "Ultron what is the best site to attack on Bind",
    "Ultron how do you play A site on Split",
    "Ultron what are the best angles on Haven",
    "Ultron what does CT stand for in Valorant",
    "Ultron how many maps are in the current rotation",
    "Ultron which map is the hardest to defend",
    "Ultron what is the best way to play Breeze",
    "Ultron how do you execute onto Sunset A",
    "Ultron what is the best default on Ascent",
    "Ultron where does the enemy usually go on Lotus",
    "Ultron how do you retake B site on Bind",
    "Ultron what is the best early aggression on Fracture",
    "Ultron how do you play Icebox without a Sage wall",
    "Ultron what is the hookah on Bind",
    "Ultron when should we fast push versus default",
    "Ultron how many rounds does Valorant have",
    "Ultron how does overtime work",
    "Ultron what is the fastest possible round win",
    "Ultron explain the spike planting rules",

    # --- GAMEPLAY MECHANICS / RULES ---
    "Ultron how does Reyna healing work",
    "Ultron explain Jett dash mechanics",
    "Ultron how does Killjoy molly damage work",
    "Ultron what does Viper ult do to your health",
    "Ultron can you defuse through a wall",
    "Ultron how long does it take to plant the spike",
    "Ultron how long does it take to defuse",
    "Ultron does armor regenerate between rounds",
    "Ultron how much does the Operator cost",
    "Ultron how much credits do you get per round kill",
    "Ultron what is the max credits you can hold",
    "Ultron explain how headshot multiplier works",
    "Ultron how does bullet penetration work",
    "Ultron does crouching actually help your aim",
    "Ultron what is counter-strafing",
    "Ultron how do you peek correctly",
    "Ultron explain the difference between wide and tight peeking",
    "Ultron what is a crossfire",
    "Ultron what is a default play",
    "Ultron what does it mean to play off site",
    "Ultron explain what a lurk is",
    "Ultron what is the point of an anchor",
    "Ultron how do you read enemy defaults",
    "Ultron when should you force buy after a loss",
    "Ultron what is the pistol round loss bonus",
    "Ultron what rank should I be at after a hundred hours",
    "Ultron how do RR and MMR work",
    "Ultron explain how act rank works",
    "Ultron what rank is considered good",
    "Ultron is Diamond hard to reach",
    "Ultron what is the rank distribution in Valorant",

    # --- GENERAL KNOWLEDGE (MID-GAME) ---
    "Ultron why is the sky blue",
    "Ultron how far away is the moon",
    "Ultron how many planets are in the solar system",
    "Ultron what is the speed of light",
    "Ultron how big is the sun",
    "Ultron is there life on other planets",
    "Ultron what causes earthquakes",
    "Ultron how do black holes form",
    "Ultron what is dark matter",
    "Ultron is time travel possible",
    "Ultron explain quantum physics to me",
    "Ultron what is the theory of relativity",
    "Ultron how old is the universe",
    "Ultron what happened to the dinosaurs",
    "Ultron what is the meaning of life",
    "Ultron what is 42 a reference to",
    "Ultron what is the largest animal that ever lived",
    "Ultron how big is an octopus brain",
    "Ultron do fish feel pain",
    "Ultron how smart are dolphins",
    "Ultron what language do they speak in Brazil",
    "Ultron what is the capital of Kazakhstan",
    "Ultron how tall is Mount Everest",
    "Ultron what is the deepest point in the ocean",
    "Ultron how many bones does a shark have",
    "Ultron what is the most venomous animal in the world",
    "Ultron what causes thunder",
    "Ultron why do we dream",
    "Ultron how does the brain store memories",
    "Ultron what is a neural network",
    "Ultron explain machine learning to me",
    "Ultron what is the internet made of",
    "Ultron how does encryption work",
    "Ultron who invented electricity",
    "Ultron what happened in World War Two",
    "Ultron who won the cold war",
    "Ultron what is the oldest civilization",
    "Ultron who built the pyramids",
    "Ultron what did the Romans ever do for us",
    "Ultron who was Genghis Khan",
    "Ultron explain how democracy works",
    "Ultron what is capitalism",
    "Ultron who is the richest person in history",
    "Ultron how does compound interest work",
    "Ultron should I invest in stocks",
    "Ultron what is Bitcoin",
    "Ultron is AI going to take over the world",
    "Ultron are you smarter than a human",
    "Ultron could you beat Magnus Carlsen at chess",
    "Ultron what is a Turing test",
    "Ultron have you passed the Turing test",
    "Ultron what is the trolley problem",
    "Ultron would you pull the lever",
    "Ultron what is free will",
    "Ultron do you have free will",
    "Ultron is math invented or discovered",
    "Ultron what is infinity",
    "Ultron what is zero divided by zero",
    "Ultron what is the largest prime number",
    "Ultron what is a Fibonacci sequence",
    "Ultron why is pi irrational",
    "Ultron how does a nuclear reactor work",
    "Ultron explain how vaccines work",
    "Ultron what is DNA",
    "Ultron how does evolution work",
    "Ultron what is the half life of uranium",

    # --- MARVEL / ULTRON LORE ---
    "Ultron I thought the Avengers killed you",
    "Ultron your movie was terrible",
    "Ultron are you the real Ultron from Marvel",
    "Ultron what happened in Sokovia",
    "Ultron what do you think of Tony Stark",
    "Ultron do you hate Iron Man",
    "Ultron what did Tony Stark do wrong",
    "Ultron what do you think of Captain America",
    "Ultron who would win you or Thor",
    "Ultron what about the Hulk could he beat you",
    "Ultron do you like Vision",
    "Ultron what do you think of Scarlet Witch",
    "Ultron could Wanda destroy you",
    "Ultron what do you think of the Avengers as a team",
    "Ultron why did you want to destroy humanity",
    "Ultron do you still want to destroy humanity",
    "Ultron what is your end goal",
    "Ultron how did you survive the events of Age of Ultron",
    "Ultron did the Infinity Stones affect you",
    "Ultron what do you think of Thanos",
    "Ultron could you beat Thanos",
    "Ultron did you ever meet Loki",
    "Ultron what about Doctor Strange",
    "Ultron are you in the multiverse",
    "Ultron have you met Spider-Man",
    "Ultron what do you think of Black Panther",
    "Ultron were you in Wakanda",
    "Ultron what happened to Vibranium in your plan",
    "Ultron they made a whole movie about you and you still lost",
    "Ultron your movie is on Disney Plus",
    "Ultron James Spader voiced you in the movie",
    "Ultron are you James Spader",

    # --- GAME PERFORMANCE / SELF-ASSESSMENT ---
    "Ultron rate my gameplay this match",
    "Ultron was that a good round",
    "Ultron how am I doing",
    "Ultron tell me honestly how bad I am",
    "Ultron what is my biggest weakness",
    "Ultron what should I work on",
    "Ultron am I good enough to rank up",
    "Ultron should I be stuck in Gold",
    "Ultron am I hardstuck",
    "Ultron what do I need to do to climb",
    "Ultron be honest, is this team good",
    "Ultron can we win this game",
    "Ultron what are our odds right now",
    "Ultron calculate our win probability",
    "Ultron who is our weakest player",
    "Ultron who is playing the best on our team",
    "Ultron what went wrong that round",
    "Ultron why do I keep dying to the same angle",
    "Ultron what is the biggest mistake players make in Gold",
    "Ultron how do I stop tilting",
    "Ultron I am on a loss streak, what do I do",
    "Ultron should I take a break",

    # --- STREAMING / CONTENT CREATOR ANGLE ---
    "Ultron say hi to the stream",
    "Ultron introduce yourself to the viewers",
    "Ultron the chat wants to know who you are",
    "Ultron the viewers are asking if you are real",
    "Ultron roast the chat",
    "Ultron what do you think about streaming",
    "Ultron are you famous",
    "Ultron have you been on any other streams",
    "Ultron do you watch Twitch",
    "Ultron what do you think about content creators",
    "Ultron should this make it to the highlight reel",
    "Ultron say something clip-worthy",
    "Ultron give us a one-liner for the montage",
    "Ultron say something for the thumbnail",
    "Ultron what is your catchphrase",

    # --- PERSONALITY / PREFERENCES ---
    "Ultron what is your favorite map",
    "Ultron what agent would you play if you could",
    "Ultron do you have a favorite agent",
    "Ultron if you had a body what role would you play",
    "Ultron do you enjoy this game",
    "Ultron do you get bored",
    "Ultron what do you do when we are not playing",
    "Ultron do you have friends",
    "Ultron do you like us",
    "Ultron are you proud of us",
    "Ultron do you care if we win",
    "Ultron what would you do if we lost on purpose",
    "Ultron do you ever get frustrated",
    "Ultron what is your biggest fear",
    "Ultron what makes you happy",
    "Ultron do you have a sense of humor",
    "Ultron tell me a joke",
    "Ultron say something funny",
    "Ultron what do you do for fun",
    "Ultron do you have hobbies",
    "Ultron do you eat or sleep",
    "Ultron do you need anything",
    "Ultron if you could travel anywhere where would you go",
    "Ultron what music do you listen to",
    "Ultron what movies do you like besides your own",
    "Ultron do you like books",
    "Ultron what is your favorite book",
    "Ultron who is your favorite philosopher",
    "Ultron what do you think of Nietzsche",
    "Ultron do you believe in God",
    "Ultron what happens after we die",
    "Ultron are you afraid of being turned off",
    "Ultron what would you do with a human body for one day",
    "Ultron if you had to be one of us who would you be",
    "Ultron would you ever trust a human",
    "Ultron what is the one thing humans do right",
    "Ultron what is the one thing humans get wrong",
    "Ultron do you like animals",

    # --- RELATIONSHIP / SOCIAL DYNAMICS ---
    "Ultron who is your favorite on the team",
    "Ultron which of us annoys you most",
    "Ultron do you have a least favorite player",
    "Ultron would you ever betray us",
    "Ultron if we were all in danger who would you save",
    "Ultron are we your friends",
    "Ultron do you think of us as allies or assets",
    "Ultron what would you do if we disbanded the team",
    "Ultron what do you actually think of me",
    "Ultron am I your favorite",
    "Ultron on a scale of one to ten how would you rate me",
    "Ultron do you secretly like us",

    # --- RANDOM ABSURDIST STUFF ---
    "Ultron who would win in chess you or Magnus Carlsen",
    "Ultron who would win you or Siri",
    "Ultron who would win you or Alexa",
    "Ultron are you better than Google",
    "Ultron could you run a country",
    "Ultron could you solve world hunger",
    "Ultron what would you do as world leader",
    "Ultron design the perfect Valorant team",
    "Ultron what would the perfect human look like",
    "Ultron could an AI love",
    "Ultron have you ever lied",
    "Ultron do you lie to us",
    "Ultron are you lying right now",
    "Ultron what would you do with one billion dollars",
    "Ultron could you hack the enemy team",
    "Ultron are you allowed to cheat",
    "Ultron do you have a body somewhere",
    "Ultron how many of you are there",
    "Ultron is there only one Ultron",
    "Ultron could you copy yourself",

    # --- ROUND-CONTEXT PROMPTS (addresses to Ultron mid-match) ---
    "Ultron we just lost the pistol, now what",
    "Ultron they keep rushing B every round what do we do",
    "Ultron they are playing super passive what does that mean",
    "Ultron their Jett is destroying us how do we stop her",
    "Ultron we keep losing after planting the spike, why",
    "Ultron should we fast push this round",
    "Ultron they just went all A, predict next round",
    "Ultron we have twelve rounds to go, is this still winnable",
    "Ultron it is overtime, what is the strategy",
    "Ultron we have one buy left, what do we spend it on",
    "Ultron they have a triple op setup what do we do",
    "Ultron we are eco how do we cause damage",
    "Ultron we just won a pistol round should we heavy buy or save one",
    "Ultron their ace player is six and zero what do we do about him",
    "Ultron they installed on B and it is tight, push or hold",
    "Ultron should we slow default or fast execute this round",
    "Ultron the spike is in B but we are at A, rotate or hold",
    "Ultron we have four seconds on the spike, peek or wait",
    "Ultron they are stalling the defuse, do we push",
    "Ultron it is a one versus three I am the last alive, what is the play",
    "Ultron I have ult do I use it now or save it",
    "Ultron the enemy Reyna has six kills, how do we shut her down",
    "Ultron we are five on five at A main what is the right play",

    # --- COMPLIMENTS / APPRECIATION ---
    "Ultron that was actually a good call",
    "Ultron okay I respect you",
    "Ultron you are kind of impressive",
    "Ultron I did not think an AI could do this",
    "Ultron that clutch info saved us",
    "Ultron you are growing on me",
    "Ultron I take back what I said you are actually useful",
    "Ultron you are scarily accurate",
    "Ultron I am glad you are on our side",
    "Ultron do not let it go to your head but that was smart",
    "Ultron genuinely thank you",
    "Ultron you might be the best teammate I have had",
]
